<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 17 Estimation Methods | Probability and Statistics for Scientists and Engineers</title>
  <meta name="description" content="This is a set of notes for Math 356 that has been compiled into a book." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 17 Estimation Methods | Probability and Statistics for Scientists and Engineers" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="/figures/Cover.png" />
  <meta property="og:description" content="This is a set of notes for Math 356 that has been compiled into a book." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 17 Estimation Methods | Probability and Statistics for Scientists and Engineers" />
  
  <meta name="twitter:description" content="This is a set of notes for Math 356 that has been compiled into a book." />
  <meta name="twitter:image" content="/figures/Cover.png" />

<meta name="author" content="Matthew Davis" />
<meta name="author" content="Brianna Hitt" />
<meta name="author" content="Ken Horton" />
<meta name="author" content="Bradley Warner" />


<meta name="date" content="2021-11-19" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="TRANS.html"/>
<link rel="next" href="CS3.html"/>
<script src="libs/header-attrs-2.11/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Probability and Statistics for Scientists and Engineers</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#who-is-this-book-for"><i class="fa fa-check"></i><b>0.1</b> Who is this book for?</a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#book-structure-and-how-to-use-it"><i class="fa fa-check"></i><b>0.2</b> Book Structure and How to Use It</a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i><b>0.3</b> Prerequisites</a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#packages"><i class="fa fa-check"></i><b>0.4</b> Packages</a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.5</b> Acknowledgements</a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#file-creation-information"><i class="fa fa-check"></i><b>0.6</b> File Creation Information</a></li>
</ul></li>
<li class="part"><span><b>I Descriptive Statistical Modeling</b></span></li>
<li class="chapter" data-level="1" data-path="CS1.html"><a href="CS1.html"><i class="fa fa-check"></i><b>1</b> Case Study</a>
<ul>
<li class="chapter" data-level="1.1" data-path="CS1.html"><a href="CS1.html#objectives"><i class="fa fa-check"></i><b>1.1</b> Objectives</a></li>
<li class="chapter" data-level="1.2" data-path="CS1.html"><a href="CS1.html#introduction-to-descriptive-statistical-modeling"><i class="fa fa-check"></i><b>1.2</b> Introduction to Descriptive Statistical Modeling</a></li>
<li class="chapter" data-level="1.3" data-path="CS1.html"><a href="CS1.html#the-data-analytic-process"><i class="fa fa-check"></i><b>1.3</b> The data analytic process</a></li>
<li class="chapter" data-level="1.4" data-path="CS1.html"><a href="CS1.html#case-study"><i class="fa fa-check"></i><b>1.4</b> Case study</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="CS1.html"><a href="CS1.html#research-question"><i class="fa fa-check"></i><b>1.4.1</b> Research question</a></li>
<li class="chapter" data-level="1.4.2" data-path="CS1.html"><a href="CS1.html#collect-the-relevant-data"><i class="fa fa-check"></i><b>1.4.2</b> Collect the relevant data</a></li>
<li class="chapter" data-level="1.4.3" data-path="CS1.html"><a href="CS1.html#import-data"><i class="fa fa-check"></i><b>1.4.3</b> Import data</a></li>
<li class="chapter" data-level="1.4.4" data-path="CS1.html"><a href="CS1.html#explore-data"><i class="fa fa-check"></i><b>1.4.4</b> Explore data</a></li>
<li class="chapter" data-level="1.4.5" data-path="CS1.html"><a href="CS1.html#visualize-the-data"><i class="fa fa-check"></i><b>1.4.5</b> Visualize the data</a></li>
<li class="chapter" data-level="1.4.6" data-path="CS1.html"><a href="CS1.html#conclusion"><i class="fa fa-check"></i><b>1.4.6</b> Conclusion</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="CS1.html"><a href="CS1.html#homework-problems"><i class="fa fa-check"></i><b>1.5</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="DB.html"><a href="DB.html"><i class="fa fa-check"></i><b>2</b> Data Basics</a>
<ul>
<li class="chapter" data-level="2.1" data-path="DB.html"><a href="DB.html#objectives-1"><i class="fa fa-check"></i><b>2.1</b> Objectives</a></li>
<li class="chapter" data-level="2.2" data-path="DB.html"><a href="DB.html#data-basics"><i class="fa fa-check"></i><b>2.2</b> Data basics</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="DB.html"><a href="DB.html#observations-variables-and-data-matrices"><i class="fa fa-check"></i><b>2.2.1</b> Observations, variables, and data matrices</a></li>
<li class="chapter" data-level="2.2.2" data-path="DB.html"><a href="DB.html#types-of-variables"><i class="fa fa-check"></i><b>2.2.2</b> Types of variables</a></li>
<li class="chapter" data-level="2.2.3" data-path="DB.html"><a href="DB.html#relationships-between-variables"><i class="fa fa-check"></i><b>2.2.3</b> Relationships between variables</a></li>
<li class="chapter" data-level="2.2.4" data-path="DB.html"><a href="DB.html#creating-a-scatterplot"><i class="fa fa-check"></i><b>2.2.4</b> Creating a scatterplot</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="DB.html"><a href="DB.html#homework-problems-1"><i class="fa fa-check"></i><b>2.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ODCP.html"><a href="ODCP.html"><i class="fa fa-check"></i><b>3</b> Overview of Data Collection Principles</a>
<ul>
<li class="chapter" data-level="3.1" data-path="ODCP.html"><a href="ODCP.html#objectives-2"><i class="fa fa-check"></i><b>3.1</b> Objectives</a></li>
<li class="chapter" data-level="3.2" data-path="ODCP.html"><a href="ODCP.html#overview-of-data-collection-principles"><i class="fa fa-check"></i><b>3.2</b> Overview of data collection principles</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="ODCP.html"><a href="ODCP.html#populations-and-samples"><i class="fa fa-check"></i><b>3.2.1</b> Populations and samples</a></li>
<li class="chapter" data-level="3.2.2" data-path="ODCP.html"><a href="ODCP.html#anecdotal-evidence"><i class="fa fa-check"></i><b>3.2.2</b> Anecdotal evidence</a></li>
<li class="chapter" data-level="3.2.3" data-path="ODCP.html"><a href="ODCP.html#sampling-from-a-population"><i class="fa fa-check"></i><b>3.2.3</b> Sampling from a population</a></li>
<li class="chapter" data-level="3.2.4" data-path="ODCP.html"><a href="ODCP.html#explanatory-and-response-variables"><i class="fa fa-check"></i><b>3.2.4</b> Explanatory and response variables</a></li>
<li class="chapter" data-level="3.2.5" data-path="ODCP.html"><a href="ODCP.html#introducing-observational-studies-and-experiments"><i class="fa fa-check"></i><b>3.2.5</b> Introducing observational studies and experiments</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="ODCP.html"><a href="ODCP.html#homework-problems-2"><i class="fa fa-check"></i><b>3.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="STUDY.html"><a href="STUDY.html"><i class="fa fa-check"></i><b>4</b> Studies</a>
<ul>
<li class="chapter" data-level="4.1" data-path="STUDY.html"><a href="STUDY.html#objectives-3"><i class="fa fa-check"></i><b>4.1</b> Objectives</a></li>
<li class="chapter" data-level="4.2" data-path="STUDY.html"><a href="STUDY.html#observation-studies-sampling-strategies-and-experiments"><i class="fa fa-check"></i><b>4.2</b> Observation studies, sampling strategies, and experiments</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="STUDY.html"><a href="STUDY.html#observational-studies"><i class="fa fa-check"></i><b>4.2.1</b> Observational studies</a></li>
<li class="chapter" data-level="4.2.2" data-path="STUDY.html"><a href="STUDY.html#three-sampling-methods"><i class="fa fa-check"></i><b>4.2.2</b> Three sampling methods</a></li>
<li class="chapter" data-level="4.2.3" data-path="STUDY.html"><a href="STUDY.html#experiments"><i class="fa fa-check"></i><b>4.2.3</b> Experiments</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="STUDY.html"><a href="STUDY.html#homework-problems-3"><i class="fa fa-check"></i><b>4.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="NUMDATA.html"><a href="NUMDATA.html"><i class="fa fa-check"></i><b>5</b> Numerical Data</a>
<ul>
<li class="chapter" data-level="5.1" data-path="NUMDATA.html"><a href="NUMDATA.html#objectives-4"><i class="fa fa-check"></i><b>5.1</b> Objectives</a></li>
<li class="chapter" data-level="5.2" data-path="NUMDATA.html"><a href="NUMDATA.html#numerical-data"><i class="fa fa-check"></i><b>5.2</b> Numerical Data</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="NUMDATA.html"><a href="NUMDATA.html#scatterplots-for-paired-data"><i class="fa fa-check"></i><b>5.2.1</b> Scatterplots for paired data</a></li>
<li class="chapter" data-level="5.2.2" data-path="NUMDATA.html"><a href="NUMDATA.html#dot-plots-and-the-mean"><i class="fa fa-check"></i><b>5.2.2</b> Dot plots and the mean</a></li>
<li class="chapter" data-level="5.2.3" data-path="NUMDATA.html"><a href="NUMDATA.html#histograms-and-shape"><i class="fa fa-check"></i><b>5.2.3</b> Histograms and shape</a></li>
<li class="chapter" data-level="5.2.4" data-path="NUMDATA.html"><a href="NUMDATA.html#variance-and-standard-deviation"><i class="fa fa-check"></i><b>5.2.4</b> Variance and standard deviation</a></li>
<li class="chapter" data-level="5.2.5" data-path="NUMDATA.html"><a href="NUMDATA.html#box-plots-quartiles-and-the-median"><i class="fa fa-check"></i><b>5.2.5</b> Box plots, quartiles, and the median</a></li>
<li class="chapter" data-level="5.2.6" data-path="NUMDATA.html"><a href="NUMDATA.html#robust-statistics"><i class="fa fa-check"></i><b>5.2.6</b> Robust statistics</a></li>
<li class="chapter" data-level="5.2.7" data-path="NUMDATA.html"><a href="NUMDATA.html#transforming-data"><i class="fa fa-check"></i><b>5.2.7</b> Transforming data</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="NUMDATA.html"><a href="NUMDATA.html#homework-problems-4"><i class="fa fa-check"></i><b>5.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="CATDATA.html"><a href="CATDATA.html"><i class="fa fa-check"></i><b>6</b> Categorical Data</a>
<ul>
<li class="chapter" data-level="6.1" data-path="CATDATA.html"><a href="CATDATA.html#objectives-5"><i class="fa fa-check"></i><b>6.1</b> Objectives</a></li>
<li class="chapter" data-level="6.2" data-path="CATDATA.html"><a href="CATDATA.html#categorical-data"><i class="fa fa-check"></i><b>6.2</b> Categorical data</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="CATDATA.html"><a href="CATDATA.html#contingency-tables-and-bar-plots"><i class="fa fa-check"></i><b>6.2.1</b> Contingency tables and bar plots</a></li>
<li class="chapter" data-level="6.2.2" data-path="CATDATA.html"><a href="CATDATA.html#column-proportions"><i class="fa fa-check"></i><b>6.2.2</b> Column proportions</a></li>
<li class="chapter" data-level="6.2.3" data-path="CATDATA.html"><a href="CATDATA.html#segmented-bar-and-mosaic-plots"><i class="fa fa-check"></i><b>6.2.3</b> Segmented bar and mosaic plots</a></li>
<li class="chapter" data-level="6.2.4" data-path="CATDATA.html"><a href="CATDATA.html#the-only-pie-chart-you-will-see-in-this-course-hopefully"><i class="fa fa-check"></i><b>6.2.4</b> The only pie chart you will see in this course, hopefully</a></li>
<li class="chapter" data-level="6.2.5" data-path="CATDATA.html"><a href="CATDATA.html#comparing-numerical-data-across-groups"><i class="fa fa-check"></i><b>6.2.5</b> Comparing numerical data across groups</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="CATDATA.html"><a href="CATDATA.html#homework-problems-5"><i class="fa fa-check"></i><b>6.3</b> Homework Problems</a></li>
</ul></li>
<li class="part"><span><b>II Probability Modeling</b></span></li>
<li class="chapter" data-level="7" data-path="CS2.html"><a href="CS2.html"><i class="fa fa-check"></i><b>7</b> Case Study</a>
<ul>
<li class="chapter" data-level="7.1" data-path="CS2.html"><a href="CS2.html#objectives-6"><i class="fa fa-check"></i><b>7.1</b> Objectives</a></li>
<li class="chapter" data-level="7.2" data-path="CS2.html"><a href="CS2.html#introduction-to-probability-models"><i class="fa fa-check"></i><b>7.2</b> Introduction to probability models</a></li>
<li class="chapter" data-level="7.3" data-path="CS2.html"><a href="CS2.html#probability-models"><i class="fa fa-check"></i><b>7.3</b> Probability models</a></li>
<li class="chapter" data-level="7.4" data-path="CS2.html"><a href="CS2.html#case-study-1"><i class="fa fa-check"></i><b>7.4</b> Case study</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="CS2.html"><a href="CS2.html#break-down-the-question"><i class="fa fa-check"></i><b>7.4.1</b> Break down the question</a></li>
<li class="chapter" data-level="7.4.2" data-path="CS2.html"><a href="CS2.html#simulate-computational"><i class="fa fa-check"></i><b>7.4.2</b> Simulate (computational)</a></li>
<li class="chapter" data-level="7.4.3" data-path="CS2.html"><a href="CS2.html#plotting"><i class="fa fa-check"></i><b>7.4.3</b> Plotting</a></li>
<li class="chapter" data-level="7.4.4" data-path="CS2.html"><a href="CS2.html#mathematical-solution"><i class="fa fa-check"></i><b>7.4.4</b> Mathematical solution</a></li>
<li class="chapter" data-level="7.4.5" data-path="CS2.html"><a href="CS2.html#general-solution"><i class="fa fa-check"></i><b>7.4.5</b> General solution</a></li>
<li class="chapter" data-level="7.4.6" data-path="CS2.html"><a href="CS2.html#data-science-approach"><i class="fa fa-check"></i><b>7.4.6</b> Data science approach</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="CS2.html"><a href="CS2.html#homework-problems-6"><i class="fa fa-check"></i><b>7.5</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="PROBRULES.html"><a href="PROBRULES.html"><i class="fa fa-check"></i><b>8</b> Probability Rules</a>
<ul>
<li class="chapter" data-level="8.1" data-path="PROBRULES.html"><a href="PROBRULES.html#objectives-7"><i class="fa fa-check"></i><b>8.1</b> Objectives</a></li>
<li class="chapter" data-level="8.2" data-path="PROBRULES.html"><a href="PROBRULES.html#probability-vs-statistics"><i class="fa fa-check"></i><b>8.2</b> Probability vs Statistics</a></li>
<li class="chapter" data-level="8.3" data-path="PROBRULES.html"><a href="PROBRULES.html#basic-probability-terms"><i class="fa fa-check"></i><b>8.3</b> Basic probability terms</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="PROBRULES.html"><a href="PROBRULES.html#sample-space"><i class="fa fa-check"></i><b>8.3.1</b> Sample space</a></li>
<li class="chapter" data-level="8.3.2" data-path="PROBRULES.html"><a href="PROBRULES.html#union-and-intersection"><i class="fa fa-check"></i><b>8.3.2</b> Union and intersection</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="PROBRULES.html"><a href="PROBRULES.html#probability"><i class="fa fa-check"></i><b>8.4</b> Probability</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="PROBRULES.html"><a href="PROBRULES.html#probability-properties"><i class="fa fa-check"></i><b>8.4.1</b> Probability properties</a></li>
<li class="chapter" data-level="8.4.2" data-path="PROBRULES.html"><a href="PROBRULES.html#equally-likely-scenarios"><i class="fa fa-check"></i><b>8.4.2</b> Equally likely scenarios</a></li>
<li class="chapter" data-level="8.4.3" data-path="PROBRULES.html"><a href="PROBRULES.html#using-r-equally-likely-scenarios"><i class="fa fa-check"></i><b>8.4.3</b> Using <code>R</code> (Equally likely scenarios)</a></li>
<li class="chapter" data-level="8.4.4" data-path="PROBRULES.html"><a href="PROBRULES.html#note"><i class="fa fa-check"></i><b>8.4.4</b> Note</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="PROBRULES.html"><a href="PROBRULES.html#counting-rules"><i class="fa fa-check"></i><b>8.5</b> Counting rules</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="PROBRULES.html"><a href="PROBRULES.html#multiplication-rule-1-order-matters-sample-with-replacement"><i class="fa fa-check"></i><b>8.5.1</b> Multiplication rule 1: Order matters, sample with replacement</a></li>
<li class="chapter" data-level="8.5.2" data-path="PROBRULES.html"><a href="PROBRULES.html#multiplication-rule-2-permutation-order-matters-sampling-without-replacement"><i class="fa fa-check"></i><b>8.5.2</b> Multiplication rule 2 (Permutation): Order Matters, Sampling Without Replacement</a></li>
<li class="chapter" data-level="8.5.3" data-path="PROBRULES.html"><a href="PROBRULES.html#multiplication-rule-3-combination-order-does-not-matter-sampling-without-replacement"><i class="fa fa-check"></i><b>8.5.3</b> Multiplication rule 3 (Combination): Order Does Not Matter, Sampling Without Replacement</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="PROBRULES.html"><a href="PROBRULES.html#homework-problems-7"><i class="fa fa-check"></i><b>8.6</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="CONDPROB.html"><a href="CONDPROB.html"><i class="fa fa-check"></i><b>9</b> Conditional Probability</a>
<ul>
<li class="chapter" data-level="9.1" data-path="CONDPROB.html"><a href="CONDPROB.html#objectives-8"><i class="fa fa-check"></i><b>9.1</b> Objectives</a></li>
<li class="chapter" data-level="9.2" data-path="CONDPROB.html"><a href="CONDPROB.html#conditional-probability"><i class="fa fa-check"></i><b>9.2</b> Conditional Probability</a></li>
<li class="chapter" data-level="9.3" data-path="CONDPROB.html"><a href="CONDPROB.html#independence"><i class="fa fa-check"></i><b>9.3</b> Independence</a></li>
<li class="chapter" data-level="9.4" data-path="CONDPROB.html"><a href="CONDPROB.html#bayes-rule"><i class="fa fa-check"></i><b>9.4</b> Bayes’ Rule</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="CONDPROB.html"><a href="CONDPROB.html#approach-using-whole-numbers"><i class="fa fa-check"></i><b>9.4.1</b> Approach using whole numbers</a></li>
<li class="chapter" data-level="9.4.2" data-path="CONDPROB.html"><a href="CONDPROB.html#mathematical-approach"><i class="fa fa-check"></i><b>9.4.2</b> Mathematical approach</a></li>
<li class="chapter" data-level="9.4.3" data-path="CONDPROB.html"><a href="CONDPROB.html#simulation"><i class="fa fa-check"></i><b>9.4.3</b> Simulation</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="CONDPROB.html"><a href="CONDPROB.html#homework-problems-8"><i class="fa fa-check"></i><b>9.5</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="RANDVAR.html"><a href="RANDVAR.html"><i class="fa fa-check"></i><b>10</b> Random Variables</a>
<ul>
<li class="chapter" data-level="10.1" data-path="RANDVAR.html"><a href="RANDVAR.html#objectives-9"><i class="fa fa-check"></i><b>10.1</b> Objectives</a></li>
<li class="chapter" data-level="10.2" data-path="RANDVAR.html"><a href="RANDVAR.html#random-variables"><i class="fa fa-check"></i><b>10.2</b> Random variables</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="RANDVAR.html"><a href="RANDVAR.html#how-does-this-help"><i class="fa fa-check"></i><b>10.2.1</b> How does this help?</a></li>
<li class="chapter" data-level="10.2.2" data-path="RANDVAR.html"><a href="RANDVAR.html#discrete-vs-continuous"><i class="fa fa-check"></i><b>10.2.2</b> Discrete vs Continuous</a></li>
<li class="chapter" data-level="10.2.3" data-path="RANDVAR.html"><a href="RANDVAR.html#discrete-distribution-functions"><i class="fa fa-check"></i><b>10.2.3</b> Discrete distribution functions</a></li>
<li class="chapter" data-level="10.2.4" data-path="RANDVAR.html"><a href="RANDVAR.html#probability-mass-function"><i class="fa fa-check"></i><b>10.2.4</b> Probability mass function</a></li>
<li class="chapter" data-level="10.2.5" data-path="RANDVAR.html"><a href="RANDVAR.html#cumulative-distribution-function"><i class="fa fa-check"></i><b>10.2.5</b> Cumulative distribution function</a></li>
<li class="chapter" data-level="10.2.6" data-path="RANDVAR.html"><a href="RANDVAR.html#simulating-random-variables"><i class="fa fa-check"></i><b>10.2.6</b> Simulating random variables</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="RANDVAR.html"><a href="RANDVAR.html#moments"><i class="fa fa-check"></i><b>10.3</b> Moments</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="RANDVAR.html"><a href="RANDVAR.html#expectation"><i class="fa fa-check"></i><b>10.3.1</b> Expectation</a></li>
<li class="chapter" data-level="10.3.2" data-path="RANDVAR.html"><a href="RANDVAR.html#mean"><i class="fa fa-check"></i><b>10.3.2</b> Mean</a></li>
<li class="chapter" data-level="10.3.3" data-path="RANDVAR.html"><a href="RANDVAR.html#variance"><i class="fa fa-check"></i><b>10.3.3</b> Variance</a></li>
<li class="chapter" data-level="10.3.4" data-path="RANDVAR.html"><a href="RANDVAR.html#mean-and-variance-of-linear-transformations"><i class="fa fa-check"></i><b>10.3.4</b> Mean and variance of Linear Transformations</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="RANDVAR.html"><a href="RANDVAR.html#homework-problems-9"><i class="fa fa-check"></i><b>10.4</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html"><i class="fa fa-check"></i><b>11</b> Continuous Random Variables</a>
<ul>
<li class="chapter" data-level="11.1" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#objectives-10"><i class="fa fa-check"></i><b>11.1</b> Objectives</a></li>
<li class="chapter" data-level="11.2" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#continuous-random-variables"><i class="fa fa-check"></i><b>11.2</b> Continuous random variables</a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#continuous-distribution-functions"><i class="fa fa-check"></i><b>11.2.1</b> Continuous distribution functions</a></li>
<li class="chapter" data-level="11.2.2" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#probability-density-function"><i class="fa fa-check"></i><b>11.2.2</b> Probability density function</a></li>
<li class="chapter" data-level="11.2.3" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#cumulative-distribution-function-1"><i class="fa fa-check"></i><b>11.2.3</b> Cumulative distribution function</a></li>
<li class="chapter" data-level="11.2.4" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#simulation-1"><i class="fa fa-check"></i><b>11.2.4</b> Simulation</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#moments-1"><i class="fa fa-check"></i><b>11.3</b> Moments</a>
<ul>
<li class="chapter" data-level="11.3.1" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#mean-and-variance"><i class="fa fa-check"></i><b>11.3.1</b> Mean and variance</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#homework-problems-10"><i class="fa fa-check"></i><b>11.4</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html"><i class="fa fa-check"></i><b>12</b> Named Discrete Distributions</a>
<ul>
<li class="chapter" data-level="12.1" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#objectives-11"><i class="fa fa-check"></i><b>12.1</b> Objectives</a></li>
<li class="chapter" data-level="12.2" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#named-distributions"><i class="fa fa-check"></i><b>12.2</b> Named distributions</a>
<ul>
<li class="chapter" data-level="12.2.1" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#discrete-uniform-distribution"><i class="fa fa-check"></i><b>12.2.1</b> Discrete uniform distribution</a></li>
<li class="chapter" data-level="12.2.2" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#simulating"><i class="fa fa-check"></i><b>12.2.2</b> Simulating</a></li>
<li class="chapter" data-level="12.2.3" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#binomial-distribution"><i class="fa fa-check"></i><b>12.2.3</b> Binomial distribution</a></li>
<li class="chapter" data-level="12.2.4" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#software-functions"><i class="fa fa-check"></i><b>12.2.4</b> Software Functions</a></li>
<li class="chapter" data-level="12.2.5" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#poisson-distribution"><i class="fa fa-check"></i><b>12.2.5</b> Poisson distribution</a></li>
<li class="chapter" data-level="12.2.6" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#hypergeometric"><i class="fa fa-check"></i><b>12.2.6</b> Hypergeometric</a></li>
</ul></li>
<li class="chapter" data-level="12.3" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#homework-problems-11"><i class="fa fa-check"></i><b>12.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html"><i class="fa fa-check"></i><b>13</b> Named Continuous Distributions</a>
<ul>
<li class="chapter" data-level="13.1" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#objectives-12"><i class="fa fa-check"></i><b>13.1</b> Objectives</a></li>
<li class="chapter" data-level="13.2" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#continuous-distributions"><i class="fa fa-check"></i><b>13.2</b> Continuous distributions</a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#uniform-distribution"><i class="fa fa-check"></i><b>13.2.1</b> Uniform distribution</a></li>
<li class="chapter" data-level="13.2.2" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#exponential-distribution"><i class="fa fa-check"></i><b>13.2.2</b> Exponential distribution</a></li>
<li class="chapter" data-level="13.2.3" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#memoryless-property"><i class="fa fa-check"></i><b>13.2.3</b> Memoryless property</a></li>
<li class="chapter" data-level="13.2.4" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#gamma-distribution"><i class="fa fa-check"></i><b>13.2.4</b> Gamma distribution</a></li>
<li class="chapter" data-level="13.2.5" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#weibull-distribution"><i class="fa fa-check"></i><b>13.2.5</b> Weibull distribution</a></li>
<li class="chapter" data-level="13.2.6" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#normal-distribution"><i class="fa fa-check"></i><b>13.2.6</b> Normal distribution</a></li>
<li class="chapter" data-level="13.2.7" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#beta-distribution"><i class="fa fa-check"></i><b>13.2.7</b> Beta distribution</a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#homework-problems-12"><i class="fa fa-check"></i><b>13.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html"><i class="fa fa-check"></i><b>14</b> Multivariate Distributions</a>
<ul>
<li class="chapter" data-level="14.1" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#objectives-13"><i class="fa fa-check"></i><b>14.1</b> Objectives</a></li>
<li class="chapter" data-level="14.2" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#multivariate-distributions"><i class="fa fa-check"></i><b>14.2</b> Multivariate distributions</a></li>
<li class="chapter" data-level="14.3" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#joint-probability"><i class="fa fa-check"></i><b>14.3</b> Joint probability</a>
<ul>
<li class="chapter" data-level="14.3.1" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#discrete-random-variables"><i class="fa fa-check"></i><b>14.3.1</b> Discrete random variables</a></li>
<li class="chapter" data-level="14.3.2" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#continuous-random-variables-1"><i class="fa fa-check"></i><b>14.3.2</b> Continuous random variables</a></li>
</ul></li>
<li class="chapter" data-level="14.4" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#homework-problems-13"><i class="fa fa-check"></i><b>14.4</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="MULTIEXP.html"><a href="MULTIEXP.html"><i class="fa fa-check"></i><b>15</b> Multivariate Expectation</a>
<ul>
<li class="chapter" data-level="15.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#objectives-14"><i class="fa fa-check"></i><b>15.1</b> Objectives</a></li>
<li class="chapter" data-level="15.2" data-path="MULTIEXP.html"><a href="MULTIEXP.html#expectation---moments"><i class="fa fa-check"></i><b>15.2</b> Expectation - moments</a>
<ul>
<li class="chapter" data-level="15.2.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#expectation-of-discrete-random-variables"><i class="fa fa-check"></i><b>15.2.1</b> Expectation of discrete random variables</a></li>
</ul></li>
<li class="chapter" data-level="15.3" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exercises-to-apply-what-we-learned"><i class="fa fa-check"></i><b>15.3</b> Exercises to apply what we learned</a>
<ul>
<li class="chapter" data-level="15.3.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#ey"><i class="fa fa-check"></i><b>15.3.1</b> E(Y)</a></li>
<li class="chapter" data-level="15.3.2" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy"><i class="fa fa-check"></i><b>15.3.2</b> E(X+Y)</a></li>
<li class="chapter" data-level="15.3.3" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy-1"><i class="fa fa-check"></i><b>15.3.3</b> E(XY)</a></li>
<li class="chapter" data-level="15.3.4" data-path="MULTIEXP.html"><a href="MULTIEXP.html#e12xy1"><i class="fa fa-check"></i><b>15.3.4</b> E(1/2X+Y+1)</a></li>
<li class="chapter" data-level="15.3.5" data-path="MULTIEXP.html"><a href="MULTIEXP.html#expectation-of-continuous-random-variables"><i class="fa fa-check"></i><b>15.3.5</b> Expectation of continuous random variables</a></li>
</ul></li>
<li class="chapter" data-level="15.4" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exercises-to-apply-what-we-learned-1"><i class="fa fa-check"></i><b>15.4</b> Exercises to apply what we learned</a>
<ul>
<li class="chapter" data-level="15.4.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#ex"><i class="fa fa-check"></i><b>15.4.1</b> E(X)</a></li>
<li class="chapter" data-level="15.4.2" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy-2"><i class="fa fa-check"></i><b>15.4.2</b> E(X+Y)</a></li>
<li class="chapter" data-level="15.4.3" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy-3"><i class="fa fa-check"></i><b>15.4.3</b> E(XY)</a></li>
<li class="chapter" data-level="15.4.4" data-path="MULTIEXP.html"><a href="MULTIEXP.html#vxy"><i class="fa fa-check"></i><b>15.4.4</b> V(XY)</a></li>
</ul></li>
<li class="chapter" data-level="15.5" data-path="MULTIEXP.html"><a href="MULTIEXP.html#covariancecorrelation"><i class="fa fa-check"></i><b>15.5</b> Covariance/Correlation</a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#variance-of-sums"><i class="fa fa-check"></i><b>15.5.1</b> Variance of sums</a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="MULTIEXP.html"><a href="MULTIEXP.html#independence-1"><i class="fa fa-check"></i><b>15.6</b> Independence</a></li>
<li class="chapter" data-level="15.7" data-path="MULTIEXP.html"><a href="MULTIEXP.html#conditional-expectation"><i class="fa fa-check"></i><b>15.7</b> Conditional expectation</a></li>
<li class="chapter" data-level="15.8" data-path="MULTIEXP.html"><a href="MULTIEXP.html#homework-problems-14"><i class="fa fa-check"></i><b>15.8</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="TRANS.html"><a href="TRANS.html"><i class="fa fa-check"></i><b>16</b> Transformations</a>
<ul>
<li class="chapter" data-level="16.1" data-path="TRANS.html"><a href="TRANS.html#objectives-15"><i class="fa fa-check"></i><b>16.1</b> Objectives</a></li>
<li class="chapter" data-level="16.2" data-path="TRANS.html"><a href="TRANS.html#transformations"><i class="fa fa-check"></i><b>16.2</b> Transformations</a>
<ul>
<li class="chapter" data-level="16.2.1" data-path="TRANS.html"><a href="TRANS.html#transformations-of-discrete-random-variables"><i class="fa fa-check"></i><b>16.2.1</b> Transformations of discrete random variables</a></li>
<li class="chapter" data-level="16.2.2" data-path="TRANS.html"><a href="TRANS.html#transformations-of-continuous-random-variables"><i class="fa fa-check"></i><b>16.2.2</b> Transformations of continuous random variables</a></li>
<li class="chapter" data-level="16.2.3" data-path="TRANS.html"><a href="TRANS.html#the-cdf-method"><i class="fa fa-check"></i><b>16.2.3</b> The cdf method</a></li>
<li class="chapter" data-level="16.2.4" data-path="TRANS.html"><a href="TRANS.html#the-pdf-method"><i class="fa fa-check"></i><b>16.2.4</b> The pdf method</a></li>
<li class="chapter" data-level="16.2.5" data-path="TRANS.html"><a href="TRANS.html#simulation-2"><i class="fa fa-check"></i><b>16.2.5</b> Simulation</a></li>
<li class="chapter" data-level="16.2.6" data-path="TRANS.html"><a href="TRANS.html#multivariate-transformations"><i class="fa fa-check"></i><b>16.2.6</b> Multivariate Transformations</a></li>
</ul></li>
<li class="chapter" data-level="16.3" data-path="TRANS.html"><a href="TRANS.html#homework-problems-15"><i class="fa fa-check"></i><b>16.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="EST.html"><a href="EST.html"><i class="fa fa-check"></i><b>17</b> Estimation Methods</a>
<ul>
<li class="chapter" data-level="17.1" data-path="EST.html"><a href="EST.html#objectives-16"><i class="fa fa-check"></i><b>17.1</b> Objectives</a></li>
<li class="chapter" data-level="17.2" data-path="EST.html"><a href="EST.html#transition"><i class="fa fa-check"></i><b>17.2</b> Transition</a></li>
<li class="chapter" data-level="17.3" data-path="EST.html"><a href="EST.html#estimation"><i class="fa fa-check"></i><b>17.3</b> Estimation</a></li>
<li class="chapter" data-level="17.4" data-path="EST.html"><a href="EST.html#method-of-moments"><i class="fa fa-check"></i><b>17.4</b> Method of Moments</a></li>
<li class="chapter" data-level="17.5" data-path="EST.html"><a href="EST.html#maximum-likelihood"><i class="fa fa-check"></i><b>17.5</b> Maximum likelihood</a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="EST.html"><a href="EST.html#likelihood-function"><i class="fa fa-check"></i><b>17.5.1</b> Likelihood Function</a></li>
<li class="chapter" data-level="17.5.2" data-path="EST.html"><a href="EST.html#maximum-likelihood-estimation"><i class="fa fa-check"></i><b>17.5.2</b> Maximum Likelihood Estimation</a></li>
<li class="chapter" data-level="17.5.3" data-path="EST.html"><a href="EST.html#numerical-methods"><i class="fa fa-check"></i><b>17.5.3</b> Numerical Methods</a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="EST.html"><a href="EST.html#homework-problems-16"><i class="fa fa-check"></i><b>17.6</b> Homework Problems</a></li>
</ul></li>
<li class="part"><span><b>III Statistical Modeling</b></span></li>
<li class="chapter" data-level="18" data-path="CS3.html"><a href="CS3.html"><i class="fa fa-check"></i><b>18</b> Case Study</a>
<ul>
<li class="chapter" data-level="18.1" data-path="CS3.html"><a href="CS3.html#objectives-17"><i class="fa fa-check"></i><b>18.1</b> Objectives</a></li>
<li class="chapter" data-level="18.2" data-path="CS3.html"><a href="CS3.html#introduction"><i class="fa fa-check"></i><b>18.2</b> Introduction</a></li>
<li class="chapter" data-level="18.3" data-path="CS3.html"><a href="CS3.html#foundation-for-inference"><i class="fa fa-check"></i><b>18.3</b> Foundation for inference</a></li>
<li class="chapter" data-level="18.4" data-path="CS3.html"><a href="CS3.html#randomization-case-study-gender-discrimination"><i class="fa fa-check"></i><b>18.4</b> Randomization case study: gender discrimination</a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="CS3.html"><a href="CS3.html#variability-within-data"><i class="fa fa-check"></i><b>18.4.1</b> Variability within data</a></li>
<li class="chapter" data-level="18.4.2" data-path="CS3.html"><a href="CS3.html#simulating-the-study"><i class="fa fa-check"></i><b>18.4.2</b> Simulating the study</a></li>
<li class="chapter" data-level="18.4.3" data-path="CS3.html"><a href="CS3.html#checking-for-independence"><i class="fa fa-check"></i><b>18.4.3</b> Checking for independence</a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="CS3.html"><a href="CS3.html#homework-problems-17"><i class="fa fa-check"></i><b>18.5</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="HYPOTEST.html"><a href="HYPOTEST.html"><i class="fa fa-check"></i><b>19</b> Hypothesis Testing</a>
<ul>
<li class="chapter" data-level="19.1" data-path="HYPOTEST.html"><a href="HYPOTEST.html#objectives-18"><i class="fa fa-check"></i><b>19.1</b> Objectives</a></li>
<li class="chapter" data-level="19.2" data-path="HYPOTEST.html"><a href="HYPOTEST.html#decision-making-under-uncertainty"><i class="fa fa-check"></i><b>19.2</b> Decision making under uncertainty</a></li>
<li class="chapter" data-level="19.3" data-path="HYPOTEST.html"><a href="HYPOTEST.html#introduction-1"><i class="fa fa-check"></i><b>19.3</b> Introduction</a></li>
<li class="chapter" data-level="19.4" data-path="HYPOTEST.html"><a href="HYPOTEST.html#hypothesis-testing"><i class="fa fa-check"></i><b>19.4</b> Hypothesis testing</a>
<ul>
<li class="chapter" data-level="19.4.1" data-path="HYPOTEST.html"><a href="HYPOTEST.html#hypothesis-testing-in-the-us-court-system"><i class="fa fa-check"></i><b>19.4.1</b> Hypothesis testing in the US court system</a></li>
<li class="chapter" data-level="19.4.2" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-1--state-the-null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>19.4.2</b> Step 1- State the null and alternative hypotheses</a></li>
<li class="chapter" data-level="19.4.3" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-2---compute-a-test-statistic."><i class="fa fa-check"></i><b>19.4.3</b> Step 2 - Compute a test statistic.</a></li>
<li class="chapter" data-level="19.4.4" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-3---determine-the-p-value."><i class="fa fa-check"></i><b>19.4.4</b> Step 3 - Determine the p-value.</a></li>
<li class="chapter" data-level="19.4.5" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-4---draw-a-conclusion"><i class="fa fa-check"></i><b>19.4.5</b> Step 4 - Draw a conclusion</a></li>
<li class="chapter" data-level="19.4.6" data-path="HYPOTEST.html"><a href="HYPOTEST.html#decision-errors"><i class="fa fa-check"></i><b>19.4.6</b> Decision errors</a></li>
<li class="chapter" data-level="19.4.7" data-path="HYPOTEST.html"><a href="HYPOTEST.html#choosing-a-significance-level"><i class="fa fa-check"></i><b>19.4.7</b> Choosing a significance level</a></li>
<li class="chapter" data-level="19.4.8" data-path="HYPOTEST.html"><a href="HYPOTEST.html#introducing-two-sided-hypotheses"><i class="fa fa-check"></i><b>19.4.8</b> Introducing two-sided hypotheses</a></li>
</ul></li>
<li class="chapter" data-level="19.5" data-path="HYPOTEST.html"><a href="HYPOTEST.html#two-sided-hypothesis-test"><i class="fa fa-check"></i><b>19.5</b> Two-sided hypothesis test</a>
<ul>
<li class="chapter" data-level="19.5.1" data-path="HYPOTEST.html"><a href="HYPOTEST.html#example-cpr"><i class="fa fa-check"></i><b>19.5.1</b> Example CPR</a></li>
<li class="chapter" data-level="19.5.2" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-1--state-the-null-and-alternative-hypotheses-1"><i class="fa fa-check"></i><b>19.5.2</b> Step 1- State the null and alternative hypotheses</a></li>
<li class="chapter" data-level="19.5.3" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-2---compute-a-test-statistic.-1"><i class="fa fa-check"></i><b>19.5.3</b> Step 2 - Compute a test statistic.</a></li>
<li class="chapter" data-level="19.5.4" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-3---determine-the-p-value.-1"><i class="fa fa-check"></i><b>19.5.4</b> Step 3 - Determine the p-value.</a></li>
<li class="chapter" data-level="19.5.5" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-4---draw-a-conclusion-1"><i class="fa fa-check"></i><b>19.5.5</b> Step 4 - Draw a conclusion</a></li>
<li class="chapter" data-level="19.5.6" data-path="HYPOTEST.html"><a href="HYPOTEST.html#how-to-use-a-hypothesis-test"><i class="fa fa-check"></i><b>19.5.6</b> How to use a hypothesis test</a></li>
</ul></li>
<li class="chapter" data-level="19.6" data-path="HYPOTEST.html"><a href="HYPOTEST.html#homework-problems-18"><i class="fa fa-check"></i><b>19.6</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="PVALUES.html"><a href="PVALUES.html"><i class="fa fa-check"></i><b>20</b> Empirical p-values</a>
<ul>
<li class="chapter" data-level="20.1" data-path="PVALUES.html"><a href="PVALUES.html#objective"><i class="fa fa-check"></i><b>20.1</b> Objective</a></li>
<li class="chapter" data-level="20.2" data-path="PVALUES.html"><a href="PVALUES.html#hypothesis-testing-using-probability-models"><i class="fa fa-check"></i><b>20.2</b> Hypothesis testing using probability models</a></li>
<li class="chapter" data-level="20.3" data-path="PVALUES.html"><a href="PVALUES.html#tappers-and-listeners"><i class="fa fa-check"></i><b>20.3</b> Tappers and listeners</a>
<ul>
<li class="chapter" data-level="20.3.1" data-path="PVALUES.html"><a href="PVALUES.html#step-1--state-the-null-and-alternative-hypotheses-2"><i class="fa fa-check"></i><b>20.3.1</b> Step 1- State the null and alternative hypotheses</a></li>
<li class="chapter" data-level="20.3.2" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-2"><i class="fa fa-check"></i><b>20.3.2</b> Step 2 - Compute a test statistic.</a></li>
<li class="chapter" data-level="20.3.3" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-2"><i class="fa fa-check"></i><b>20.3.3</b> Step 3 - Determine the p-value.</a></li>
<li class="chapter" data-level="20.3.4" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-2"><i class="fa fa-check"></i><b>20.3.4</b> Step 4 - Draw a conclusion</a></li>
<li class="chapter" data-level="20.3.5" data-path="PVALUES.html"><a href="PVALUES.html#repeat-using-simulation"><i class="fa fa-check"></i><b>20.3.5</b> Repeat using simulation</a></li>
<li class="chapter" data-level="20.3.6" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-3"><i class="fa fa-check"></i><b>20.3.6</b> Step 2 - Compute a test statistic.</a></li>
<li class="chapter" data-level="20.3.7" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-3"><i class="fa fa-check"></i><b>20.3.7</b> Step 3 - Determine the p-value.</a></li>
<li class="chapter" data-level="20.3.8" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-3"><i class="fa fa-check"></i><b>20.3.8</b> Step 4 - Draw a conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20.4" data-path="PVALUES.html"><a href="PVALUES.html#cardiopulmonary-resuscitation-cpr"><i class="fa fa-check"></i><b>20.4</b> Cardiopulmonary resuscitation (CPR)</a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="PVALUES.html"><a href="PVALUES.html#step-1--state-the-null-and-alternative-hypotheses-3"><i class="fa fa-check"></i><b>20.4.1</b> Step 1- State the null and alternative hypotheses</a></li>
<li class="chapter" data-level="20.4.2" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-4"><i class="fa fa-check"></i><b>20.4.2</b> Step 2 - Compute a test statistic.</a></li>
<li class="chapter" data-level="20.4.3" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-4"><i class="fa fa-check"></i><b>20.4.3</b> Step 3 - Determine the p-value.</a></li>
<li class="chapter" data-level="20.4.4" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-4"><i class="fa fa-check"></i><b>20.4.4</b> Step 4 - Draw a conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="PVALUES.html"><a href="PVALUES.html#golf-balls"><i class="fa fa-check"></i><b>20.5</b> Golf Balls</a>
<ul>
<li class="chapter" data-level="20.5.1" data-path="PVALUES.html"><a href="PVALUES.html#step-1--state-the-null-and-alternative-hypotheses-4"><i class="fa fa-check"></i><b>20.5.1</b> Step 1- State the null and alternative hypotheses</a></li>
<li class="chapter" data-level="20.5.2" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-5"><i class="fa fa-check"></i><b>20.5.2</b> Step 2 - Compute a test statistic.</a></li>
<li class="chapter" data-level="20.5.3" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-5"><i class="fa fa-check"></i><b>20.5.3</b> Step 3 - Determine the p-value.</a></li>
<li class="chapter" data-level="20.5.4" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-5"><i class="fa fa-check"></i><b>20.5.4</b> Step 4 - Draw a conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="PVALUES.html"><a href="PVALUES.html#repeat-with-a-different-test-statistic"><i class="fa fa-check"></i><b>20.6</b> Repeat with a different test statistic</a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-6"><i class="fa fa-check"></i><b>20.6.1</b> Step 2 - Compute a test statistic.</a></li>
<li class="chapter" data-level="20.6.2" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-6"><i class="fa fa-check"></i><b>20.6.2</b> Step 3 - Determine the p-value.</a></li>
<li class="chapter" data-level="20.6.3" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-6"><i class="fa fa-check"></i><b>20.6.3</b> Step 4 - Draw a conclusion</a></li>
</ul></li>
<li class="chapter" data-level="20.7" data-path="PVALUES.html"><a href="PVALUES.html#summary"><i class="fa fa-check"></i><b>20.7</b> Summary</a></li>
<li class="chapter" data-level="20.8" data-path="PVALUES.html"><a href="PVALUES.html#homework-problems-19"><i class="fa fa-check"></i><b>20.8</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="CLT.html"><a href="CLT.html"><i class="fa fa-check"></i><b>21</b> Central Limit Theorem</a>
<ul>
<li class="chapter" data-level="21.1" data-path="CLT.html"><a href="CLT.html#objectives-19"><i class="fa fa-check"></i><b>21.1</b> Objectives</a></li>
<li class="chapter" data-level="21.2" data-path="CLT.html"><a href="CLT.html#central-limit-theorem"><i class="fa fa-check"></i><b>21.2</b> Central limit theorem</a>
<ul>
<li class="chapter" data-level="21.2.1" data-path="CLT.html"><a href="CLT.html#null-distribution"><i class="fa fa-check"></i><b>21.2.1</b> Null distribution</a></li>
<li class="chapter" data-level="21.2.2" data-path="CLT.html"><a href="CLT.html#theorem---central-limit-theorem"><i class="fa fa-check"></i><b>21.2.2</b> Theorem - central limit theorem</a></li>
<li class="chapter" data-level="21.2.3" data-path="CLT.html"><a href="CLT.html#simulating-data-for-clt"><i class="fa fa-check"></i><b>21.2.3</b> Simulating data for CLT</a></li>
<li class="chapter" data-level="21.2.4" data-path="CLT.html"><a href="CLT.html#summary-of-example"><i class="fa fa-check"></i><b>21.2.4</b> Summary of example</a></li>
</ul></li>
<li class="chapter" data-level="21.3" data-path="CLT.html"><a href="CLT.html#other-distribution-for-estimators"><i class="fa fa-check"></i><b>21.3</b> Other distribution for estimators</a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="CLT.html"><a href="CLT.html#chi-sqaured"><i class="fa fa-check"></i><b>21.3.1</b> Chi-sqaured</a></li>
<li class="chapter" data-level="21.3.2" data-path="CLT.html"><a href="CLT.html#students-t"><i class="fa fa-check"></i><b>21.3.2</b> Student’s t</a></li>
<li class="chapter" data-level="21.3.3" data-path="CLT.html"><a href="CLT.html#important-note"><i class="fa fa-check"></i><b>21.3.3</b> Important Note</a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="CLT.html"><a href="CLT.html#hypotheses-tests-using-clt"><i class="fa fa-check"></i><b>21.4</b> Hypotheses tests using CLT</a>
<ul>
<li class="chapter" data-level="21.4.1" data-path="CLT.html"><a href="CLT.html#tappers-and-listeners-1"><i class="fa fa-check"></i><b>21.4.1</b> Tappers and listeners</a></li>
<li class="chapter" data-level="21.4.2" data-path="CLT.html"><a href="CLT.html#body-temperature"><i class="fa fa-check"></i><b>21.4.2</b> Body temperature</a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="CLT.html"><a href="CLT.html#summary-and-rules-of-thumb"><i class="fa fa-check"></i><b>21.5</b> Summary and rules of thumb</a>
<ul>
<li class="chapter" data-level="21.5.1" data-path="CLT.html"><a href="CLT.html#numerical-data-1"><i class="fa fa-check"></i><b>21.5.1</b> Numerical data</a></li>
<li class="chapter" data-level="21.5.2" data-path="CLT.html"><a href="CLT.html#binary-data"><i class="fa fa-check"></i><b>21.5.2</b> Binary data</a></li>
</ul></li>
<li class="chapter" data-level="21.6" data-path="CLT.html"><a href="CLT.html#homework-problems-20"><i class="fa fa-check"></i><b>21.6</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="CI.html"><a href="CI.html"><i class="fa fa-check"></i><b>22</b> Confidence Intervals</a>
<ul>
<li class="chapter" data-level="22.1" data-path="CI.html"><a href="CI.html#objectives-20"><i class="fa fa-check"></i><b>22.1</b> Objectives</a></li>
<li class="chapter" data-level="22.2" data-path="CI.html"><a href="CI.html#confidence-interval"><i class="fa fa-check"></i><b>22.2</b> Confidence interval</a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="CI.html"><a href="CI.html#capturing-the-population-parameter"><i class="fa fa-check"></i><b>22.2.1</b> Capturing the population parameter</a></li>
<li class="chapter" data-level="22.2.2" data-path="CI.html"><a href="CI.html#constructing-a-confidence-interval"><i class="fa fa-check"></i><b>22.2.2</b> Constructing a confidence interval</a></li>
<li class="chapter" data-level="22.2.3" data-path="CI.html"><a href="CI.html#body-temperature-example"><i class="fa fa-check"></i><b>22.2.3</b> Body Temperature Example</a></li>
<li class="chapter" data-level="22.2.4" data-path="CI.html"><a href="CI.html#one-sided-intervals"><i class="fa fa-check"></i><b>22.2.4</b> One-sided Intervals</a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="CI.html"><a href="CI.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>22.3</b> Confidence intervals for two proportions</a>
<ul>
<li class="chapter" data-level="22.3.1" data-path="CI.html"><a href="CI.html#permutation-test-for-two-proportions"><i class="fa fa-check"></i><b>22.3.1</b> Permutation test for two proportions</a></li>
<li class="chapter" data-level="22.3.2" data-path="CI.html"><a href="CI.html#hypothesis-test-for-two-proportions-using-normal-model"><i class="fa fa-check"></i><b>22.3.2</b> Hypothesis test for two proportions using normal model</a></li>
<li class="chapter" data-level="22.3.3" data-path="CI.html"><a href="CI.html#confidence-interval-for-two-proportions-using-normal-model"><i class="fa fa-check"></i><b>22.3.3</b> Confidence interval for two proportions using normal model</a></li>
</ul></li>
<li class="chapter" data-level="22.4" data-path="CI.html"><a href="CI.html#changing-the-confidence-level"><i class="fa fa-check"></i><b>22.4</b> Changing the confidence level</a></li>
<li class="chapter" data-level="22.5" data-path="CI.html"><a href="CI.html#interpreting-confidence-intervals"><i class="fa fa-check"></i><b>22.5</b> Interpreting confidence intervals</a></li>
<li class="chapter" data-level="22.6" data-path="CI.html"><a href="CI.html#homework-problems-21"><i class="fa fa-check"></i><b>22.6</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="BOOT.html"><a href="BOOT.html"><i class="fa fa-check"></i><b>23</b> Bootstrap</a>
<ul>
<li class="chapter" data-level="23.1" data-path="BOOT.html"><a href="BOOT.html#objectives-21"><i class="fa fa-check"></i><b>23.1</b> Objectives</a></li>
<li class="chapter" data-level="23.2" data-path="BOOT.html"><a href="BOOT.html#confidence-intervals"><i class="fa fa-check"></i><b>23.2</b> Confidence intervals</a></li>
<li class="chapter" data-level="23.3" data-path="BOOT.html"><a href="BOOT.html#bootstrapping"><i class="fa fa-check"></i><b>23.3</b> Bootstrapping</a></li>
<li class="chapter" data-level="23.4" data-path="BOOT.html"><a href="BOOT.html#bootstrap-example"><i class="fa fa-check"></i><b>23.4</b> Bootstrap example</a>
<ul>
<li class="chapter" data-level="23.4.1" data-path="BOOT.html"><a href="BOOT.html#using-traditional-mathematically-methods"><i class="fa fa-check"></i><b>23.4.1</b> Using traditional mathematically methods</a></li>
<li class="chapter" data-level="23.4.2" data-path="BOOT.html"><a href="BOOT.html#bootstrap"><i class="fa fa-check"></i><b>23.4.2</b> Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="23.5" data-path="BOOT.html"><a href="BOOT.html#non-standard-sample-statistics"><i class="fa fa-check"></i><b>23.5</b> Non-standard sample statistics</a>
<ul>
<li class="chapter" data-level="23.5.1" data-path="BOOT.html"><a href="BOOT.html#example-median"><i class="fa fa-check"></i><b>23.5.1</b> Example median</a></li>
<li class="chapter" data-level="23.5.2" data-path="BOOT.html"><a href="BOOT.html#summary-bootstrap"><i class="fa fa-check"></i><b>23.5.2</b> Summary bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="23.6" data-path="BOOT.html"><a href="BOOT.html#confidence-interval-for-difference-in-means"><i class="fa fa-check"></i><b>23.6</b> Confidence interval for difference in means</a>
<ul>
<li class="chapter" data-level="23.6.1" data-path="BOOT.html"><a href="BOOT.html#health-evaluation-and-linkage-of-primary-care"><i class="fa fa-check"></i><b>23.6.1</b> Health evaluation and linkage of primary care</a></li>
<li class="chapter" data-level="23.6.2" data-path="BOOT.html"><a href="BOOT.html#permutation-test"><i class="fa fa-check"></i><b>23.6.2</b> Permutation test</a></li>
<li class="chapter" data-level="23.6.3" data-path="BOOT.html"><a href="BOOT.html#traditional-mathematical-methods"><i class="fa fa-check"></i><b>23.6.3</b> Traditional mathematical methods</a></li>
<li class="chapter" data-level="23.6.4" data-path="BOOT.html"><a href="BOOT.html#hypothesis-tests"><i class="fa fa-check"></i><b>23.6.4</b> Hypothesis tests</a></li>
<li class="chapter" data-level="23.6.5" data-path="BOOT.html"><a href="BOOT.html#confidence-intervals-1"><i class="fa fa-check"></i><b>23.6.5</b> Confidence intervals</a></li>
<li class="chapter" data-level="23.6.6" data-path="BOOT.html"><a href="BOOT.html#bootstrap-1"><i class="fa fa-check"></i><b>23.6.6</b> Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="23.7" data-path="BOOT.html"><a href="BOOT.html#frequently-asked-questions"><i class="fa fa-check"></i><b>23.7</b> Frequently asked questions</a></li>
<li class="chapter" data-level="23.8" data-path="BOOT.html"><a href="BOOT.html#homework-problems-22"><i class="fa fa-check"></i><b>23.8</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="ADDTESTS.html"><a href="ADDTESTS.html"><i class="fa fa-check"></i><b>24</b> Additional Hypothesis Tests</a>
<ul>
<li class="chapter" data-level="24.1" data-path="ADDTESTS.html"><a href="ADDTESTS.html#objectives-22"><i class="fa fa-check"></i><b>24.1</b> Objectives</a></li>
<li class="chapter" data-level="24.2" data-path="ADDTESTS.html"><a href="ADDTESTS.html#introduction-2"><i class="fa fa-check"></i><b>24.2</b> Introduction</a></li>
<li class="chapter" data-level="24.3" data-path="ADDTESTS.html"><a href="ADDTESTS.html#categorical-data-1"><i class="fa fa-check"></i><b>24.3</b> Categorical data</a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="ADDTESTS.html"><a href="ADDTESTS.html#help-example"><i class="fa fa-check"></i><b>24.3.1</b> HELP example</a></li>
<li class="chapter" data-level="24.3.2" data-path="ADDTESTS.html"><a href="ADDTESTS.html#test-statistic"><i class="fa fa-check"></i><b>24.3.2</b> Test statistic</a></li>
<li class="chapter" data-level="24.3.3" data-path="ADDTESTS.html"><a href="ADDTESTS.html#extension-to-larger-tables"><i class="fa fa-check"></i><b>24.3.3</b> Extension to larger tables</a></li>
<li class="chapter" data-level="24.3.4" data-path="ADDTESTS.html"><a href="ADDTESTS.html#permutation-test-1"><i class="fa fa-check"></i><b>24.3.4</b> Permutation test</a></li>
<li class="chapter" data-level="24.3.5" data-path="ADDTESTS.html"><a href="ADDTESTS.html#chi-squared-test"><i class="fa fa-check"></i><b>24.3.5</b> Chi-squared test</a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="ADDTESTS.html"><a href="ADDTESTS.html#numerical-data-2"><i class="fa fa-check"></i><b>24.4</b> Numerical data</a>
<ul>
<li class="chapter" data-level="24.4.1" data-path="ADDTESTS.html"><a href="ADDTESTS.html#mlb-batting-performance"><i class="fa fa-check"></i><b>24.4.1</b> MLB batting performance</a></li>
<li class="chapter" data-level="24.4.2" data-path="ADDTESTS.html"><a href="ADDTESTS.html#analysis-of-variance-anova-and-the-f-test"><i class="fa fa-check"></i><b>24.4.2</b> Analysis of variance (ANOVA) and the F test</a></li>
</ul></li>
<li class="chapter" data-level="24.5" data-path="ADDTESTS.html"><a href="ADDTESTS.html#homework-problems-23"><i class="fa fa-check"></i><b>24.5</b> Homework Problems</a></li>
</ul></li>
<li class="part"><span><b>IV Predictive Statistical Modeling</b></span></li>
<li class="chapter" data-level="25" data-path="CS4.html"><a href="CS4.html"><i class="fa fa-check"></i><b>25</b> Case Study</a>
<ul>
<li class="chapter" data-level="25.1" data-path="CS4.html"><a href="CS4.html#objectives-23"><i class="fa fa-check"></i><b>25.1</b> Objectives</a></li>
<li class="chapter" data-level="25.2" data-path="CS4.html"><a href="CS4.html#introduction-to-linear-regression"><i class="fa fa-check"></i><b>25.2</b> Introduction to linear regression</a></li>
<li class="chapter" data-level="25.3" data-path="CS4.html"><a href="CS4.html#case-study-introduction"><i class="fa fa-check"></i><b>25.3</b> Case study introduction</a>
<ul>
<li class="chapter" data-level="25.3.1" data-path="CS4.html"><a href="CS4.html#load-packages"><i class="fa fa-check"></i><b>25.3.1</b> Load packages</a></li>
<li class="chapter" data-level="25.3.2" data-path="CS4.html"><a href="CS4.html#the-data-and-exploratory-analysis"><i class="fa fa-check"></i><b>25.3.2</b> The data and exploratory analysis</a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="CS4.html"><a href="CS4.html#sum-of-squared-residuals"><i class="fa fa-check"></i><b>25.4</b> Sum of squared residuals</a></li>
<li class="chapter" data-level="25.5" data-path="CS4.html"><a href="CS4.html#the-linear-model"><i class="fa fa-check"></i><b>25.5</b> The linear model</a></li>
<li class="chapter" data-level="25.6" data-path="CS4.html"><a href="CS4.html#prediction-and-prediction-errors"><i class="fa fa-check"></i><b>25.6</b> Prediction and prediction errors</a></li>
<li class="chapter" data-level="25.7" data-path="CS4.html"><a href="CS4.html#model-diagnostics"><i class="fa fa-check"></i><b>25.7</b> Model diagnostics</a></li>
<li class="chapter" data-level="25.8" data-path="CS4.html"><a href="CS4.html#brief-summary"><i class="fa fa-check"></i><b>25.8</b> Brief summary</a></li>
<li class="chapter" data-level="25.9" data-path="CS4.html"><a href="CS4.html#homework-problems-24"><i class="fa fa-check"></i><b>25.9</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="LRBASICS.html"><a href="LRBASICS.html"><i class="fa fa-check"></i><b>26</b> Linear Regression Basics</a>
<ul>
<li class="chapter" data-level="26.1" data-path="LRBASICS.html"><a href="LRBASICS.html#objectives-24"><i class="fa fa-check"></i><b>26.1</b> Objectives</a></li>
<li class="chapter" data-level="26.2" data-path="LRBASICS.html"><a href="LRBASICS.html#linear-regression-models"><i class="fa fa-check"></i><b>26.2</b> Linear regression models</a>
<ul>
<li class="chapter" data-level="26.2.1" data-path="LRBASICS.html"><a href="LRBASICS.html#estimation-1"><i class="fa fa-check"></i><b>26.2.1</b> Estimation</a></li>
<li class="chapter" data-level="26.2.2" data-path="LRBASICS.html"><a href="LRBASICS.html#possum-example"><i class="fa fa-check"></i><b>26.2.2</b> Possum example</a></li>
<li class="chapter" data-level="26.2.3" data-path="LRBASICS.html"><a href="LRBASICS.html#interpretation"><i class="fa fa-check"></i><b>26.2.3</b> Interpretation</a></li>
<li class="chapter" data-level="26.2.4" data-path="LRBASICS.html"><a href="LRBASICS.html#extrapolation-is-dangerous"><i class="fa fa-check"></i><b>26.2.4</b> Extrapolation is dangerous</a></li>
<li class="chapter" data-level="26.2.5" data-path="LRBASICS.html"><a href="LRBASICS.html#reading-computer-output"><i class="fa fa-check"></i><b>26.2.5</b> Reading computer output</a></li>
<li class="chapter" data-level="26.2.6" data-path="LRBASICS.html"><a href="LRBASICS.html#assumptions-1"><i class="fa fa-check"></i><b>26.2.6</b> Assumptions</a></li>
<li class="chapter" data-level="26.2.7" data-path="LRBASICS.html"><a href="LRBASICS.html#residual-plots"><i class="fa fa-check"></i><b>26.2.7</b> Residual plots</a></li>
<li class="chapter" data-level="26.2.8" data-path="LRBASICS.html"><a href="LRBASICS.html#summary-1"><i class="fa fa-check"></i><b>26.2.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="26.3" data-path="LRBASICS.html"><a href="LRBASICS.html#homework-problems-25"><i class="fa fa-check"></i><b>26.3</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="LRINF.html"><a href="LRINF.html"><i class="fa fa-check"></i><b>27</b> Linear Regression Inference</a>
<ul>
<li class="chapter" data-level="27.1" data-path="LRINF.html"><a href="LRINF.html#objectives-25"><i class="fa fa-check"></i><b>27.1</b> Objectives</a></li>
<li class="chapter" data-level="27.2" data-path="LRINF.html"><a href="LRINF.html#introduction-3"><i class="fa fa-check"></i><b>27.2</b> Introduction</a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="LRINF.html"><a href="LRINF.html#regression"><i class="fa fa-check"></i><b>27.2.1</b> Regression</a></li>
<li class="chapter" data-level="27.2.2" data-path="LRINF.html"><a href="LRINF.html#review-of-assumptions"><i class="fa fa-check"></i><b>27.2.2</b> Review of assumptions</a></li>
<li class="chapter" data-level="27.2.3" data-path="LRINF.html"><a href="LRINF.html#distribution-of-our-estimators"><i class="fa fa-check"></i><b>27.2.3</b> Distribution of our estimators</a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="LRINF.html"><a href="LRINF.html#inference"><i class="fa fa-check"></i><b>27.3</b> Inference</a>
<ul>
<li class="chapter" data-level="27.3.1" data-path="LRINF.html"><a href="LRINF.html#starbucks"><i class="fa fa-check"></i><b>27.3.1</b> Starbucks</a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="LRINF.html"><a href="LRINF.html#inference-on-predictions"><i class="fa fa-check"></i><b>27.4</b> Inference on Predictions</a>
<ul>
<li class="chapter" data-level="27.4.1" data-path="LRINF.html"><a href="LRINF.html#starbucks-1"><i class="fa fa-check"></i><b>27.4.1</b> Starbucks</a></li>
<li class="chapter" data-level="27.4.2" data-path="LRINF.html"><a href="LRINF.html#summary-2"><i class="fa fa-check"></i><b>27.4.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="LRINF.html"><a href="LRINF.html#homework-problems-26"><i class="fa fa-check"></i><b>27.5</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="28" data-path="LRDIAG.html"><a href="LRDIAG.html"><i class="fa fa-check"></i><b>28</b> Regression Diagnostics</a>
<ul>
<li class="chapter" data-level="28.1" data-path="LRDIAG.html"><a href="LRDIAG.html#objectives-26"><i class="fa fa-check"></i><b>28.1</b> Objectives</a></li>
<li class="chapter" data-level="28.2" data-path="LRDIAG.html"><a href="LRDIAG.html#introduction-4"><i class="fa fa-check"></i><b>28.2</b> Introduction</a></li>
<li class="chapter" data-level="28.3" data-path="LRDIAG.html"><a href="LRDIAG.html#assessing-our-model---understanding-the-output-from-lm"><i class="fa fa-check"></i><b>28.3</b> Assessing our model - understanding the output from <code>lm</code></a>
<ul>
<li class="chapter" data-level="28.3.1" data-path="LRDIAG.html"><a href="LRDIAG.html#residual-standard-error"><i class="fa fa-check"></i><b>28.3.1</b> Residual Standard Error</a></li>
<li class="chapter" data-level="28.3.2" data-path="LRDIAG.html"><a href="LRDIAG.html#r-squared"><i class="fa fa-check"></i><b>28.3.2</b> R-squared</a></li>
<li class="chapter" data-level="28.3.3" data-path="LRDIAG.html"><a href="LRDIAG.html#f-statistic"><i class="fa fa-check"></i><b>28.3.3</b> F-Statistic</a></li>
</ul></li>
<li class="chapter" data-level="28.4" data-path="LRDIAG.html"><a href="LRDIAG.html#regression-diagnostics"><i class="fa fa-check"></i><b>28.4</b> Regression diagnostics</a>
<ul>
<li class="chapter" data-level="28.4.1" data-path="LRDIAG.html"><a href="LRDIAG.html#residual-plots-1"><i class="fa fa-check"></i><b>28.4.1</b> Residual plots</a></li>
<li class="chapter" data-level="28.4.2" data-path="LRDIAG.html"><a href="LRDIAG.html#residuals-vs-fitted"><i class="fa fa-check"></i><b>28.4.2</b> Residuals vs Fitted</a></li>
<li class="chapter" data-level="28.4.3" data-path="LRDIAG.html"><a href="LRDIAG.html#normal-q-q-plot"><i class="fa fa-check"></i><b>28.4.3</b> Normal Q-Q Plot</a></li>
<li class="chapter" data-level="28.4.4" data-path="LRDIAG.html"><a href="LRDIAG.html#scale-location-plot"><i class="fa fa-check"></i><b>28.4.4</b> Scale-Location Plot</a></li>
</ul></li>
<li class="chapter" data-level="28.5" data-path="LRDIAG.html"><a href="LRDIAG.html#outliers-and-leverage"><i class="fa fa-check"></i><b>28.5</b> Outliers and leverage</a>
<ul>
<li class="chapter" data-level="28.5.1" data-path="LRDIAG.html"><a href="LRDIAG.html#residuals-vs-leverage-plot"><i class="fa fa-check"></i><b>28.5.1</b> Residuals vs Leverage Plot</a></li>
<li class="chapter" data-level="28.5.2" data-path="LRDIAG.html"><a href="LRDIAG.html#what-if-our-assumptions-are-violated"><i class="fa fa-check"></i><b>28.5.2</b> What If Our Assumptions Are Violated</a></li>
</ul></li>
<li class="chapter" data-level="28.6" data-path="LRDIAG.html"><a href="LRDIAG.html#homework-problems-27"><i class="fa fa-check"></i><b>28.6</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="29" data-path="LRSIM.html"><a href="LRSIM.html"><i class="fa fa-check"></i><b>29</b> Simulation Based Linear Regression</a>
<ul>
<li class="chapter" data-level="29.1" data-path="LRSIM.html"><a href="LRSIM.html#objectives-27"><i class="fa fa-check"></i><b>29.1</b> Objectives</a></li>
<li class="chapter" data-level="29.2" data-path="LRSIM.html"><a href="LRSIM.html#introduction-5"><i class="fa fa-check"></i><b>29.2</b> Introduction</a></li>
<li class="chapter" data-level="29.3" data-path="LRSIM.html"><a href="LRSIM.html#confidence-intervals-for-parameters"><i class="fa fa-check"></i><b>29.3</b> Confidence intervals for parameters</a>
<ul>
<li class="chapter" data-level="29.3.1" data-path="LRSIM.html"><a href="LRSIM.html#resampling"><i class="fa fa-check"></i><b>29.3.1</b> Resampling</a></li>
<li class="chapter" data-level="29.3.2" data-path="LRSIM.html"><a href="LRSIM.html#resample-residuals"><i class="fa fa-check"></i><b>29.3.2</b> Resample residuals</a></li>
</ul></li>
<li class="chapter" data-level="29.4" data-path="LRSIM.html"><a href="LRSIM.html#confidence-intervals-for-prediction"><i class="fa fa-check"></i><b>29.4</b> Confidence intervals for prediction</a>
<ul>
<li class="chapter" data-level="29.4.1" data-path="LRSIM.html"><a href="LRSIM.html#prediction-interval"><i class="fa fa-check"></i><b>29.4.1</b> Prediction interval</a></li>
</ul></li>
<li class="chapter" data-level="29.5" data-path="LRSIM.html"><a href="LRSIM.html#categorical-predictor"><i class="fa fa-check"></i><b>29.5</b> Categorical predictor</a>
<ul>
<li class="chapter" data-level="29.5.1" data-path="LRSIM.html"><a href="LRSIM.html#lending-club"><i class="fa fa-check"></i><b>29.5.1</b> Lending Club</a></li>
<li class="chapter" data-level="29.5.2" data-path="LRSIM.html"><a href="LRSIM.html#bootstrap-2"><i class="fa fa-check"></i><b>29.5.2</b> Bootstrap</a></li>
<li class="chapter" data-level="29.5.3" data-path="LRSIM.html"><a href="LRSIM.html#anova-table"><i class="fa fa-check"></i><b>29.5.3</b> ANOVA Table</a></li>
<li class="chapter" data-level="29.5.4" data-path="LRSIM.html"><a href="LRSIM.html#pairwise-comparisons"><i class="fa fa-check"></i><b>29.5.4</b> Pairwise Comparisons</a></li>
</ul></li>
<li class="chapter" data-level="29.6" data-path="LRSIM.html"><a href="LRSIM.html#assumptions-2"><i class="fa fa-check"></i><b>29.6</b> Assumptions</a></li>
<li class="chapter" data-level="29.7" data-path="LRSIM.html"><a href="LRSIM.html#homework-problems-28"><i class="fa fa-check"></i><b>29.7</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="30" data-path="LRMULTI.html"><a href="LRMULTI.html"><i class="fa fa-check"></i><b>30</b> Multiple Linear Regression</a>
<ul>
<li class="chapter" data-level="30.1" data-path="LRMULTI.html"><a href="LRMULTI.html#objectives-28"><i class="fa fa-check"></i><b>30.1</b> Objectives</a></li>
<li class="chapter" data-level="30.2" data-path="LRMULTI.html"><a href="LRMULTI.html#introduction-to-multiple-regression"><i class="fa fa-check"></i><b>30.2</b> Introduction to multiple regression</a></li>
<li class="chapter" data-level="30.3" data-path="LRMULTI.html"><a href="LRMULTI.html#multiple-regression"><i class="fa fa-check"></i><b>30.3</b> Multiple regression</a>
<ul>
<li class="chapter" data-level="30.3.1" data-path="LRMULTI.html"><a href="LRMULTI.html#a-single-variable-model-for-the-mario-kart-data"><i class="fa fa-check"></i><b>30.3.1</b> A single-variable model for the Mario Kart data</a></li>
<li class="chapter" data-level="30.3.2" data-path="LRMULTI.html"><a href="LRMULTI.html#including-and-assessing-many-variables-in-a-model"><i class="fa fa-check"></i><b>30.3.2</b> Including and assessing many variables in a model</a></li>
<li class="chapter" data-level="30.3.3" data-path="LRMULTI.html"><a href="LRMULTI.html#inference-1"><i class="fa fa-check"></i><b>30.3.3</b> Inference</a></li>
<li class="chapter" data-level="30.3.4" data-path="LRMULTI.html"><a href="LRMULTI.html#adjusted-r2-as-a-better-estimate-of-explained-variance"><i class="fa fa-check"></i><b>30.3.4</b> Adjusted <span class="math inline">\(R^2\)</span> as a better estimate of explained variance</a></li>
<li class="chapter" data-level="30.3.5" data-path="LRMULTI.html"><a href="LRMULTI.html#reduced-model"><i class="fa fa-check"></i><b>30.3.5</b> Reduced model</a></li>
<li class="chapter" data-level="30.3.6" data-path="LRMULTI.html"><a href="LRMULTI.html#confidence-and-prediction-intervals"><i class="fa fa-check"></i><b>30.3.6</b> Confidence and prediction intervals</a></li>
<li class="chapter" data-level="30.3.7" data-path="LRMULTI.html"><a href="LRMULTI.html#diagnostics"><i class="fa fa-check"></i><b>30.3.7</b> Diagnostics</a></li>
</ul></li>
<li class="chapter" data-level="30.4" data-path="LRMULTI.html"><a href="LRMULTI.html#interaction-and-higher-order-terms"><i class="fa fa-check"></i><b>30.4</b> Interaction and Higher Order Terms</a>
<ul>
<li class="chapter" data-level="30.4.1" data-path="LRMULTI.html"><a href="LRMULTI.html#summary-3"><i class="fa fa-check"></i><b>30.4.1</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="30.5" data-path="LRMULTI.html"><a href="LRMULTI.html#homework-problems-29"><i class="fa fa-check"></i><b>30.5</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="31" data-path="LOGREG.html"><a href="LOGREG.html"><i class="fa fa-check"></i><b>31</b> Logistic Regression</a>
<ul>
<li class="chapter" data-level="31.1" data-path="LOGREG.html"><a href="LOGREG.html#objectives-29"><i class="fa fa-check"></i><b>31.1</b> Objectives</a></li>
<li class="chapter" data-level="31.2" data-path="LOGREG.html"><a href="LOGREG.html#logistic-regression-introduction"><i class="fa fa-check"></i><b>31.2</b> Logistic regression introduction</a>
<ul>
<li class="chapter" data-level="31.2.1" data-path="LOGREG.html"><a href="LOGREG.html#mario-kart-data"><i class="fa fa-check"></i><b>31.2.1</b> Mario Kart data</a></li>
<li class="chapter" data-level="31.2.2" data-path="LOGREG.html"><a href="LOGREG.html#analyzing-contingency-table"><i class="fa fa-check"></i><b>31.2.2</b> Analyzing contingency table</a></li>
<li class="chapter" data-level="31.2.3" data-path="LOGREG.html"><a href="LOGREG.html#modeling-the-probability-of-an-event"><i class="fa fa-check"></i><b>31.2.3</b> Modeling the probability of an event</a></li>
<li class="chapter" data-level="31.2.4" data-path="LOGREG.html"><a href="LOGREG.html#first-model---intercept-only"><i class="fa fa-check"></i><b>31.2.4</b> First model - intercept only</a></li>
<li class="chapter" data-level="31.2.5" data-path="LOGREG.html"><a href="LOGREG.html#second-model---stock_photo"><i class="fa fa-check"></i><b>31.2.5</b> Second model - stock_photo</a></li>
<li class="chapter" data-level="31.2.6" data-path="LOGREG.html"><a href="LOGREG.html#interpreting-the-coefficients"><i class="fa fa-check"></i><b>31.2.6</b> Interpreting the coefficients</a></li>
<li class="chapter" data-level="31.2.7" data-path="LOGREG.html"><a href="LOGREG.html#comparing-models"><i class="fa fa-check"></i><b>31.2.7</b> Comparing models</a></li>
</ul></li>
<li class="chapter" data-level="31.3" data-path="LOGREG.html"><a href="LOGREG.html#multiple-logistic-regression"><i class="fa fa-check"></i><b>31.3</b> Multiple logistic regression</a>
<ul>
<li class="chapter" data-level="31.3.1" data-path="LOGREG.html"><a href="LOGREG.html#diagnostics-for-logistic-regression"><i class="fa fa-check"></i><b>31.3.1</b> Diagnostics for logistic regression</a></li>
</ul></li>
<li class="chapter" data-level="31.4" data-path="LOGREG.html"><a href="LOGREG.html#confidence-intervals-2"><i class="fa fa-check"></i><b>31.4</b> Confidence intervals</a>
<ul>
<li class="chapter" data-level="31.4.1" data-path="LOGREG.html"><a href="LOGREG.html#confidence-intervals-for-a-parameter"><i class="fa fa-check"></i><b>31.4.1</b> Confidence intervals for a parameter</a></li>
<li class="chapter" data-level="31.4.2" data-path="LOGREG.html"><a href="LOGREG.html#confidence-intervals-for-probability-of-success"><i class="fa fa-check"></i><b>31.4.2</b> Confidence intervals for probability of success</a></li>
</ul></li>
<li class="chapter" data-level="31.5" data-path="LOGREG.html"><a href="LOGREG.html#summary-4"><i class="fa fa-check"></i><b>31.5</b> Summary</a></li>
<li class="chapter" data-level="31.6" data-path="LOGREG.html"><a href="LOGREG.html#homework-problems-30"><i class="fa fa-check"></i><b>31.6</b> Homework Problems</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Probability and Statistics for Scientists and Engineers</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="EST" class="section level1" number="17">
<h1><span class="header-section-number">Chapter 17</span> Estimation Methods</h1>
<div id="objectives-16" class="section level2" number="17.1">
<h2><span class="header-section-number">17.1</span> Objectives</h2>
<ol style="list-style-type: decimal">
<li>Obtain a method of moments estimate of a parameter or set of parameters.<br />
</li>
<li>Given a random sample from a distribution, obtain the likelihood function.<br />
</li>
<li>Obtain a maximum likelihood estimate of a parameter or set of parameters.<br />
</li>
<li>Determine if an estimator is unbiased.</li>
</ol>
</div>
<div id="transition" class="section level2" number="17.2">
<h2><span class="header-section-number">17.2</span> Transition</h2>
<p>We started this book with descriptive models of data and then moved onto probability models. In these probability models, we have been characterizing experiments and random processes using both theory and simulation. These models are using a model about a random event to make decisions about data. These models are about the population and are used to make decisions about samples and data. For example, suppose we flip a fair coin 10 times, and record the number of heads. The population is the collection of all possible outcomes of this experiment. In this case, the population is infinite, as we could run this experiment repeatedly without limit. If we assume, model, the number of heads as a binomial distribution, we know the exact distribution of the outcomes. For example, we know that exactly 24.61% of the time, we will obtain 5 heads out of 10 flips of a fair coin. We can also use the model to characterize the variance, that is when it does not equal 5 and how much different from 5 it will be. However, these probability models are highly dependent on the assumptions and the values of the parameters.</p>
<p>From this point on in the book, we will focus on <em>statistical</em> models. Statistical models describe one or more variables and their relationships. We use these models to make decisions about the population, to predict future outcomes, or both. Often we don’t know the true underlying process; all we have is a <em>sample</em> of observations and perhaps some context. Using <em>inferential</em> statistics, we can draw conclusions about the underlying process. For example, suppose we are given a coin and we don’t know whether it is fair. So, we flip it a number of times to obtain a sample of outcomes. We can use that sample to decide whether the coin could be fair.</p>
<p>In some sense, we’ve already explored some of these concepts. In our simulation examples, we have drawn observations from a population of interest and used those observations to estimate characteristics of another population or segment of the experiment. For example, we explored random variable <span class="math inline">\(Z\)</span>, where <span class="math inline">\(Z=|X - Y|\)</span> and <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> were both uniform random variables. Instead of dealing with the distribution of <span class="math inline">\(Z\)</span> directly, we simulated many observations from <span class="math inline">\(Z\)</span> and used this simulation to describe the behavior of <span class="math inline">\(Z\)</span>.</p>
<p>Statistical models and probability models are not separate. In statistical models we find relationships, the explained portion of variation, and use probability models for the remaining random variation. In Figure <a href="EST.html#fig:prob-stats">17.1</a>, we demonstrate this relationship between the two types of models. In the first part of our studies, we will use univariate data in statistical models to estimate the parameters of a probability model. From there we will develop more sophisticated models to include multivariate models.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:prob-stats"></span>
<img src="figures/Prob_Stats.png" alt="A graphical representation of probability and statistics. In probability, we describe what we expect to happen if we know that underlying process; in statistics, we don't know the underlying process, and must infer based on representative samples." width="576" />
<p class="caption">
Figure 17.1: A graphical representation of probability and statistics. In probability, we describe what we expect to happen if we know that underlying process; in statistics, we don’t know the underlying process, and must infer based on representative samples.
</p>
</div>
</div>
<div id="estimation" class="section level2" number="17.3">
<h2><span class="header-section-number">17.3</span> Estimation</h2>
<p>Recall that in probability models, we have complete information about the population and we use that to describe the expected behavior of samples from that population. In statistics we are given a sample from a population about which we know little or nothing.</p>
<p>In this lesson, we will discuss <em>estimation</em>. Given a sample, we would like to estimate population parameters. There are several ways to do that. We will discuss two methods: <em>method of moments</em> and <em>maximum likelihood</em>.</p>
</div>
<div id="method-of-moments" class="section level2" number="17.4">
<h2><span class="header-section-number">17.4</span> Method of Moments</h2>
<p>Recall earlier we discussed moments. We can refer to <span class="math inline">\(\mbox{E}(X) = \mu\)</span> as the first moment or mean. Further, we can refer to <span class="math inline">\(\mbox{E}(X^k)\)</span> as the <span class="math inline">\(k\)</span>th central moment and <span class="math inline">\(\mbox{E}[(X-\mu)^k]\)</span> as the <span class="math inline">\(k\)</span> moment around the mean. The second moment around the mean is also known as variance. It is important to point out that these are <strong>POPULATION</strong> moments and are typically some function of the parameters of a probability model.</p>
<p>Suppose <span class="math inline">\(X_1,X_2,...,X_n\)</span> is a sequence of independent, identically distributed random variables with some distribution and parameters <span class="math inline">\(\boldsymbol{\theta}\)</span>. When provided with a random sample of data, we will not know the population moments. However, we can obtain <em>sample moments</em>. The <span class="math inline">\(k\)</span>th central sample moment is denoted by <span class="math inline">\(\hat{\mu}_k\)</span> and is given by
<span class="math display">\[
\hat{\mu}_k = \frac{1}{n}\sum_{i=1}^n x_i^k
\]</span></p>
<p>The <span class="math inline">\(k\)</span>th sample moment around the mean is denoted by <span class="math inline">\(\hat{\mu}&#39;_k\)</span> and is given by
<span class="math display">\[
\hat{\mu}&#39;_k=\frac{1}{n} \sum_{i=1}^n (x_i-\bar{x})^k
\]</span></p>
<p>The value <span class="math inline">\(\hat{\mu}\)</span> is read “mu-hat.” The hat denotes that the value is an estimate.</p>
<p>We can use the sample moments to estimate the population moments since the population moments are usually functions of a distribution’s parameters, <span class="math inline">\(\boldsymbol{\theta}\)</span>. Thus, we can solve for the parameters to obtain method of moments estimates of <span class="math inline">\(\boldsymbol{\theta}\)</span>.</p>
<p>This is all technical, so let’s look at an example.</p>
<blockquote>
<p><em>Example</em>:<br />
Suppose <span class="math inline">\(x_1,x_2,...,x_n\)</span> is an iid, independent and identically distributed, sample from a uniform distribution <span class="math inline">\(\textsf{Unif}(0,\theta)\)</span>, and we don’t know <span class="math inline">\(\theta\)</span>. That is, our data consists of positive random numbers but we don’t know the upper bound. Find the method of moments estimator for <span class="math inline">\(\theta\)</span>, the upper bound.</p>
</blockquote>
<p>We know that if <span class="math inline">\(X\sim \textsf{Unif}(a,b)\)</span>, then <span class="math inline">\(\mbox{E}(X)=\frac{a+b}{2}\)</span>. So, in this case, <span class="math inline">\(\mbox{E}(X)={\theta \over 2}\)</span>. This is the first population moment. We can estimate this with the first <em>sample</em> moment, which is just the sample mean:
<span class="math display">\[
\hat{\mu}_1=\frac{1}{n}\sum_{i=1}^n x_i = \bar{x}
\]</span></p>
<p>Our best guess for the first population moment (<span class="math inline">\(\theta/2\)</span>) is the first sample moment (<span class="math inline">\(\bar{x}\)</span>). From a common sense perspective, we are hoping that the sample moment will be close in value to the population moment, so we can set them equal and solve for the unknown population parameter. This is essentially what we were doing in our simulations of probability models. Solving for <span class="math inline">\(\theta\)</span> yields our method of moments estimator for <span class="math inline">\(\theta\)</span>:
<span class="math display">\[
\hat{\theta}_{MoM}=2\bar{x}
\]</span></p>
<p>Note that we could have used the second moments about the mean as well. This is less intuitive but still applicable. In this case we know that if <span class="math inline">\(X\sim \textsf{Unif}(a,b)\)</span>, then <span class="math inline">\(\mbox{Var}(X)=\frac{(b - a)^2}{12}\)</span>. So, in this case, <span class="math inline">\(\mbox{Var}(X)=\frac{\theta ^2}{ 12}\)</span>. We use the second sample moment about the mean <span class="math inline">\(\hat{\mu}&#39;_2=\frac{1}{n} \sum_{i=1}^n (x_i-\bar{x})^2\)</span> which is not quite the sample variance. In fact, the sample variance is related to the second sample moment about the mean by <span class="math inline">\(\hat{\mu}&#39;_2 = s^2 \frac{n}{n-1}\)</span>. Setting the population moment and sample moment equal and solving we get</p>
<p><span class="math display">\[
\hat{\theta}_{MoM}=\sqrt{\frac{12n}{n-1}}s
\]</span></p>
<p>To decide which is better we need a criteria of comparison. This is beyond the scope of this book, but some common criteria are <em>unbiased</em> and <em>minimum variance</em>.</p>
<p>The method of moments can be used to estimate more than one parameter as well. We simply would have to incorporate higher order moments.</p>
<blockquote>
<p><em>Example</em>:<br />
Suppose we take an iid sample from the normal distribution with parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>. Find method of moments estimates of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>.</p>
</blockquote>
<p>First, we remember that we know two population moments for the normal distribution:
<span class="math display">\[
\mbox{E}(X)=\mu \hspace{1cm} \mbox{Var}(X)=\mbox{E}[(X-\mu)^2]=\sigma^2
\]</span></p>
<p>Setting these equal to the sample moments yields:
<span class="math display">\[
\hat{\mu}_{MoM}=\bar{x} \hspace{1cm} \hat{\sigma}_{MoM} = \sqrt{\frac{1}{n}\sum_{i=1}^n (x_i-\bar{x})^2}
\]</span></p>
<p>Again, we notice that the estimate for <span class="math inline">\(\sigma\)</span> is different from sample standard deviation discussed earlier in the book. The reason for this is a property of estimators called <em>unbiased</em>. Notice that if we treat the data points as random variables then the estimators are random variables. We can then take the expected value of the estimator and if this equals the parameter being estimated, then it is unbiased. Mathematically, this is written
<span class="math display">\[
E(\hat{\theta})=\theta
\]</span>
Unbiased is not a required property for an estimated but many practitioners find it desirable. In words, unbiased means that on average the estimator will equal the true value. Sample variance using <span class="math inline">\(n-1\)</span> in the denominator is an unbiased estimate of the population variance.</p>
<blockquote>
<p><em>Exercise</em>:<br />
You shot 25 free throws and make 21. Assuming a binomial model fits. Find an estimate of the probability of making a free throw.</p>
</blockquote>
<p>There are two ways to approach this problem depending on how we define the random variable. In the first case we will use a binomial random variable, <span class="math inline">\(X\)</span> the number of made free throws in 25 attempts. In this case, we only ran the experiment once and have the observed result of 21. Recall for the binomial <span class="math inline">\(E(X)=np\)</span> where <span class="math inline">\(n\)</span> is the number of attempts and <span class="math inline">\(p\)</span> is the probability of success. The sample mean is 21 since we only have one data point. Using the method of moments, we set the first population mean equal to the first sample mean <span class="math inline">\(np=\frac{\sum{x_i}}{m}\)</span>, notice <span class="math inline">\(n\)</span> is the number of trials 25 and <span class="math inline">\(m\)</span> is the number of data points 1, or <span class="math inline">\(25 \hat{p} = 21\)</span>. Thus <span class="math inline">\(\hat{p} = \frac{21}{25}\)</span>.</p>
<p>A second approach is to let <span class="math inline">\(X_i\)</span> be a single free throw, we have a Bernoulli random variable. This variable takes on the values of 0 if we miss and 1 if we make the free throw. Thus we have 25 data points. For a Bernoulli random variable <span class="math inline">\(E(X)=p\)</span>. The sample is <span class="math inline">\(\bar{x} = \frac{21}{25}\)</span>. Using the method of moments, we set the sample mean equal to the population mean. We have <span class="math inline">\(E(X) = \hat{p} = \bar{x} = \frac{21}{25}\)</span>. This is a natural estimate; we estimate our probability of success as the number of made free throws divided by the number of shots. As a side note, this is an unbiased estimator since
<span class="math display">\[
E(\hat{p})=E\left( \sum{\frac{X_i}{n}} \right)
\]</span></p>
<p><span class="math display">\[
=  \sum{E\left( \frac{X_i}{n} \right)}= \sum{ \frac{E\left(X_i\right)}{n}}=\sum{\frac{p}{n}}=\frac{np}{n}=p
\]</span></p>
</div>
<div id="maximum-likelihood" class="section level2" number="17.5">
<h2><span class="header-section-number">17.5</span> Maximum likelihood</h2>
<p>Recall that using method of moments involves finding values of the parameters that cause the population moments to be equal to the sample moments. Solving for the parameters yields method of moments estimates.</p>
<p>Next we will discuss one more estimation method, <em>maximum likelihood estimation</em>. In this method, we are finding values of parameters that would make the observed data most “likely.” In order to do this, we first need to introduce the <em>likelihood function</em>.</p>
<div id="likelihood-function" class="section level3" number="17.5.1">
<h3><span class="header-section-number">17.5.1</span> Likelihood Function</h3>
<p>Suppose <span class="math inline">\(x_1,x_2,...,x_n\)</span> is an iid random sample from a distribution with mass/density function <span class="math inline">\(f_{X}(x;\boldsymbol{\theta})\)</span> where <span class="math inline">\(\boldsymbol{\theta}\)</span> are the parameters. Let’s take a second to explain this notation. We are using a bold symbol for <span class="math inline">\(\boldsymbol{\theta}\)</span> to indicate it is a vector, that it can be one or more values. However, in the pmf/pdf <span class="math inline">\(x\)</span> is not bold since it is a scalar variable. In our probability models we know <span class="math inline">\(\boldsymbol{\theta}\)</span> and then use to model to make decision about the random variable <span class="math inline">\(X\)</span>.</p>
<p>The likelihood function is denoted as <span class="math inline">\(L(\boldsymbol{\theta};x_1,x_2,...,x_n) = L(\boldsymbol{\theta};\boldsymbol{x})\)</span>. Now we have multiple instances of the random variable, we use <span class="math inline">\(\boldsymbol{x}\)</span>. Since our random sample is iid, independent and identically distributed, we can write the likelihood function as a product of the pmfs/pdfs:
<span class="math display">\[
L(\boldsymbol{\theta};\boldsymbol{x})=\prod_{i=1}^n f_X(x_i;\boldsymbol{\theta})
\]</span></p>
<p>The likelihood function is really the pmf/pdf except instead of the variables being random and the parameter(s) fixed, the values of the variable are known and the parameter(s) are unknown. A note on notation, we are using the semicolon in the pdf and likelihood function to denote what is known or given. In the pmf/pdf the parameters are known and thus follow the semicolon. The opposite is the case in the likelihood function.</p>
<p>Let’s do an example to help understand these ideas.</p>
<blockquote>
<p><em>Example</em>:<br />
Suppose we are presented with a coin and are unsure of its fairness. We toss the coin 50 times and obtain 18 heads and 32 tails. Let <span class="math inline">\(\pi\)</span> be the probability that a coin flip results in heads, we could use <span class="math inline">\(p\)</span> but we are getting you used to the two different common ways to represent a binomial parameter. What is the likelihood function of <span class="math inline">\(\pi\)</span>?</p>
</blockquote>
<p>This is a binomial process, but each individual coin flip can be thought of as a Bernoulli experiment. That is, <span class="math inline">\(x_1,x_2,...,x_{50}\)</span> is an iid sample from <span class="math inline">\(\textsf{Binom}(1,\pi)\)</span> or, in other words, <span class="math inline">\(\textsf{Bernoulli}(\pi)\)</span>. Each <span class="math inline">\(x_i\)</span> is either 1 or 0. The pmf of <span class="math inline">\(X\)</span>, a Bernoulli random variable, is simply:
<span class="math display">\[
f_X(x;\pi)= \binom{1}{x} \pi^x(1-\pi)^{1-x} = \pi^x(1-\pi)^{1-x}
\]</span></p>
<p>Notice this makes sense</p>
<p><span class="math display">\[
f_X(1)=P(X=1)= \pi^1(1-\pi)^{1-1}=\pi
\]</span></p>
<p>and</p>
<p><span class="math display">\[
f_X(0)=P(X=0)= \pi^0(1-\pi)^{1-0}=(1-\pi)
\]</span></p>
<p>Generalizing for any sample size <span class="math inline">\(n\)</span>, the likelihood function is:
<span class="math display">\[
L(\pi;\boldsymbol{x})=\prod_{i=1}^{n} \pi^{x_i}(1-\pi)^{1-x_i} = \pi^{\sum_{i=1}^{n} x_i}(1-\pi)^{n-\sum_{i=1}^{n} x_i}
\]</span></p>
<p>For our example <span class="math inline">\(n=50\)</span> and the</p>
<p><span class="math display">\[
L(\pi;\boldsymbol{x})=\prod_{i=1}^{50} \pi^{x_i}(1-\pi)^{1-x_i} = \pi^{18}(1-\pi)^{32}
\]</span></p>
<p>which makes sense because we had 18 successes, heads, and 32 failures, tails. The likelihood function is a function of the unknown parameter <span class="math inline">\(\pi\)</span>.</p>
</div>
<div id="maximum-likelihood-estimation" class="section level3" number="17.5.2">
<h3><span class="header-section-number">17.5.2</span> Maximum Likelihood Estimation</h3>
<p>Once we have a likelihood function <span class="math inline">\(L(\boldsymbol{\theta},\boldsymbol{x})\)</span>, we need to figure out which value of <span class="math inline">\(\boldsymbol{\theta}\)</span> makes the data most likely. In other words, we need to maximize <span class="math inline">\(L\)</span> with respect to <span class="math inline">\(\boldsymbol{\theta}\)</span>.</p>
<p>Most of the time (but not always), this will involve simple optimization through calculus (i.e., take the derivative with respect to the parameter, set to 0 and solve for the parameter). When maximizing the likelihood function through calculus, it is often easier to maximize the log of the likelihood function, denoted as <span class="math inline">\(l\)</span> and often referred to as the “log-likelihood function”:
<span class="math display">\[
l(\boldsymbol{\theta};\boldsymbol{x})= \log L(\boldsymbol{\theta};\boldsymbol{x}) 
\]</span>
Note that since logarithm is one-to-one, onto and increasing, maximizing the log-likelihood function is equivalent to maximizing the likelihood function, and the maximum will occur at the same values of the parameters. We are using <code>log</code> because now we can take the derivative of a sum instead of a product, thus making it much easier.</p>
<blockquote>
<p><em>Example</em>:<br />
Continuing our example. Find the maximum likelihood estimator for <span class="math inline">\(\pi\)</span>.</p>
</blockquote>
<p>Recall that our likelihood function is
<span class="math display">\[
L(\pi;\boldsymbol{x})= \pi^{\sum x_i}(1-\pi)^{n-\sum x_i}
\]</span></p>
<p>Figure <a href="EST.html#fig:lik1-fig">17.2</a> is a plot of the likelihood function as a function of the unknown parameter <span class="math inline">\(\pi\)</span>.</p>
<pre><code>## Warning: geom_vline(): Ignoring `mapping` because `xintercept` was provided.</code></pre>
<div class="figure"><span style="display:block;" id="fig:lik1-fig"></span>
<img src="17-Estimation-Methods_files/figure-html/lik1-fig-1.png" alt="Likelihood function for 18 successes in 50 trials" width="672" />
<p class="caption">
Figure 17.2: Likelihood function for 18 successes in 50 trials
</p>
</div>
<p>By visual inspection, the value of <span class="math inline">\(\pi\)</span> that makes our data most likely, maximizes the likelihood function, is something a little less than 0.4, the actual value is 0.36 as indicated by the blue line in Figure <a href="EST.html#fig:lik1-fig">17.2</a>.</p>
<p>To maximize by mathematical methods, we need to take the derivative of the likelihood function with respect to <span class="math inline">\(\pi\)</span>. We can do this because the likelihood function is a continuous function. Even though the binomial is a discrete random variable, its likelihood is a continuous function.</p>
<p>We can find the derivative of the likelihood function by applying the product rule:
<span class="math display">\[
{\mathop{}\!\mathrm{d}L(\pi;\boldsymbol{x})\over \mathop{}\!\mathrm{d}\pi} = \left(\sum x_i\right) \pi^{\sum x_i -1}(1-\pi)^{n-\sum x_i} + \pi^{\sum x_i}\left(\sum x_i -n\right)(1-\pi)^{n-\sum x_i -1}
\]</span></p>
<p>We could simplify this, set to 0, and solve for <span class="math inline">\(\pi\)</span>. However, it may be easier to use the log-likelihood function:
<span class="math display">\[
l(\pi;\boldsymbol{x})=\log L(\pi;\boldsymbol{x})= \log \left(\pi^{\sum x_i}(1-\pi)^{n-\sum x_i}\right) = \sum x_i \log \pi + (n-\sum x_i)\log (1-\pi)
\]</span></p>
<p>Now, taking the derivative does not require the product rule:
<span class="math display">\[
{\mathop{}\!\mathrm{d}l(\pi;\boldsymbol{x})\over \mathop{}\!\mathrm{d}\pi}= {\sum x_i \over \pi} - {n-\sum x_i\over (1-\pi)}
\]</span></p>
<p>Setting equal to 0 yields:
<span class="math display">\[
{\sum x_i \over \pi} ={n-\sum x_i\over (1-\pi)}
\]</span></p>
<p>Solving for <span class="math inline">\(\pi\)</span> yields
<span class="math display">\[
\hat{\pi}_{MLE}={\sum x_i \over n}
\]</span></p>
<p>Note that technically, we should confirm that the function is concave down at our critical value, ensuring that <span class="math inline">\(\hat{\pi}_{MLE}\)</span> is, in fact, a maximum:
<span class="math display">\[
{\mathop{}\!\mathrm{d}^2 l(\pi;\boldsymbol{x})\over \mathop{}\!\mathrm{d}\pi^2}= {-\sum x_i \over \pi^2} - {n-\sum x_i\over (1-\pi)^2}
\]</span></p>
<p>This value is negative for all relevant values of <span class="math inline">\(\pi\)</span>, so <span class="math inline">\(l\)</span> is concave down and <span class="math inline">\(\hat{\pi}_{MLE}\)</span> is a maximum.</p>
<p>In the case of our example (18 heads out of 50 trials), <span class="math inline">\(\hat{\pi}_{MLE}=18/50=0.36\)</span>.</p>
<p>This seems to make sense. Our best guess for the probability of heads is the number of observed heads divided by our number of trials. That was a great deal of algebra and calculus for what appears to be an obvious answer. However, in more difficult problems, it is not as obvious what to use for a MLE.</p>
</div>
<div id="numerical-methods" class="section level3" number="17.5.3">
<h3><span class="header-section-number">17.5.3</span> Numerical Methods</h3>
<p>When obtaining MLEs, there are times when analytical methods (calculus) are not feasible or not possible. In the Pruim book <span class="citation">(<a href="#ref-pruim2011foundations" role="doc-biblioref">R. J. Pruim 2011</a>)</span>, there is a good example regarding data from Old Faithful at Yellowstone National Park. We need to load the <strong>fastR2</strong> package for this example.</p>
<div class="sourceCode" id="cb435"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb435-1"><a href="EST.html#cb435-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fastR2)</span></code></pre></div>
<p>The <code>faithful</code> data set is preloaded into <code>R</code> and contains 272 observations of 2 variables: eruption time in minutes and waiting time until next eruption. If we plot eruption durations, we notice that the distribution appears bimodal, see Figure <a href="EST.html#fig:hist171-fig">17.3</a>.</p>
<div class="figure"><span style="display:block;" id="fig:hist171-fig"></span>
<img src="17-Estimation-Methods_files/figure-html/hist171-fig-1.png" alt="Histogram of eruption durations of Old Faithful." width="672" />
<p class="caption">
Figure 17.3: Histogram of eruption durations of Old Faithful.
</p>
</div>
<p>Within each section, the distribution appears somewhat bell-curve-ish so we’ll model the eruption time with a mixture of two normal distributions. In this mixture, a proportion <span class="math inline">\(\alpha\)</span> of our eruptions belong to one normal distribution and the remaining <span class="math inline">\(1-\alpha\)</span> belong to the other normal distribution. The density function of eruptions is given by:
<span class="math display">\[
\alpha f(x;\mu_1,\sigma_1)+(1-\alpha)f(x;\mu_2,\sigma_2)
\]</span></p>
<p>where <span class="math inline">\(f\)</span> is the pdf of the normal distribution with parameters specified.</p>
<p>We have five parameters to estimate: <span class="math inline">\(\alpha, \mu_1, \mu_2, \sigma_1, \sigma_2\)</span>. Obviously, estimation through differentiation is not feasible and thus we will use numerical methods. This code is less in the spirit of <code>tidyverse</code> but we want you to see the example. Try to work your way through the code below:</p>
<div class="sourceCode" id="cb436"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb436-1"><a href="EST.html#cb436-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define function for pdf of eruptions as a mixture of normals</span></span>
<span id="cb436-2"><a href="EST.html#cb436-2" aria-hidden="true" tabindex="-1"></a>dmix<span class="ot">&lt;-</span><span class="cf">function</span>(x,alpha,mu1,mu2,sigma1,sigma2){</span>
<span id="cb436-3"><a href="EST.html#cb436-3" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(alpha <span class="sc">&lt;</span> <span class="dv">0</span>) <span class="fu">dnorm</span>(x,mu2,sigma2)</span>
<span id="cb436-4"><a href="EST.html#cb436-4" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(alpha <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="fu">dnorm</span>(x,mu1,sigma1)</span>
<span id="cb436-5"><a href="EST.html#cb436-5" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(alpha <span class="sc">&gt;=</span> <span class="dv">0</span> <span class="sc">&amp;&amp;</span> alpha <span class="sc">&lt;=</span><span class="dv">1</span>){</span>
<span id="cb436-6"><a href="EST.html#cb436-6" aria-hidden="true" tabindex="-1"></a>    alpha<span class="sc">*</span><span class="fu">dnorm</span>(x,mu1,sigma1)<span class="sc">+</span>(<span class="dv">1</span><span class="sc">-</span>alpha)<span class="sc">*</span><span class="fu">dnorm</span>(x,mu2,sigma2)</span>
<span id="cb436-7"><a href="EST.html#cb436-7" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb436-8"><a href="EST.html#cb436-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Next write a function for the log-likelihood function. <code>R</code> is a vector based programming language so we send <code>theta</code> into the function as a vector argument.</p>
<div class="sourceCode" id="cb437"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb437-1"><a href="EST.html#cb437-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the log-likelihood function</span></span>
<span id="cb437-2"><a href="EST.html#cb437-2" aria-hidden="true" tabindex="-1"></a>loglik<span class="ot">&lt;-</span><span class="cf">function</span>(theta,x){</span>
<span id="cb437-3"><a href="EST.html#cb437-3" aria-hidden="true" tabindex="-1"></a>  alpha<span class="ot">=</span>theta[<span class="dv">1</span>]</span>
<span id="cb437-4"><a href="EST.html#cb437-4" aria-hidden="true" tabindex="-1"></a>  mu1<span class="ot">=</span>theta[<span class="dv">2</span>]</span>
<span id="cb437-5"><a href="EST.html#cb437-5" aria-hidden="true" tabindex="-1"></a>  mu2<span class="ot">=</span>theta[<span class="dv">3</span>]</span>
<span id="cb437-6"><a href="EST.html#cb437-6" aria-hidden="true" tabindex="-1"></a>  sigma1<span class="ot">=</span>theta[<span class="dv">4</span>]</span>
<span id="cb437-7"><a href="EST.html#cb437-7" aria-hidden="true" tabindex="-1"></a>  sigma2<span class="ot">=</span>theta[<span class="dv">5</span>]</span>
<span id="cb437-8"><a href="EST.html#cb437-8" aria-hidden="true" tabindex="-1"></a>  density<span class="ot">&lt;-</span><span class="cf">function</span>(x){</span>
<span id="cb437-9"><a href="EST.html#cb437-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(alpha<span class="sc">&lt;</span><span class="dv">0</span>) <span class="fu">return</span> (<span class="cn">Inf</span>)</span>
<span id="cb437-10"><a href="EST.html#cb437-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(alpha<span class="sc">&gt;</span><span class="dv">1</span>) <span class="fu">return</span> (<span class="cn">Inf</span>)</span>
<span id="cb437-11"><a href="EST.html#cb437-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(sigma1<span class="sc">&lt;</span><span class="dv">0</span>) <span class="fu">return</span> (<span class="cn">Inf</span>)</span>
<span id="cb437-12"><a href="EST.html#cb437-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span>(sigma2<span class="sc">&lt;</span><span class="dv">0</span>) <span class="fu">return</span> (<span class="cn">Inf</span>)</span>
<span id="cb437-13"><a href="EST.html#cb437-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">dmix</span>(x,alpha,mu1,mu2,sigma1,sigma2)</span>
<span id="cb437-14"><a href="EST.html#cb437-14" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb437-15"><a href="EST.html#cb437-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">sum</span>(<span class="fu">log</span>(<span class="fu">sapply</span>(x,density)))</span>
<span id="cb437-16"><a href="EST.html#cb437-16" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>Find the sample mean and standard deviation of the eruption data to use as starting points in the optimization routine.</p>
<div class="sourceCode" id="cb438"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb438-1"><a href="EST.html#cb438-1" aria-hidden="true" tabindex="-1"></a>m<span class="ot">&lt;-</span><span class="fu">mean</span>(faithful<span class="sc">$</span>eruptions)</span>
<span id="cb438-2"><a href="EST.html#cb438-2" aria-hidden="true" tabindex="-1"></a>s<span class="ot">&lt;-</span><span class="fu">sd</span>(faithful<span class="sc">$</span>eruptions)</span></code></pre></div>
<p>Use the function <code>nlmax()</code> to maximize the non-linear log-likelihood function.</p>
<div class="sourceCode" id="cb439"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb439-1"><a href="EST.html#cb439-1" aria-hidden="true" tabindex="-1"></a>mle<span class="ot">&lt;-</span><span class="fu">nlmax</span>(loglik,<span class="at">p=</span><span class="fu">c</span>(<span class="fl">0.5</span>,m<span class="dv">-1</span>,m<span class="sc">+</span><span class="dv">1</span>,s,s),<span class="at">x=</span>faithful<span class="sc">$</span>eruptions)<span class="sc">$</span>estimate</span>
<span id="cb439-2"><a href="EST.html#cb439-2" aria-hidden="true" tabindex="-1"></a>mle</span></code></pre></div>
<pre><code>## [1] 0.3484040 2.0186065 4.2733410 0.2356208 0.4370633</code></pre>
<p>So, according to our MLEs, about 34.84% of the eruptions belong to the first normal distribution (the one on the left). Furthermore the parameters of that first distribution are a mean of 2.019 and a standard deviation of 0.236. Likewise, 65.16% of the eruptions belong to the second normal with mean of 4.27 and standard deviation of 0.437.</p>
<p>Plotting the density atop the histogram shows a fairly good fit:</p>
<div class="sourceCode" id="cb441"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb441-1"><a href="EST.html#cb441-1" aria-hidden="true" tabindex="-1"></a>dmix2<span class="ot">&lt;-</span><span class="cf">function</span>(x) <span class="fu">dmix</span>(x,mle[<span class="dv">1</span>],mle[<span class="dv">2</span>],mle[<span class="dv">3</span>],mle[<span class="dv">4</span>],mle[<span class="dv">5</span>])</span>
<span id="cb441-2"><a href="EST.html#cb441-2" aria-hidden="true" tabindex="-1"></a><span class="co">#y_old&lt;-dmix2(seq(1,6,.01))</span></span>
<span id="cb441-3"><a href="EST.html#cb441-3" aria-hidden="true" tabindex="-1"></a><span class="co">#x_old&lt;-seq(1,6,.01)</span></span>
<span id="cb441-4"><a href="EST.html#cb441-4" aria-hidden="true" tabindex="-1"></a><span class="co">#dens_data&lt;-data.frame(x=x_old,y=y_old)</span></span>
<span id="cb441-5"><a href="EST.html#cb441-5" aria-hidden="true" tabindex="-1"></a><span class="co">#faithful%&gt;%</span></span>
<span id="cb441-6"><a href="EST.html#cb441-6" aria-hidden="true" tabindex="-1"></a><span class="co">#gf_histogram(~eruptions,fill=&quot;cyan&quot;,color = &quot;black&quot;) %&gt;%</span></span>
<span id="cb441-7"><a href="EST.html#cb441-7" aria-hidden="true" tabindex="-1"></a><span class="co">#  gf_curve(y~x,data=dens_data)%&gt;%</span></span>
<span id="cb441-8"><a href="EST.html#cb441-8" aria-hidden="true" tabindex="-1"></a><span class="co">#  gf_theme(theme_bw()) %&gt;%</span></span>
<span id="cb441-9"><a href="EST.html#cb441-9" aria-hidden="true" tabindex="-1"></a><span class="co">#  gf_labs(x=&quot;Duration in minutes&quot;,y=&quot;Count&quot;) </span></span>
<span id="cb441-10"><a href="EST.html#cb441-10" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(faithful<span class="sc">$</span>eruptions,<span class="at">breaks=</span><span class="dv">40</span>,<span class="at">freq=</span>F,<span class="at">main=</span><span class="st">&quot;&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Duration in minutes.&quot;</span>)</span>
<span id="cb441-11"><a href="EST.html#cb441-11" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(dmix2,<span class="at">from=</span><span class="dv">1</span>,<span class="at">to=</span><span class="dv">6</span>,<span class="at">add=</span>T)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:hist172-fig"></span>
<img src="17-Estimation-Methods_files/figure-html/hist172-fig-1.png" alt="Histogram of eruption duration with estimated mixture of normals plotted on top." width="672" />
<p class="caption">
Figure 17.4: Histogram of eruption duration with estimated mixture of normals plotted on top.
</p>
</div>
<p>This is a fairly elaborate example but it is cool. You can see the power of the method and the software.</p>
</div>
</div>
<div id="homework-problems-16" class="section level2" number="17.6">
<h2><span class="header-section-number">17.6</span> Homework Problems</h2>
<ol style="list-style-type: decimal">
<li>In the Notes, we found that if we take a sample from the uniform distribution <span class="math inline">\(\textsf{Unif}(0,\theta)\)</span>, the method of moments estimate of <span class="math inline">\(\theta\)</span> is <span class="math inline">\(\hat{\theta}_{MoM}=2\bar{x}\)</span>. Suppose our sample consists of the following values:
<span class="math display">\[
0.2 \hspace{0.4cm} 0.9 \hspace{0.4cm} 1.9 \hspace{0.4cm} 2.2 \hspace{0.4cm} 4.7 \hspace{0.4cm} 5.1
\]</span></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>What is <span class="math inline">\(\hat{\theta}_{MoM}\)</span> for this sample?<br />
</li>
<li>What is an wrong with this estimate?<br />
</li>
<li>Show that this estimator is unbiased.<br />
</li>
<li>ADVANCED: Use simulation in <code>R</code> to find out how often the method of moment estimator is less the maximum observed value, (<span class="math inline">\(\hat{\theta}_{MoM} &lt; \max x\)</span>). Report an answer for various sizes of samples. You can just pick an arbitrary value for <span class="math inline">\(\theta\)</span> when you sample from the uniform. However, the minimum must be 0.</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li><p>Let <span class="math inline">\(x_1,x_2,...,x_n\)</span> be a simple random sample from an exponentially distributed population with parameter <span class="math inline">\(\lambda\)</span>. Find <span class="math inline">\(\hat{\lambda}_{MoM}\)</span>.</p></li>
<li><p>Let <span class="math inline">\(x_1,x_2,...,x_n\)</span> be an iid random sample from an exponentially distributed population with parameter <span class="math inline">\(\lambda\)</span>. Find <span class="math inline">\(\hat{\lambda}_{MLE}\)</span>.</p></li>
<li><p>It is mathematically difficult to determine if the estimators found in questions 2 and 3 are unbiased. Since the sample mean is in the denominator; mathematically we may have to work with the joint pdf. So instead, use simulation to get an sense of whether the method of moments estimator for the exponential distribution is unbiased.</p></li>
<li><p>Find a maximum likelihood estimator for <span class="math inline">\(\theta\)</span> when <span class="math inline">\(X\sim\textsf{Unif}(0,\theta)\)</span>. Compare this to the method of moments estimator we found. Hint: Do not take the derivative of the likelihood function.</p></li>
</ol>

</div>
</div>



<h3>References</h3>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-pruim2011foundations" class="csl-entry">
Pruim, Randall J. 2011. <em>Foundations and Applications of Statistics: An Introduction Using r</em>. Vol. 13. American Mathematical Soc.
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="TRANS.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="CS3.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
