<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 18 Hypothesis Testing with the Central Limit Theorem | Computational Probability and Statistics</title>
  <meta name="description" content="This is a set of notes used for Math 377 starting in the fall of 2020 that has been compiled into a book." />
  <meta name="generator" content="bookdown 0.25 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 18 Hypothesis Testing with the Central Limit Theorem | Computational Probability and Statistics" />
  <meta property="og:type" content="book" />
  <meta property="og:image" content="/figures/Cover.png" />
  <meta property="og:description" content="This is a set of notes used for Math 377 starting in the fall of 2020 that has been compiled into a book." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 18 Hypothesis Testing with the Central Limit Theorem | Computational Probability and Statistics" />
  
  <meta name="twitter:description" content="This is a set of notes used for Math 377 starting in the fall of 2020 that has been compiled into a book." />
  <meta name="twitter:image" content="/figures/Cover.png" />

<meta name="author" content="Matthew Davis" />
<meta name="author" content="Brianna Hitt" />
<meta name="author" content="Ken Horton" />
<meta name="author" content="Bradley Warner" />


<meta name="date" content="2022-06-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="PVALUES.html"/>
<link rel="next" href="CI.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Computational Probability and Statistics</a></li>

<li class="divider"></li>
<li><a href="index.html#preface">Preface<span></span></a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>0.1</b> Who is this book for?<span></span></a></li>
<li class="chapter" data-level="0.2" data-path="index.html"><a href="index.html#book-structure-and-how-to-use-it"><i class="fa fa-check"></i><b>0.2</b> Book structure and how to use it<span></span></a></li>
<li class="chapter" data-level="0.3" data-path="index.html"><a href="index.html#prerequisites"><i class="fa fa-check"></i><b>0.3</b> Prerequisites<span></span></a></li>
<li class="chapter" data-level="0.4" data-path="index.html"><a href="index.html#packages"><i class="fa fa-check"></i><b>0.4</b> Packages<span></span></a></li>
<li class="chapter" data-level="0.5" data-path="index.html"><a href="index.html#acknowledgements"><i class="fa fa-check"></i><b>0.5</b> Acknowledgements<span></span></a></li>
<li class="chapter" data-level="0.6" data-path="index.html"><a href="index.html#file-creation-information"><i class="fa fa-check"></i><b>0.6</b> File Creation Information<span></span></a></li>
</ul></li>
<li><a href="#part-descriptive-statistical-modeling">(PART) Descriptive Statistical Modeling<span></span></a>
<ul>
<li class="chapter" data-level="0.7" data-path="index.html"><a href="index.html#objectives"><i class="fa fa-check"></i><b>0.7</b> Objectives<span></span></a></li>
<li class="chapter" data-level="0.8" data-path="index.html"><a href="index.html#introduction-to-descriptive-statistical-modeling"><i class="fa fa-check"></i><b>0.8</b> Introduction to descriptive statistical modeling<span></span></a></li>
<li class="chapter" data-level="0.9" data-path="index.html"><a href="index.html#the-data-analytic-process"><i class="fa fa-check"></i><b>0.9</b> The data analytic process<span></span></a></li>
<li class="chapter" data-level="0.10" data-path="index.html"><a href="index.html#case-study"><i class="fa fa-check"></i><b>0.10</b> Case study<span></span></a>
<ul>
<li class="chapter" data-level="0.10.1" data-path="index.html"><a href="index.html#research-question"><i class="fa fa-check"></i><b>0.10.1</b> Research question<span></span></a></li>
<li class="chapter" data-level="0.10.2" data-path="index.html"><a href="index.html#collect-the-relevant-data"><i class="fa fa-check"></i><b>0.10.2</b> Collect the relevant data<span></span></a></li>
<li class="chapter" data-level="0.10.3" data-path="index.html"><a href="index.html#import-data"><i class="fa fa-check"></i><b>0.10.3</b> Import data<span></span></a></li>
<li class="chapter" data-level="0.10.4" data-path="index.html"><a href="index.html#explore-data"><i class="fa fa-check"></i><b>0.10.4</b> Explore data<span></span></a></li>
<li class="chapter" data-level="0.10.5" data-path="index.html"><a href="index.html#visualize-the-data"><i class="fa fa-check"></i><b>0.10.5</b> Visualize the data<span></span></a></li>
<li class="chapter" data-level="0.10.6" data-path="index.html"><a href="index.html#conclusion"><i class="fa fa-check"></i><b>0.10.6</b> Conclusion<span></span></a></li>
</ul></li>
<li class="chapter" data-level="0.11" data-path="index.html"><a href="index.html#homework-problems"><i class="fa fa-check"></i><b>0.11</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="DB.html"><a href="DB.html"><i class="fa fa-check"></i><b>1</b> Data Basics<span></span></a>
<ul>
<li class="chapter" data-level="1.1" data-path="DB.html"><a href="DB.html#objectives-1"><i class="fa fa-check"></i><b>1.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="1.2" data-path="DB.html"><a href="DB.html#data-basics"><i class="fa fa-check"></i><b>1.2</b> Data basics<span></span></a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="DB.html"><a href="DB.html#observations-variables-and-data-matrices"><i class="fa fa-check"></i><b>1.2.1</b> Observations, variables, and data matrices<span></span></a></li>
<li class="chapter" data-level="1.2.2" data-path="DB.html"><a href="DB.html#types-of-variables"><i class="fa fa-check"></i><b>1.2.2</b> Types of variables<span></span></a></li>
<li class="chapter" data-level="1.2.3" data-path="DB.html"><a href="DB.html#relationships-between-variables"><i class="fa fa-check"></i><b>1.2.3</b> Relationships between variables<span></span></a></li>
<li class="chapter" data-level="1.2.4" data-path="DB.html"><a href="DB.html#creating-a-scatterplot"><i class="fa fa-check"></i><b>1.2.4</b> Creating a scatterplot<span></span></a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="DB.html"><a href="DB.html#homework-problems-1"><i class="fa fa-check"></i><b>1.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="ODCP.html"><a href="ODCP.html"><i class="fa fa-check"></i><b>2</b> Overview of Data Collection Principles<span></span></a>
<ul>
<li class="chapter" data-level="2.1" data-path="ODCP.html"><a href="ODCP.html#objectives-2"><i class="fa fa-check"></i><b>2.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="2.2" data-path="ODCP.html"><a href="ODCP.html#overview-of-data-collection-principles"><i class="fa fa-check"></i><b>2.2</b> Overview of data collection principles<span></span></a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="ODCP.html"><a href="ODCP.html#populations-and-samples"><i class="fa fa-check"></i><b>2.2.1</b> Populations and samples<span></span></a></li>
<li class="chapter" data-level="2.2.2" data-path="ODCP.html"><a href="ODCP.html#anecdotal-evidence"><i class="fa fa-check"></i><b>2.2.2</b> Anecdotal evidence<span></span></a></li>
<li class="chapter" data-level="2.2.3" data-path="ODCP.html"><a href="ODCP.html#sampling-from-a-population"><i class="fa fa-check"></i><b>2.2.3</b> Sampling from a population<span></span></a></li>
<li class="chapter" data-level="2.2.4" data-path="ODCP.html"><a href="ODCP.html#explanatory-and-response-variables"><i class="fa fa-check"></i><b>2.2.4</b> Explanatory and response variables<span></span></a></li>
<li class="chapter" data-level="2.2.5" data-path="ODCP.html"><a href="ODCP.html#introducing-observational-studies-and-experiments"><i class="fa fa-check"></i><b>2.2.5</b> Introducing observational studies and experiments<span></span></a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="ODCP.html"><a href="ODCP.html#homework-problems-2"><i class="fa fa-check"></i><b>2.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="STUDY.html"><a href="STUDY.html"><i class="fa fa-check"></i><b>3</b> Studies<span></span></a>
<ul>
<li class="chapter" data-level="3.1" data-path="STUDY.html"><a href="STUDY.html#objectives-3"><i class="fa fa-check"></i><b>3.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="3.2" data-path="STUDY.html"><a href="STUDY.html#observation-studies-sampling-strategies-and-experiments"><i class="fa fa-check"></i><b>3.2</b> Observation studies, sampling strategies, and experiments<span></span></a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="STUDY.html"><a href="STUDY.html#observational-studies"><i class="fa fa-check"></i><b>3.2.1</b> Observational studies<span></span></a></li>
<li class="chapter" data-level="3.2.2" data-path="STUDY.html"><a href="STUDY.html#three-sampling-methods"><i class="fa fa-check"></i><b>3.2.2</b> Three sampling methods<span></span></a></li>
<li class="chapter" data-level="3.2.3" data-path="STUDY.html"><a href="STUDY.html#experiments"><i class="fa fa-check"></i><b>3.2.3</b> Experiments<span></span></a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="STUDY.html"><a href="STUDY.html#homework-problems-3"><i class="fa fa-check"></i><b>3.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="NUMDATA.html"><a href="NUMDATA.html"><i class="fa fa-check"></i><b>4</b> Numerical Data<span></span></a>
<ul>
<li class="chapter" data-level="4.1" data-path="NUMDATA.html"><a href="NUMDATA.html#objectives-4"><i class="fa fa-check"></i><b>4.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="4.2" data-path="NUMDATA.html"><a href="NUMDATA.html#numerical-data"><i class="fa fa-check"></i><b>4.2</b> Numerical Data<span></span></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="NUMDATA.html"><a href="NUMDATA.html#scatterplots-for-paired-data"><i class="fa fa-check"></i><b>4.2.1</b> Scatterplots for paired data<span></span></a></li>
<li class="chapter" data-level="4.2.2" data-path="NUMDATA.html"><a href="NUMDATA.html#dot-plots-and-the-mean"><i class="fa fa-check"></i><b>4.2.2</b> Dot plots and the mean<span></span></a></li>
<li class="chapter" data-level="4.2.3" data-path="NUMDATA.html"><a href="NUMDATA.html#histograms-and-shape"><i class="fa fa-check"></i><b>4.2.3</b> Histograms and shape<span></span></a></li>
<li class="chapter" data-level="4.2.4" data-path="NUMDATA.html"><a href="NUMDATA.html#variance-and-standard-deviation"><i class="fa fa-check"></i><b>4.2.4</b> Variance and standard deviation<span></span></a></li>
<li class="chapter" data-level="4.2.5" data-path="NUMDATA.html"><a href="NUMDATA.html#box-plots-quartiles-and-the-median"><i class="fa fa-check"></i><b>4.2.5</b> Box plots, quartiles, and the median<span></span></a></li>
<li class="chapter" data-level="4.2.6" data-path="NUMDATA.html"><a href="NUMDATA.html#robust-statistics"><i class="fa fa-check"></i><b>4.2.6</b> Robust statistics<span></span></a></li>
<li class="chapter" data-level="4.2.7" data-path="NUMDATA.html"><a href="NUMDATA.html#transforming-data"><i class="fa fa-check"></i><b>4.2.7</b> Transforming data<span></span></a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="NUMDATA.html"><a href="NUMDATA.html#homework-problems-4"><i class="fa fa-check"></i><b>4.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="CATDATA.html"><a href="CATDATA.html"><i class="fa fa-check"></i><b>5</b> Categorical Data<span></span></a>
<ul>
<li class="chapter" data-level="5.1" data-path="CATDATA.html"><a href="CATDATA.html#objectives-5"><i class="fa fa-check"></i><b>5.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="5.2" data-path="CATDATA.html"><a href="CATDATA.html#categorical-data"><i class="fa fa-check"></i><b>5.2</b> Categorical data<span></span></a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="CATDATA.html"><a href="CATDATA.html#contingency-tables-and-bar-plots"><i class="fa fa-check"></i><b>5.2.1</b> Contingency tables and bar plots<span></span></a></li>
<li class="chapter" data-level="5.2.2" data-path="CATDATA.html"><a href="CATDATA.html#column-proportions"><i class="fa fa-check"></i><b>5.2.2</b> Column proportions<span></span></a></li>
<li class="chapter" data-level="5.2.3" data-path="CATDATA.html"><a href="CATDATA.html#segmented-bar-and-mosaic-plots"><i class="fa fa-check"></i><b>5.2.3</b> Segmented bar and mosaic plots<span></span></a></li>
<li class="chapter" data-level="5.2.4" data-path="CATDATA.html"><a href="CATDATA.html#the-only-pie-chart-you-will-see-in-this-course-hopefully"><i class="fa fa-check"></i><b>5.2.4</b> The only pie chart you will see in this course, hopefully<span></span></a></li>
<li class="chapter" data-level="5.2.5" data-path="CATDATA.html"><a href="CATDATA.html#comparing-numerical-data-across-groups"><i class="fa fa-check"></i><b>5.2.5</b> Comparing numerical data across groups<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="CATDATA.html"><a href="CATDATA.html#homework-problems-5"><i class="fa fa-check"></i><b>5.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li><a href="#part-probability-modeling">(PART) Probability Modeling<span></span></a>
<ul>
<li class="chapter" data-level="5.4" data-path="CATDATA.html"><a href="CATDATA.html#objectives-6"><i class="fa fa-check"></i><b>5.4</b> Objectives<span></span></a></li>
<li class="chapter" data-level="5.5" data-path="CATDATA.html"><a href="CATDATA.html#introduction-to-probability-models"><i class="fa fa-check"></i><b>5.5</b> Introduction to probability models<span></span></a></li>
<li class="chapter" data-level="5.6" data-path="CATDATA.html"><a href="CATDATA.html#probability-models"><i class="fa fa-check"></i><b>5.6</b> Probability models<span></span></a></li>
<li class="chapter" data-level="5.7" data-path="CATDATA.html"><a href="CATDATA.html#case-study-1"><i class="fa fa-check"></i><b>5.7</b> Case study<span></span></a>
<ul>
<li class="chapter" data-level="5.7.1" data-path="CATDATA.html"><a href="CATDATA.html#break-down-the-question"><i class="fa fa-check"></i><b>5.7.1</b> Break down the question<span></span></a></li>
<li class="chapter" data-level="5.7.2" data-path="CATDATA.html"><a href="CATDATA.html#simulate-computational"><i class="fa fa-check"></i><b>5.7.2</b> Simulate (computational)<span></span></a></li>
<li class="chapter" data-level="5.7.3" data-path="CATDATA.html"><a href="CATDATA.html#plotting"><i class="fa fa-check"></i><b>5.7.3</b> Plotting<span></span></a></li>
<li class="chapter" data-level="5.7.4" data-path="CATDATA.html"><a href="CATDATA.html#mathematical-solution"><i class="fa fa-check"></i><b>5.7.4</b> Mathematical solution<span></span></a></li>
<li class="chapter" data-level="5.7.5" data-path="CATDATA.html"><a href="CATDATA.html#general-solution"><i class="fa fa-check"></i><b>5.7.5</b> General solution<span></span></a></li>
<li class="chapter" data-level="5.7.6" data-path="CATDATA.html"><a href="CATDATA.html#data-science-approach"><i class="fa fa-check"></i><b>5.7.6</b> Data science approach<span></span></a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="CATDATA.html"><a href="CATDATA.html#homework-problems-6"><i class="fa fa-check"></i><b>5.8</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="PROBRULES.html"><a href="PROBRULES.html"><i class="fa fa-check"></i><b>6</b> Probability Rules<span></span></a>
<ul>
<li class="chapter" data-level="6.1" data-path="PROBRULES.html"><a href="PROBRULES.html#objectives-7"><i class="fa fa-check"></i><b>6.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="6.2" data-path="PROBRULES.html"><a href="PROBRULES.html#probability-vs-statistics"><i class="fa fa-check"></i><b>6.2</b> Probability vs Statistics<span></span></a></li>
<li class="chapter" data-level="6.3" data-path="PROBRULES.html"><a href="PROBRULES.html#basic-probability-terms"><i class="fa fa-check"></i><b>6.3</b> Basic probability terms<span></span></a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="PROBRULES.html"><a href="PROBRULES.html#sample-space"><i class="fa fa-check"></i><b>6.3.1</b> Sample space<span></span></a></li>
<li class="chapter" data-level="6.3.2" data-path="PROBRULES.html"><a href="PROBRULES.html#union-and-intersection"><i class="fa fa-check"></i><b>6.3.2</b> Union and intersection<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="PROBRULES.html"><a href="PROBRULES.html#probability"><i class="fa fa-check"></i><b>6.4</b> Probability<span></span></a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="PROBRULES.html"><a href="PROBRULES.html#probability-properties"><i class="fa fa-check"></i><b>6.4.1</b> Probability properties<span></span></a></li>
<li class="chapter" data-level="6.4.2" data-path="PROBRULES.html"><a href="PROBRULES.html#equally-likely-scenarios"><i class="fa fa-check"></i><b>6.4.2</b> Equally likely scenarios<span></span></a></li>
<li class="chapter" data-level="6.4.3" data-path="PROBRULES.html"><a href="PROBRULES.html#using-r-equally-likely-scenarios"><i class="fa fa-check"></i><b>6.4.3</b> Using <code>R</code> (Equally likely scenarios)<span></span></a></li>
<li class="chapter" data-level="6.4.4" data-path="PROBRULES.html"><a href="PROBRULES.html#note"><i class="fa fa-check"></i><b>6.4.4</b> Note<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="PROBRULES.html"><a href="PROBRULES.html#counting-rules"><i class="fa fa-check"></i><b>6.5</b> Counting rules<span></span></a>
<ul>
<li class="chapter" data-level="6.5.1" data-path="PROBRULES.html"><a href="PROBRULES.html#multiplication-rule-1-order-matters-sample-with-replacement"><i class="fa fa-check"></i><b>6.5.1</b> Multiplication rule 1: Order matters, sample with replacement<span></span></a></li>
<li class="chapter" data-level="6.5.2" data-path="PROBRULES.html"><a href="PROBRULES.html#multiplication-rule-2-permutation-order-matters-sampling-without-replacement"><i class="fa fa-check"></i><b>6.5.2</b> Multiplication rule 2 (Permutation): Order Matters, Sampling Without Replacement<span></span></a></li>
<li class="chapter" data-level="6.5.3" data-path="PROBRULES.html"><a href="PROBRULES.html#multiplication-rule-3-combination-order-does-not-matter-sampling-without-replacement"><i class="fa fa-check"></i><b>6.5.3</b> Multiplication rule 3 (Combination): Order Does Not Matter, Sampling Without Replacement<span></span></a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="PROBRULES.html"><a href="PROBRULES.html#homework-problems-7"><i class="fa fa-check"></i><b>6.6</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="CONDPROB.html"><a href="CONDPROB.html"><i class="fa fa-check"></i><b>7</b> Conditional Probability<span></span></a>
<ul>
<li class="chapter" data-level="7.1" data-path="CONDPROB.html"><a href="CONDPROB.html#objectives-8"><i class="fa fa-check"></i><b>7.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="7.2" data-path="CONDPROB.html"><a href="CONDPROB.html#conditional-probability"><i class="fa fa-check"></i><b>7.2</b> Conditional Probability<span></span></a></li>
<li class="chapter" data-level="7.3" data-path="CONDPROB.html"><a href="CONDPROB.html#independence"><i class="fa fa-check"></i><b>7.3</b> Independence<span></span></a></li>
<li class="chapter" data-level="7.4" data-path="CONDPROB.html"><a href="CONDPROB.html#bayes-rule"><i class="fa fa-check"></i><b>7.4</b> Bayes’ Rule<span></span></a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="CONDPROB.html"><a href="CONDPROB.html#approach-using-whole-numbers"><i class="fa fa-check"></i><b>7.4.1</b> Approach using whole numbers<span></span></a></li>
<li class="chapter" data-level="7.4.2" data-path="CONDPROB.html"><a href="CONDPROB.html#mathematical-approach"><i class="fa fa-check"></i><b>7.4.2</b> Mathematical approach<span></span></a></li>
<li class="chapter" data-level="7.4.3" data-path="CONDPROB.html"><a href="CONDPROB.html#simulation"><i class="fa fa-check"></i><b>7.4.3</b> Simulation<span></span></a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="CONDPROB.html"><a href="CONDPROB.html#homework-problems-8"><i class="fa fa-check"></i><b>7.5</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="RANDVAR.html"><a href="RANDVAR.html"><i class="fa fa-check"></i><b>8</b> Random Variables<span></span></a>
<ul>
<li class="chapter" data-level="8.1" data-path="RANDVAR.html"><a href="RANDVAR.html#objectives-9"><i class="fa fa-check"></i><b>8.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="8.2" data-path="RANDVAR.html"><a href="RANDVAR.html#random-variables"><i class="fa fa-check"></i><b>8.2</b> Random variables<span></span></a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="RANDVAR.html"><a href="RANDVAR.html#how-does-this-help"><i class="fa fa-check"></i><b>8.2.1</b> How does this help?<span></span></a></li>
<li class="chapter" data-level="8.2.2" data-path="RANDVAR.html"><a href="RANDVAR.html#discrete-vs-continuous"><i class="fa fa-check"></i><b>8.2.2</b> Discrete vs Continuous<span></span></a></li>
<li class="chapter" data-level="8.2.3" data-path="RANDVAR.html"><a href="RANDVAR.html#discrete-distribution-functions"><i class="fa fa-check"></i><b>8.2.3</b> Discrete distribution functions<span></span></a></li>
<li class="chapter" data-level="8.2.4" data-path="RANDVAR.html"><a href="RANDVAR.html#probability-mass-function"><i class="fa fa-check"></i><b>8.2.4</b> Probability mass function<span></span></a></li>
<li class="chapter" data-level="8.2.5" data-path="RANDVAR.html"><a href="RANDVAR.html#cumulative-distribution-function"><i class="fa fa-check"></i><b>8.2.5</b> Cumulative distribution function<span></span></a></li>
<li class="chapter" data-level="8.2.6" data-path="RANDVAR.html"><a href="RANDVAR.html#simulating-random-variables"><i class="fa fa-check"></i><b>8.2.6</b> Simulating random variables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="RANDVAR.html"><a href="RANDVAR.html#moments"><i class="fa fa-check"></i><b>8.3</b> Moments<span></span></a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="RANDVAR.html"><a href="RANDVAR.html#expectation"><i class="fa fa-check"></i><b>8.3.1</b> Expectation<span></span></a></li>
<li class="chapter" data-level="8.3.2" data-path="RANDVAR.html"><a href="RANDVAR.html#mean"><i class="fa fa-check"></i><b>8.3.2</b> Mean<span></span></a></li>
<li class="chapter" data-level="8.3.3" data-path="RANDVAR.html"><a href="RANDVAR.html#variance"><i class="fa fa-check"></i><b>8.3.3</b> Variance<span></span></a></li>
<li class="chapter" data-level="8.3.4" data-path="RANDVAR.html"><a href="RANDVAR.html#mean-and-variance-of-linear-transformations"><i class="fa fa-check"></i><b>8.3.4</b> Mean and variance of Linear Transformations<span></span></a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="RANDVAR.html"><a href="RANDVAR.html#homework-problems-9"><i class="fa fa-check"></i><b>8.4</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html"><i class="fa fa-check"></i><b>9</b> Continuous Random Variables<span></span></a>
<ul>
<li class="chapter" data-level="9.1" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#objectives-10"><i class="fa fa-check"></i><b>9.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="9.2" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#continuous-random-variables"><i class="fa fa-check"></i><b>9.2</b> Continuous random variables<span></span></a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#continuous-distribution-functions"><i class="fa fa-check"></i><b>9.2.1</b> Continuous distribution functions<span></span></a></li>
<li class="chapter" data-level="9.2.2" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#probability-density-function"><i class="fa fa-check"></i><b>9.2.2</b> Probability density function<span></span></a></li>
<li class="chapter" data-level="9.2.3" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#cumulative-distribution-function-1"><i class="fa fa-check"></i><b>9.2.3</b> Cumulative distribution function<span></span></a></li>
<li class="chapter" data-level="9.2.4" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#simulation-1"><i class="fa fa-check"></i><b>9.2.4</b> Simulation<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#moments-1"><i class="fa fa-check"></i><b>9.3</b> Moments<span></span></a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#mean-and-variance"><i class="fa fa-check"></i><b>9.3.1</b> Mean and variance<span></span></a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="CONRANDVAR.html"><a href="CONRANDVAR.html#homework-problems-10"><i class="fa fa-check"></i><b>9.4</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html"><i class="fa fa-check"></i><b>10</b> Named Discrete Distributions<span></span></a>
<ul>
<li class="chapter" data-level="10.1" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#objectives-11"><i class="fa fa-check"></i><b>10.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="10.2" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#named-distributions"><i class="fa fa-check"></i><b>10.2</b> Named distributions<span></span></a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#discrete-uniform-distribution"><i class="fa fa-check"></i><b>10.2.1</b> Discrete uniform distribution<span></span></a></li>
<li class="chapter" data-level="10.2.2" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#simulating"><i class="fa fa-check"></i><b>10.2.2</b> Simulating<span></span></a></li>
<li class="chapter" data-level="10.2.3" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#binomial-distribution"><i class="fa fa-check"></i><b>10.2.3</b> Binomial distribution<span></span></a></li>
<li class="chapter" data-level="10.2.4" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#software-functions"><i class="fa fa-check"></i><b>10.2.4</b> Software Functions<span></span></a></li>
<li class="chapter" data-level="10.2.5" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#poisson-distribution"><i class="fa fa-check"></i><b>10.2.5</b> Poisson distribution<span></span></a></li>
<li class="chapter" data-level="10.2.6" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#hypergeometric"><i class="fa fa-check"></i><b>10.2.6</b> Hypergeometric<span></span></a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="DISCRETENAMED.html"><a href="DISCRETENAMED.html#homework-problems-11"><i class="fa fa-check"></i><b>10.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html"><i class="fa fa-check"></i><b>11</b> Named Continuous Distributions<span></span></a>
<ul>
<li class="chapter" data-level="11.1" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#objectives-12"><i class="fa fa-check"></i><b>11.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="11.2" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#continuous-distributions"><i class="fa fa-check"></i><b>11.2</b> Continuous distributions<span></span></a>
<ul>
<li class="chapter" data-level="11.2.1" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#uniform-distribution"><i class="fa fa-check"></i><b>11.2.1</b> Uniform distribution<span></span></a></li>
<li class="chapter" data-level="11.2.2" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#exponential-distribution"><i class="fa fa-check"></i><b>11.2.2</b> Exponential distribution<span></span></a></li>
<li class="chapter" data-level="11.2.3" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#memoryless-property"><i class="fa fa-check"></i><b>11.2.3</b> Memoryless property<span></span></a></li>
<li class="chapter" data-level="11.2.4" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#gamma-distribution"><i class="fa fa-check"></i><b>11.2.4</b> Gamma distribution<span></span></a></li>
<li class="chapter" data-level="11.2.5" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#weibull-distribution"><i class="fa fa-check"></i><b>11.2.5</b> Weibull distribution<span></span></a></li>
<li class="chapter" data-level="11.2.6" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#normal-distribution"><i class="fa fa-check"></i><b>11.2.6</b> Normal distribution<span></span></a></li>
<li class="chapter" data-level="11.2.7" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#beta-distribution"><i class="fa fa-check"></i><b>11.2.7</b> Beta distribution<span></span></a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="CONTNNAMED.html"><a href="CONTNNAMED.html#homework-problems-12"><i class="fa fa-check"></i><b>11.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html"><i class="fa fa-check"></i><b>12</b> Multivariate Distributions<span></span></a>
<ul>
<li class="chapter" data-level="12.1" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#objectives-13"><i class="fa fa-check"></i><b>12.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="12.2" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#multivariate-distributions"><i class="fa fa-check"></i><b>12.2</b> Multivariate distributions<span></span></a></li>
<li class="chapter" data-level="12.3" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#joint-probability"><i class="fa fa-check"></i><b>12.3</b> Joint probability<span></span></a>
<ul>
<li class="chapter" data-level="12.3.1" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#discrete-random-variables"><i class="fa fa-check"></i><b>12.3.1</b> Discrete random variables<span></span></a></li>
<li class="chapter" data-level="12.3.2" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#continuous-random-variables-1"><i class="fa fa-check"></i><b>12.3.2</b> Continuous random variables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="12.4" data-path="MULTIDISTS.html"><a href="MULTIDISTS.html#homework-problems-13"><i class="fa fa-check"></i><b>12.4</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="MULTIEXP.html"><a href="MULTIEXP.html"><i class="fa fa-check"></i><b>13</b> Multivariate Expectation<span></span></a>
<ul>
<li class="chapter" data-level="13.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#objectives-14"><i class="fa fa-check"></i><b>13.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="13.2" data-path="MULTIEXP.html"><a href="MULTIEXP.html#expectation---moments"><i class="fa fa-check"></i><b>13.2</b> Expectation - moments<span></span></a>
<ul>
<li class="chapter" data-level="13.2.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#expectation-of-discrete-random-variables"><i class="fa fa-check"></i><b>13.2.1</b> Expectation of discrete random variables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.3" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exercises-to-apply-what-we-learned"><i class="fa fa-check"></i><b>13.3</b> Exercises to apply what we learned<span></span></a>
<ul>
<li class="chapter" data-level="13.3.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#ey"><i class="fa fa-check"></i><b>13.3.1</b> E(Y)<span></span></a></li>
<li class="chapter" data-level="13.3.2" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy"><i class="fa fa-check"></i><b>13.3.2</b> E(X+Y)<span></span></a></li>
<li class="chapter" data-level="13.3.3" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy-1"><i class="fa fa-check"></i><b>13.3.3</b> E(XY)<span></span></a></li>
<li class="chapter" data-level="13.3.4" data-path="MULTIEXP.html"><a href="MULTIEXP.html#e12xy1"><i class="fa fa-check"></i><b>13.3.4</b> E(1/2X+Y+1)<span></span></a></li>
<li class="chapter" data-level="13.3.5" data-path="MULTIEXP.html"><a href="MULTIEXP.html#expectation-of-continuous-random-variables"><i class="fa fa-check"></i><b>13.3.5</b> Expectation of continuous random variables<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.4" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exercises-to-apply-what-we-learned-1"><i class="fa fa-check"></i><b>13.4</b> Exercises to apply what we learned<span></span></a>
<ul>
<li class="chapter" data-level="13.4.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#ex"><i class="fa fa-check"></i><b>13.4.1</b> E(X)<span></span></a></li>
<li class="chapter" data-level="13.4.2" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy-2"><i class="fa fa-check"></i><b>13.4.2</b> E(X+Y)<span></span></a></li>
<li class="chapter" data-level="13.4.3" data-path="MULTIEXP.html"><a href="MULTIEXP.html#exy-3"><i class="fa fa-check"></i><b>13.4.3</b> E(XY)<span></span></a></li>
<li class="chapter" data-level="13.4.4" data-path="MULTIEXP.html"><a href="MULTIEXP.html#vxy"><i class="fa fa-check"></i><b>13.4.4</b> V(XY)<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.5" data-path="MULTIEXP.html"><a href="MULTIEXP.html#covariancecorrelation"><i class="fa fa-check"></i><b>13.5</b> Covariance/Correlation<span></span></a>
<ul>
<li class="chapter" data-level="13.5.1" data-path="MULTIEXP.html"><a href="MULTIEXP.html#variance-of-sums"><i class="fa fa-check"></i><b>13.5.1</b> Variance of sums<span></span></a></li>
</ul></li>
<li class="chapter" data-level="13.6" data-path="MULTIEXP.html"><a href="MULTIEXP.html#independence-1"><i class="fa fa-check"></i><b>13.6</b> Independence<span></span></a></li>
<li class="chapter" data-level="13.7" data-path="MULTIEXP.html"><a href="MULTIEXP.html#conditional-expectation"><i class="fa fa-check"></i><b>13.7</b> Conditional expectation<span></span></a></li>
<li class="chapter" data-level="13.8" data-path="MULTIEXP.html"><a href="MULTIEXP.html#homework-problems-14"><i class="fa fa-check"></i><b>13.8</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="TRANS.html"><a href="TRANS.html"><i class="fa fa-check"></i><b>14</b> Transformations<span></span></a>
<ul>
<li class="chapter" data-level="14.1" data-path="TRANS.html"><a href="TRANS.html#objectives-15"><i class="fa fa-check"></i><b>14.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="14.2" data-path="TRANS.html"><a href="TRANS.html#transformations"><i class="fa fa-check"></i><b>14.2</b> Transformations<span></span></a>
<ul>
<li class="chapter" data-level="14.2.1" data-path="TRANS.html"><a href="TRANS.html#transformations-of-discrete-random-variables"><i class="fa fa-check"></i><b>14.2.1</b> Transformations of discrete random variables<span></span></a></li>
<li class="chapter" data-level="14.2.2" data-path="TRANS.html"><a href="TRANS.html#transformations-of-continuous-random-variables"><i class="fa fa-check"></i><b>14.2.2</b> Transformations of continuous random variables<span></span></a></li>
<li class="chapter" data-level="14.2.3" data-path="TRANS.html"><a href="TRANS.html#the-cdf-method"><i class="fa fa-check"></i><b>14.2.3</b> The cdf method<span></span></a></li>
<li class="chapter" data-level="14.2.4" data-path="TRANS.html"><a href="TRANS.html#the-pdf-method"><i class="fa fa-check"></i><b>14.2.4</b> The pdf method<span></span></a></li>
<li class="chapter" data-level="14.2.5" data-path="TRANS.html"><a href="TRANS.html#simulation-2"><i class="fa fa-check"></i><b>14.2.5</b> Simulation<span></span></a></li>
<li class="chapter" data-level="14.2.6" data-path="TRANS.html"><a href="TRANS.html#multivariate-transformations"><i class="fa fa-check"></i><b>14.2.6</b> Multivariate Transformations<span></span></a></li>
</ul></li>
<li class="chapter" data-level="14.3" data-path="TRANS.html"><a href="TRANS.html#homework-problems-15"><i class="fa fa-check"></i><b>14.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="EST.html"><a href="EST.html"><i class="fa fa-check"></i><b>15</b> Estimation Methods<span></span></a>
<ul>
<li class="chapter" data-level="15.1" data-path="EST.html"><a href="EST.html#objectives-16"><i class="fa fa-check"></i><b>15.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="15.2" data-path="EST.html"><a href="EST.html#transition"><i class="fa fa-check"></i><b>15.2</b> Transition<span></span></a></li>
<li class="chapter" data-level="15.3" data-path="EST.html"><a href="EST.html#estimation"><i class="fa fa-check"></i><b>15.3</b> Estimation<span></span></a></li>
<li class="chapter" data-level="15.4" data-path="EST.html"><a href="EST.html#method-of-moments"><i class="fa fa-check"></i><b>15.4</b> Method of Moments<span></span></a></li>
<li class="chapter" data-level="15.5" data-path="EST.html"><a href="EST.html#maximum-likelihood"><i class="fa fa-check"></i><b>15.5</b> Maximum likelihood<span></span></a>
<ul>
<li class="chapter" data-level="15.5.1" data-path="EST.html"><a href="EST.html#likelihood-function"><i class="fa fa-check"></i><b>15.5.1</b> Likelihood Function<span></span></a></li>
<li class="chapter" data-level="15.5.2" data-path="EST.html"><a href="EST.html#maximum-likelihood-estimation"><i class="fa fa-check"></i><b>15.5.2</b> Maximum Likelihood Estimation<span></span></a></li>
<li class="chapter" data-level="15.5.3" data-path="EST.html"><a href="EST.html#numerical-methods"><i class="fa fa-check"></i><b>15.5.3</b> Numerical Methods<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15.6" data-path="EST.html"><a href="EST.html#homework-problems-16"><i class="fa fa-check"></i><b>15.6</b> Homework Problems<span></span></a></li>
</ul></li>
<li><a href="#part-statistical-modeling">(PART) Statistical Modeling<span></span></a>
<ul>
<li class="chapter" data-level="15.7" data-path="EST.html"><a href="EST.html#objectives-17"><i class="fa fa-check"></i><b>15.7</b> Objectives<span></span></a></li>
<li class="chapter" data-level="15.8" data-path="EST.html"><a href="EST.html#introduction"><i class="fa fa-check"></i><b>15.8</b> Introduction<span></span></a></li>
<li class="chapter" data-level="15.9" data-path="EST.html"><a href="EST.html#foundation-for-inference"><i class="fa fa-check"></i><b>15.9</b> Foundation for inference<span></span></a></li>
<li class="chapter" data-level="15.10" data-path="EST.html"><a href="EST.html#randomization-case-study-gender-discrimination"><i class="fa fa-check"></i><b>15.10</b> Randomization case study: gender discrimination<span></span></a>
<ul>
<li class="chapter" data-level="15.10.1" data-path="EST.html"><a href="EST.html#variability-within-data"><i class="fa fa-check"></i><b>15.10.1</b> Variability within data<span></span></a></li>
<li class="chapter" data-level="15.10.2" data-path="EST.html"><a href="EST.html#simulating-the-study"><i class="fa fa-check"></i><b>15.10.2</b> Simulating the study<span></span></a></li>
<li class="chapter" data-level="15.10.3" data-path="EST.html"><a href="EST.html#checking-for-independence"><i class="fa fa-check"></i><b>15.10.3</b> Checking for independence<span></span></a></li>
</ul></li>
<li class="chapter" data-level="15.11" data-path="EST.html"><a href="EST.html#homework-problems-17"><i class="fa fa-check"></i><b>15.11</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="HYPOTEST.html"><a href="HYPOTEST.html"><i class="fa fa-check"></i><b>16</b> Hypothesis Testing<span></span></a>
<ul>
<li class="chapter" data-level="16.1" data-path="HYPOTEST.html"><a href="HYPOTEST.html#objectives-18"><i class="fa fa-check"></i><b>16.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="16.2" data-path="HYPOTEST.html"><a href="HYPOTEST.html#decision-making-under-uncertainty"><i class="fa fa-check"></i><b>16.2</b> Decision making under uncertainty<span></span></a></li>
<li class="chapter" data-level="16.3" data-path="HYPOTEST.html"><a href="HYPOTEST.html#introduction-1"><i class="fa fa-check"></i><b>16.3</b> Introduction<span></span></a></li>
<li class="chapter" data-level="16.4" data-path="HYPOTEST.html"><a href="HYPOTEST.html#hypothesis-testing"><i class="fa fa-check"></i><b>16.4</b> Hypothesis testing<span></span></a>
<ul>
<li class="chapter" data-level="16.4.1" data-path="HYPOTEST.html"><a href="HYPOTEST.html#hypothesis-testing-in-the-us-court-system"><i class="fa fa-check"></i><b>16.4.1</b> Hypothesis testing in the US court system<span></span></a></li>
<li class="chapter" data-level="16.4.2" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-1--state-the-null-and-alternative-hypotheses"><i class="fa fa-check"></i><b>16.4.2</b> Step 1- State the null and alternative hypotheses<span></span></a></li>
<li class="chapter" data-level="16.4.3" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-2---compute-a-test-statistic."><i class="fa fa-check"></i><b>16.4.3</b> Step 2 - Compute a test statistic.<span></span></a></li>
<li class="chapter" data-level="16.4.4" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-3---determine-the-p-value."><i class="fa fa-check"></i><b>16.4.4</b> Step 3 - Determine the p-value.<span></span></a></li>
<li class="chapter" data-level="16.4.5" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-4---draw-a-conclusion"><i class="fa fa-check"></i><b>16.4.5</b> Step 4 - Draw a conclusion<span></span></a></li>
<li class="chapter" data-level="16.4.6" data-path="HYPOTEST.html"><a href="HYPOTEST.html#decision-errors"><i class="fa fa-check"></i><b>16.4.6</b> Decision errors<span></span></a></li>
<li class="chapter" data-level="16.4.7" data-path="HYPOTEST.html"><a href="HYPOTEST.html#choosing-a-significance-level"><i class="fa fa-check"></i><b>16.4.7</b> Choosing a significance level<span></span></a></li>
<li class="chapter" data-level="16.4.8" data-path="HYPOTEST.html"><a href="HYPOTEST.html#introducing-two-sided-hypotheses"><i class="fa fa-check"></i><b>16.4.8</b> Introducing two-sided hypotheses<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16.5" data-path="HYPOTEST.html"><a href="HYPOTEST.html#two-sided-hypothesis-test"><i class="fa fa-check"></i><b>16.5</b> Two-sided hypothesis test<span></span></a>
<ul>
<li class="chapter" data-level="16.5.1" data-path="HYPOTEST.html"><a href="HYPOTEST.html#example-cpr"><i class="fa fa-check"></i><b>16.5.1</b> Example CPR<span></span></a></li>
<li class="chapter" data-level="16.5.2" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-1--state-the-null-and-alternative-hypotheses-1"><i class="fa fa-check"></i><b>16.5.2</b> Step 1- State the null and alternative hypotheses<span></span></a></li>
<li class="chapter" data-level="16.5.3" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-2---compute-a-test-statistic.-1"><i class="fa fa-check"></i><b>16.5.3</b> Step 2 - Compute a test statistic.<span></span></a></li>
<li class="chapter" data-level="16.5.4" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-3---determine-the-p-value.-1"><i class="fa fa-check"></i><b>16.5.4</b> Step 3 - Determine the p-value.<span></span></a></li>
<li class="chapter" data-level="16.5.5" data-path="HYPOTEST.html"><a href="HYPOTEST.html#step-4---draw-a-conclusion-1"><i class="fa fa-check"></i><b>16.5.5</b> Step 4 - Draw a conclusion<span></span></a></li>
<li class="chapter" data-level="16.5.6" data-path="HYPOTEST.html"><a href="HYPOTEST.html#how-to-use-a-hypothesis-test"><i class="fa fa-check"></i><b>16.5.6</b> How to use a hypothesis test<span></span></a></li>
</ul></li>
<li class="chapter" data-level="16.6" data-path="HYPOTEST.html"><a href="HYPOTEST.html#homework-problems-18"><i class="fa fa-check"></i><b>16.6</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="PVALUES.html"><a href="PVALUES.html"><i class="fa fa-check"></i><b>17</b> Empirical p-values<span></span></a>
<ul>
<li class="chapter" data-level="17.1" data-path="PVALUES.html"><a href="PVALUES.html#objective"><i class="fa fa-check"></i><b>17.1</b> Objective<span></span></a></li>
<li class="chapter" data-level="17.2" data-path="PVALUES.html"><a href="PVALUES.html#hypothesis-testing-using-probability-models"><i class="fa fa-check"></i><b>17.2</b> Hypothesis testing using probability models<span></span></a></li>
<li class="chapter" data-level="17.3" data-path="PVALUES.html"><a href="PVALUES.html#tappers-and-listeners"><i class="fa fa-check"></i><b>17.3</b> Tappers and listeners<span></span></a>
<ul>
<li class="chapter" data-level="17.3.1" data-path="PVALUES.html"><a href="PVALUES.html#step-1--state-the-null-and-alternative-hypotheses-2"><i class="fa fa-check"></i><b>17.3.1</b> Step 1- State the null and alternative hypotheses<span></span></a></li>
<li class="chapter" data-level="17.3.2" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-2"><i class="fa fa-check"></i><b>17.3.2</b> Step 2 - Compute a test statistic.<span></span></a></li>
<li class="chapter" data-level="17.3.3" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-2"><i class="fa fa-check"></i><b>17.3.3</b> Step 3 - Determine the p-value.<span></span></a></li>
<li class="chapter" data-level="17.3.4" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-2"><i class="fa fa-check"></i><b>17.3.4</b> Step 4 - Draw a conclusion<span></span></a></li>
<li class="chapter" data-level="17.3.5" data-path="PVALUES.html"><a href="PVALUES.html#repeat-using-simulation"><i class="fa fa-check"></i><b>17.3.5</b> Repeat using simulation<span></span></a></li>
<li class="chapter" data-level="17.3.6" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-3"><i class="fa fa-check"></i><b>17.3.6</b> Step 2 - Compute a test statistic.<span></span></a></li>
<li class="chapter" data-level="17.3.7" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-3"><i class="fa fa-check"></i><b>17.3.7</b> Step 3 - Determine the p-value.<span></span></a></li>
<li class="chapter" data-level="17.3.8" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-3"><i class="fa fa-check"></i><b>17.3.8</b> Step 4 - Draw a conclusion<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17.4" data-path="PVALUES.html"><a href="PVALUES.html#cardiopulmonary-resuscitation-cpr"><i class="fa fa-check"></i><b>17.4</b> Cardiopulmonary resuscitation (CPR)<span></span></a>
<ul>
<li class="chapter" data-level="17.4.1" data-path="PVALUES.html"><a href="PVALUES.html#step-1--state-the-null-and-alternative-hypotheses-3"><i class="fa fa-check"></i><b>17.4.1</b> Step 1- State the null and alternative hypotheses<span></span></a></li>
<li class="chapter" data-level="17.4.2" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-4"><i class="fa fa-check"></i><b>17.4.2</b> Step 2 - Compute a test statistic.<span></span></a></li>
<li class="chapter" data-level="17.4.3" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-4"><i class="fa fa-check"></i><b>17.4.3</b> Step 3 - Determine the p-value.<span></span></a></li>
<li class="chapter" data-level="17.4.4" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-4"><i class="fa fa-check"></i><b>17.4.4</b> Step 4 - Draw a conclusion<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17.5" data-path="PVALUES.html"><a href="PVALUES.html#golf-balls"><i class="fa fa-check"></i><b>17.5</b> Golf Balls<span></span></a>
<ul>
<li class="chapter" data-level="17.5.1" data-path="PVALUES.html"><a href="PVALUES.html#step-1--state-the-null-and-alternative-hypotheses-4"><i class="fa fa-check"></i><b>17.5.1</b> Step 1- State the null and alternative hypotheses<span></span></a></li>
<li class="chapter" data-level="17.5.2" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-5"><i class="fa fa-check"></i><b>17.5.2</b> Step 2 - Compute a test statistic.<span></span></a></li>
<li class="chapter" data-level="17.5.3" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-5"><i class="fa fa-check"></i><b>17.5.3</b> Step 3 - Determine the p-value.<span></span></a></li>
<li class="chapter" data-level="17.5.4" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-5"><i class="fa fa-check"></i><b>17.5.4</b> Step 4 - Draw a conclusion<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17.6" data-path="PVALUES.html"><a href="PVALUES.html#repeat-with-a-different-test-statistic"><i class="fa fa-check"></i><b>17.6</b> Repeat with a different test statistic<span></span></a>
<ul>
<li class="chapter" data-level="17.6.1" data-path="PVALUES.html"><a href="PVALUES.html#step-2---compute-a-test-statistic.-6"><i class="fa fa-check"></i><b>17.6.1</b> Step 2 - Compute a test statistic.<span></span></a></li>
<li class="chapter" data-level="17.6.2" data-path="PVALUES.html"><a href="PVALUES.html#step-3---determine-the-p-value.-6"><i class="fa fa-check"></i><b>17.6.2</b> Step 3 - Determine the p-value.<span></span></a></li>
<li class="chapter" data-level="17.6.3" data-path="PVALUES.html"><a href="PVALUES.html#step-4---draw-a-conclusion-6"><i class="fa fa-check"></i><b>17.6.3</b> Step 4 - Draw a conclusion<span></span></a></li>
</ul></li>
<li class="chapter" data-level="17.7" data-path="PVALUES.html"><a href="PVALUES.html#summary"><i class="fa fa-check"></i><b>17.7</b> Summary<span></span></a></li>
<li class="chapter" data-level="17.8" data-path="PVALUES.html"><a href="PVALUES.html#homework-problems-19"><i class="fa fa-check"></i><b>17.8</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="18" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html"><i class="fa fa-check"></i><b>18</b> Hypothesis Testing with the Central Limit Theorem<span></span></a>
<ul>
<li class="chapter" data-level="18.1" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#objectives-19"><i class="fa fa-check"></i><b>18.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="18.2" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#central-limit-theorem"><i class="fa fa-check"></i><b>18.2</b> Central limit theorem<span></span></a>
<ul>
<li class="chapter" data-level="18.2.1" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#null-distribution"><i class="fa fa-check"></i><b>18.2.1</b> Null distribution<span></span></a></li>
<li class="chapter" data-level="18.2.2" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#theorem---central-limit-theorem"><i class="fa fa-check"></i><b>18.2.2</b> Theorem - central limit theorem<span></span></a></li>
<li class="chapter" data-level="18.2.3" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#simulating-data-for-the-clt"><i class="fa fa-check"></i><b>18.2.3</b> Simulating data for the CLT<span></span></a></li>
<li class="chapter" data-level="18.2.4" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#summary-of-example"><i class="fa fa-check"></i><b>18.2.4</b> Summary of example<span></span></a></li>
</ul></li>
<li class="chapter" data-level="18.3" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#other-distribution-for-estimators"><i class="fa fa-check"></i><b>18.3</b> Other distribution for estimators<span></span></a>
<ul>
<li class="chapter" data-level="18.3.1" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#students-t"><i class="fa fa-check"></i><b>18.3.1</b> Student’s t<span></span></a></li>
</ul></li>
<li class="chapter" data-level="18.4" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#hypothesis-tests-using-the-clt"><i class="fa fa-check"></i><b>18.4</b> Hypothesis tests using the CLT<span></span></a>
<ul>
<li class="chapter" data-level="18.4.1" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#body-temperature"><i class="fa fa-check"></i><b>18.4.1</b> Body temperature<span></span></a></li>
</ul></li>
<li class="chapter" data-level="18.5" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#summary-and-rules-of-thumb"><i class="fa fa-check"></i><b>18.5</b> Summary and rules of thumb<span></span></a>
<ul>
<li class="chapter" data-level="18.5.1" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#numerical-data-1"><i class="fa fa-check"></i><b>18.5.1</b> Numerical data<span></span></a></li>
<li class="chapter" data-level="18.5.2" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#binary-data"><i class="fa fa-check"></i><b>18.5.2</b> Binary data<span></span></a></li>
<li class="chapter" data-level="18.5.3" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#tappers-and-listeners-1"><i class="fa fa-check"></i><b>18.5.3</b> Tappers and listeners<span></span></a></li>
</ul></li>
<li class="chapter" data-level="18.6" data-path="HYPTESTCLT.html"><a href="HYPTESTCLT.html#homework-problems-20"><i class="fa fa-check"></i><b>18.6</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="19" data-path="CI.html"><a href="CI.html"><i class="fa fa-check"></i><b>19</b> Confidence Intervals<span></span></a>
<ul>
<li class="chapter" data-level="19.1" data-path="CI.html"><a href="CI.html#objectives-20"><i class="fa fa-check"></i><b>19.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="19.2" data-path="CI.html"><a href="CI.html#confidence-interval"><i class="fa fa-check"></i><b>19.2</b> Confidence interval<span></span></a>
<ul>
<li class="chapter" data-level="19.2.1" data-path="CI.html"><a href="CI.html#capturing-the-population-parameter"><i class="fa fa-check"></i><b>19.2.1</b> Capturing the population parameter<span></span></a></li>
<li class="chapter" data-level="19.2.2" data-path="CI.html"><a href="CI.html#constructing-a-confidence-interval"><i class="fa fa-check"></i><b>19.2.2</b> Constructing a confidence interval<span></span></a></li>
<li class="chapter" data-level="19.2.3" data-path="CI.html"><a href="CI.html#body-temperature-example"><i class="fa fa-check"></i><b>19.2.3</b> Body Temperature Example<span></span></a></li>
<li class="chapter" data-level="19.2.4" data-path="CI.html"><a href="CI.html#one-sided-intervals"><i class="fa fa-check"></i><b>19.2.4</b> One-sided Intervals<span></span></a></li>
</ul></li>
<li class="chapter" data-level="19.3" data-path="CI.html"><a href="CI.html#confidence-intervals-for-two-proportions"><i class="fa fa-check"></i><b>19.3</b> Confidence intervals for two proportions<span></span></a>
<ul>
<li class="chapter" data-level="19.3.1" data-path="CI.html"><a href="CI.html#permutation-test-for-two-proportions"><i class="fa fa-check"></i><b>19.3.1</b> Permutation test for two proportions<span></span></a></li>
<li class="chapter" data-level="19.3.2" data-path="CI.html"><a href="CI.html#hypothesis-test-for-two-proportions-using-normal-model"><i class="fa fa-check"></i><b>19.3.2</b> Hypothesis test for two proportions using normal model<span></span></a></li>
<li class="chapter" data-level="19.3.3" data-path="CI.html"><a href="CI.html#confidence-interval-for-two-proportions-using-normal-model"><i class="fa fa-check"></i><b>19.3.3</b> Confidence interval for two proportions using normal model<span></span></a></li>
</ul></li>
<li class="chapter" data-level="19.4" data-path="CI.html"><a href="CI.html#changing-the-confidence-level"><i class="fa fa-check"></i><b>19.4</b> Changing the confidence level<span></span></a></li>
<li class="chapter" data-level="19.5" data-path="CI.html"><a href="CI.html#interpreting-confidence-intervals"><i class="fa fa-check"></i><b>19.5</b> Interpreting confidence intervals<span></span></a></li>
<li class="chapter" data-level="19.6" data-path="CI.html"><a href="CI.html#homework-problems-21"><i class="fa fa-check"></i><b>19.6</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="20" data-path="BOOT.html"><a href="BOOT.html"><i class="fa fa-check"></i><b>20</b> Bootstrap<span></span></a>
<ul>
<li class="chapter" data-level="20.1" data-path="BOOT.html"><a href="BOOT.html#objectives-21"><i class="fa fa-check"></i><b>20.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="20.2" data-path="BOOT.html"><a href="BOOT.html#confidence-intervals"><i class="fa fa-check"></i><b>20.2</b> Confidence intervals<span></span></a></li>
<li class="chapter" data-level="20.3" data-path="BOOT.html"><a href="BOOT.html#bootstrapping"><i class="fa fa-check"></i><b>20.3</b> Bootstrapping<span></span></a></li>
<li class="chapter" data-level="20.4" data-path="BOOT.html"><a href="BOOT.html#bootstrap-example"><i class="fa fa-check"></i><b>20.4</b> Bootstrap example<span></span></a>
<ul>
<li class="chapter" data-level="20.4.1" data-path="BOOT.html"><a href="BOOT.html#using-traditional-mathematically-methods"><i class="fa fa-check"></i><b>20.4.1</b> Using traditional mathematically methods<span></span></a></li>
<li class="chapter" data-level="20.4.2" data-path="BOOT.html"><a href="BOOT.html#bootstrap"><i class="fa fa-check"></i><b>20.4.2</b> Bootstrap<span></span></a></li>
</ul></li>
<li class="chapter" data-level="20.5" data-path="BOOT.html"><a href="BOOT.html#non-standard-sample-statistics"><i class="fa fa-check"></i><b>20.5</b> Non-standard sample statistics<span></span></a>
<ul>
<li class="chapter" data-level="20.5.1" data-path="BOOT.html"><a href="BOOT.html#example-median"><i class="fa fa-check"></i><b>20.5.1</b> Example median<span></span></a></li>
<li class="chapter" data-level="20.5.2" data-path="BOOT.html"><a href="BOOT.html#summary-bootstrap"><i class="fa fa-check"></i><b>20.5.2</b> Summary bootstrap<span></span></a></li>
</ul></li>
<li class="chapter" data-level="20.6" data-path="BOOT.html"><a href="BOOT.html#confidence-interval-for-difference-in-means"><i class="fa fa-check"></i><b>20.6</b> Confidence interval for difference in means<span></span></a>
<ul>
<li class="chapter" data-level="20.6.1" data-path="BOOT.html"><a href="BOOT.html#health-evaluation-and-linkage-of-primary-care"><i class="fa fa-check"></i><b>20.6.1</b> Health evaluation and linkage of primary care<span></span></a></li>
<li class="chapter" data-level="20.6.2" data-path="BOOT.html"><a href="BOOT.html#permutation-test"><i class="fa fa-check"></i><b>20.6.2</b> Permutation test<span></span></a></li>
<li class="chapter" data-level="20.6.3" data-path="BOOT.html"><a href="BOOT.html#traditional-mathematical-methods"><i class="fa fa-check"></i><b>20.6.3</b> Traditional mathematical methods<span></span></a></li>
<li class="chapter" data-level="20.6.4" data-path="BOOT.html"><a href="BOOT.html#hypothesis-tests"><i class="fa fa-check"></i><b>20.6.4</b> Hypothesis tests<span></span></a></li>
<li class="chapter" data-level="20.6.5" data-path="BOOT.html"><a href="BOOT.html#confidence-intervals-1"><i class="fa fa-check"></i><b>20.6.5</b> Confidence intervals<span></span></a></li>
<li class="chapter" data-level="20.6.6" data-path="BOOT.html"><a href="BOOT.html#bootstrap-1"><i class="fa fa-check"></i><b>20.6.6</b> Bootstrap<span></span></a></li>
</ul></li>
<li class="chapter" data-level="20.7" data-path="BOOT.html"><a href="BOOT.html#frequently-asked-questions"><i class="fa fa-check"></i><b>20.7</b> Frequently asked questions<span></span></a></li>
<li class="chapter" data-level="20.8" data-path="BOOT.html"><a href="BOOT.html#homework-problems-22"><i class="fa fa-check"></i><b>20.8</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="21" data-path="ADDTESTS.html"><a href="ADDTESTS.html"><i class="fa fa-check"></i><b>21</b> Additional Hypothesis Tests<span></span></a>
<ul>
<li class="chapter" data-level="21.1" data-path="ADDTESTS.html"><a href="ADDTESTS.html#objectives-22"><i class="fa fa-check"></i><b>21.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="21.2" data-path="ADDTESTS.html"><a href="ADDTESTS.html#introduction-2"><i class="fa fa-check"></i><b>21.2</b> Introduction<span></span></a></li>
<li class="chapter" data-level="21.3" data-path="ADDTESTS.html"><a href="ADDTESTS.html#categorical-data-1"><i class="fa fa-check"></i><b>21.3</b> Categorical data<span></span></a>
<ul>
<li class="chapter" data-level="21.3.1" data-path="ADDTESTS.html"><a href="ADDTESTS.html#help-example"><i class="fa fa-check"></i><b>21.3.1</b> HELP example<span></span></a></li>
<li class="chapter" data-level="21.3.2" data-path="ADDTESTS.html"><a href="ADDTESTS.html#test-statistic"><i class="fa fa-check"></i><b>21.3.2</b> Test statistic<span></span></a></li>
<li class="chapter" data-level="21.3.3" data-path="ADDTESTS.html"><a href="ADDTESTS.html#extension-to-larger-tables"><i class="fa fa-check"></i><b>21.3.3</b> Extension to larger tables<span></span></a></li>
<li class="chapter" data-level="21.3.4" data-path="ADDTESTS.html"><a href="ADDTESTS.html#permutation-test-1"><i class="fa fa-check"></i><b>21.3.4</b> Permutation test<span></span></a></li>
<li class="chapter" data-level="21.3.5" data-path="ADDTESTS.html"><a href="ADDTESTS.html#chi-squared-test"><i class="fa fa-check"></i><b>21.3.5</b> Chi-squared test<span></span></a></li>
</ul></li>
<li class="chapter" data-level="21.4" data-path="ADDTESTS.html"><a href="ADDTESTS.html#numerical-data-2"><i class="fa fa-check"></i><b>21.4</b> Numerical data<span></span></a>
<ul>
<li class="chapter" data-level="21.4.1" data-path="ADDTESTS.html"><a href="ADDTESTS.html#mlb-batting-performance"><i class="fa fa-check"></i><b>21.4.1</b> MLB batting performance<span></span></a></li>
<li class="chapter" data-level="21.4.2" data-path="ADDTESTS.html"><a href="ADDTESTS.html#analysis-of-variance-anova-and-the-f-test"><i class="fa fa-check"></i><b>21.4.2</b> Analysis of variance (ANOVA) and the F test<span></span></a></li>
</ul></li>
<li class="chapter" data-level="21.5" data-path="ADDTESTS.html"><a href="ADDTESTS.html#homework-problems-23"><i class="fa fa-check"></i><b>21.5</b> Homework Problems<span></span></a></li>
</ul></li>
<li><a href="#part-predictive-statistical-modeling">(PART) Predictive Statistical Modeling<span></span></a>
<ul>
<li class="chapter" data-level="21.6" data-path="ADDTESTS.html"><a href="ADDTESTS.html#objectives-23"><i class="fa fa-check"></i><b>21.6</b> Objectives<span></span></a></li>
<li class="chapter" data-level="21.7" data-path="ADDTESTS.html"><a href="ADDTESTS.html#introduction-to-linear-regression"><i class="fa fa-check"></i><b>21.7</b> Introduction to linear regression<span></span></a></li>
<li class="chapter" data-level="21.8" data-path="ADDTESTS.html"><a href="ADDTESTS.html#case-study-introduction"><i class="fa fa-check"></i><b>21.8</b> Case study introduction<span></span></a>
<ul>
<li class="chapter" data-level="21.8.1" data-path="ADDTESTS.html"><a href="ADDTESTS.html#load-packages"><i class="fa fa-check"></i><b>21.8.1</b> Load packages<span></span></a></li>
<li class="chapter" data-level="21.8.2" data-path="ADDTESTS.html"><a href="ADDTESTS.html#the-data-and-exploratory-analysis"><i class="fa fa-check"></i><b>21.8.2</b> The data and exploratory analysis<span></span></a></li>
</ul></li>
<li class="chapter" data-level="21.9" data-path="ADDTESTS.html"><a href="ADDTESTS.html#sum-of-squared-residuals"><i class="fa fa-check"></i><b>21.9</b> Sum of squared residuals<span></span></a></li>
<li class="chapter" data-level="21.10" data-path="ADDTESTS.html"><a href="ADDTESTS.html#the-linear-model"><i class="fa fa-check"></i><b>21.10</b> The linear model<span></span></a></li>
<li class="chapter" data-level="21.11" data-path="ADDTESTS.html"><a href="ADDTESTS.html#prediction-and-prediction-errors"><i class="fa fa-check"></i><b>21.11</b> Prediction and prediction errors<span></span></a></li>
<li class="chapter" data-level="21.12" data-path="ADDTESTS.html"><a href="ADDTESTS.html#model-diagnostics"><i class="fa fa-check"></i><b>21.12</b> Model diagnostics<span></span></a></li>
<li class="chapter" data-level="21.13" data-path="ADDTESTS.html"><a href="ADDTESTS.html#brief-summary"><i class="fa fa-check"></i><b>21.13</b> Brief summary<span></span></a></li>
<li class="chapter" data-level="21.14" data-path="ADDTESTS.html"><a href="ADDTESTS.html#homework-problems-24"><i class="fa fa-check"></i><b>21.14</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="22" data-path="LRBASICS.html"><a href="LRBASICS.html"><i class="fa fa-check"></i><b>22</b> Linear Regression Basics<span></span></a>
<ul>
<li class="chapter" data-level="22.1" data-path="LRBASICS.html"><a href="LRBASICS.html#objectives-24"><i class="fa fa-check"></i><b>22.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="22.2" data-path="LRBASICS.html"><a href="LRBASICS.html#linear-regression-models"><i class="fa fa-check"></i><b>22.2</b> Linear regression models<span></span></a>
<ul>
<li class="chapter" data-level="22.2.1" data-path="LRBASICS.html"><a href="LRBASICS.html#estimation-1"><i class="fa fa-check"></i><b>22.2.1</b> Estimation<span></span></a></li>
<li class="chapter" data-level="22.2.2" data-path="LRBASICS.html"><a href="LRBASICS.html#possum-example"><i class="fa fa-check"></i><b>22.2.2</b> Possum example<span></span></a></li>
<li class="chapter" data-level="22.2.3" data-path="LRBASICS.html"><a href="LRBASICS.html#interpretation"><i class="fa fa-check"></i><b>22.2.3</b> Interpretation<span></span></a></li>
<li class="chapter" data-level="22.2.4" data-path="LRBASICS.html"><a href="LRBASICS.html#extrapolation-is-dangerous"><i class="fa fa-check"></i><b>22.2.4</b> Extrapolation is dangerous<span></span></a></li>
<li class="chapter" data-level="22.2.5" data-path="LRBASICS.html"><a href="LRBASICS.html#reading-computer-output"><i class="fa fa-check"></i><b>22.2.5</b> Reading computer output<span></span></a></li>
<li class="chapter" data-level="22.2.6" data-path="LRBASICS.html"><a href="LRBASICS.html#assumptions-1"><i class="fa fa-check"></i><b>22.2.6</b> Assumptions<span></span></a></li>
<li class="chapter" data-level="22.2.7" data-path="LRBASICS.html"><a href="LRBASICS.html#residual-plots"><i class="fa fa-check"></i><b>22.2.7</b> Residual plots<span></span></a></li>
<li class="chapter" data-level="22.2.8" data-path="LRBASICS.html"><a href="LRBASICS.html#summary-1"><i class="fa fa-check"></i><b>22.2.8</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="22.3" data-path="LRBASICS.html"><a href="LRBASICS.html#homework-problems-25"><i class="fa fa-check"></i><b>22.3</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="23" data-path="LRINF.html"><a href="LRINF.html"><i class="fa fa-check"></i><b>23</b> Linear Regression Inference<span></span></a>
<ul>
<li class="chapter" data-level="23.1" data-path="LRINF.html"><a href="LRINF.html#objectives-25"><i class="fa fa-check"></i><b>23.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="23.2" data-path="LRINF.html"><a href="LRINF.html#introduction-3"><i class="fa fa-check"></i><b>23.2</b> Introduction<span></span></a>
<ul>
<li class="chapter" data-level="23.2.1" data-path="LRINF.html"><a href="LRINF.html#regression"><i class="fa fa-check"></i><b>23.2.1</b> Regression<span></span></a></li>
<li class="chapter" data-level="23.2.2" data-path="LRINF.html"><a href="LRINF.html#review-of-assumptions"><i class="fa fa-check"></i><b>23.2.2</b> Review of assumptions<span></span></a></li>
<li class="chapter" data-level="23.2.3" data-path="LRINF.html"><a href="LRINF.html#distribution-of-our-estimators"><i class="fa fa-check"></i><b>23.2.3</b> Distribution of our estimators<span></span></a></li>
</ul></li>
<li class="chapter" data-level="23.3" data-path="LRINF.html"><a href="LRINF.html#inference"><i class="fa fa-check"></i><b>23.3</b> Inference<span></span></a>
<ul>
<li class="chapter" data-level="23.3.1" data-path="LRINF.html"><a href="LRINF.html#starbucks"><i class="fa fa-check"></i><b>23.3.1</b> Starbucks<span></span></a></li>
</ul></li>
<li class="chapter" data-level="23.4" data-path="LRINF.html"><a href="LRINF.html#inference-on-predictions"><i class="fa fa-check"></i><b>23.4</b> Inference on Predictions<span></span></a>
<ul>
<li class="chapter" data-level="23.4.1" data-path="LRINF.html"><a href="LRINF.html#starbucks-1"><i class="fa fa-check"></i><b>23.4.1</b> Starbucks<span></span></a></li>
<li class="chapter" data-level="23.4.2" data-path="LRINF.html"><a href="LRINF.html#summary-2"><i class="fa fa-check"></i><b>23.4.2</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="23.5" data-path="LRINF.html"><a href="LRINF.html#homework-problems-26"><i class="fa fa-check"></i><b>23.5</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="24" data-path="LRDIAG.html"><a href="LRDIAG.html"><i class="fa fa-check"></i><b>24</b> Regression Diagnostics<span></span></a>
<ul>
<li class="chapter" data-level="24.1" data-path="LRDIAG.html"><a href="LRDIAG.html#objectives-26"><i class="fa fa-check"></i><b>24.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="24.2" data-path="LRDIAG.html"><a href="LRDIAG.html#introduction-4"><i class="fa fa-check"></i><b>24.2</b> Introduction<span></span></a></li>
<li class="chapter" data-level="24.3" data-path="LRDIAG.html"><a href="LRDIAG.html#assessing-our-model---understanding-the-output-from-lm"><i class="fa fa-check"></i><b>24.3</b> Assessing our model - understanding the output from <code>lm</code><span></span></a>
<ul>
<li class="chapter" data-level="24.3.1" data-path="LRDIAG.html"><a href="LRDIAG.html#residual-standard-error"><i class="fa fa-check"></i><b>24.3.1</b> Residual Standard Error<span></span></a></li>
<li class="chapter" data-level="24.3.2" data-path="LRDIAG.html"><a href="LRDIAG.html#r-squared"><i class="fa fa-check"></i><b>24.3.2</b> R-squared<span></span></a></li>
<li class="chapter" data-level="24.3.3" data-path="LRDIAG.html"><a href="LRDIAG.html#f-statistic"><i class="fa fa-check"></i><b>24.3.3</b> F-Statistic<span></span></a></li>
</ul></li>
<li class="chapter" data-level="24.4" data-path="LRDIAG.html"><a href="LRDIAG.html#regression-diagnostics"><i class="fa fa-check"></i><b>24.4</b> Regression diagnostics<span></span></a>
<ul>
<li class="chapter" data-level="24.4.1" data-path="LRDIAG.html"><a href="LRDIAG.html#residual-plots-1"><i class="fa fa-check"></i><b>24.4.1</b> Residual plots<span></span></a></li>
<li class="chapter" data-level="24.4.2" data-path="LRDIAG.html"><a href="LRDIAG.html#residuals-vs-fitted"><i class="fa fa-check"></i><b>24.4.2</b> Residuals vs Fitted<span></span></a></li>
<li class="chapter" data-level="24.4.3" data-path="LRDIAG.html"><a href="LRDIAG.html#normal-q-q-plot"><i class="fa fa-check"></i><b>24.4.3</b> Normal Q-Q Plot<span></span></a></li>
<li class="chapter" data-level="24.4.4" data-path="LRDIAG.html"><a href="LRDIAG.html#scale-location-plot"><i class="fa fa-check"></i><b>24.4.4</b> Scale-Location Plot<span></span></a></li>
</ul></li>
<li class="chapter" data-level="24.5" data-path="LRDIAG.html"><a href="LRDIAG.html#outliers-and-leverage"><i class="fa fa-check"></i><b>24.5</b> Outliers and leverage<span></span></a>
<ul>
<li class="chapter" data-level="24.5.1" data-path="LRDIAG.html"><a href="LRDIAG.html#residuals-vs-leverage-plot"><i class="fa fa-check"></i><b>24.5.1</b> Residuals vs Leverage Plot<span></span></a></li>
<li class="chapter" data-level="24.5.2" data-path="LRDIAG.html"><a href="LRDIAG.html#what-if-our-assumptions-are-violated"><i class="fa fa-check"></i><b>24.5.2</b> What If Our Assumptions Are Violated<span></span></a></li>
</ul></li>
<li class="chapter" data-level="24.6" data-path="LRDIAG.html"><a href="LRDIAG.html#homework-problems-27"><i class="fa fa-check"></i><b>24.6</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="25" data-path="LRSIM.html"><a href="LRSIM.html"><i class="fa fa-check"></i><b>25</b> Simulation Based Linear Regression<span></span></a>
<ul>
<li class="chapter" data-level="25.1" data-path="LRSIM.html"><a href="LRSIM.html#objectives-27"><i class="fa fa-check"></i><b>25.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="25.2" data-path="LRSIM.html"><a href="LRSIM.html#introduction-5"><i class="fa fa-check"></i><b>25.2</b> Introduction<span></span></a></li>
<li class="chapter" data-level="25.3" data-path="LRSIM.html"><a href="LRSIM.html#confidence-intervals-for-parameters"><i class="fa fa-check"></i><b>25.3</b> Confidence intervals for parameters<span></span></a>
<ul>
<li class="chapter" data-level="25.3.1" data-path="LRSIM.html"><a href="LRSIM.html#resampling"><i class="fa fa-check"></i><b>25.3.1</b> Resampling<span></span></a></li>
<li class="chapter" data-level="25.3.2" data-path="LRSIM.html"><a href="LRSIM.html#resample-residuals"><i class="fa fa-check"></i><b>25.3.2</b> Resample residuals<span></span></a></li>
</ul></li>
<li class="chapter" data-level="25.4" data-path="LRSIM.html"><a href="LRSIM.html#confidence-intervals-for-prediction"><i class="fa fa-check"></i><b>25.4</b> Confidence intervals for prediction<span></span></a>
<ul>
<li class="chapter" data-level="25.4.1" data-path="LRSIM.html"><a href="LRSIM.html#prediction-interval"><i class="fa fa-check"></i><b>25.4.1</b> Prediction interval<span></span></a></li>
</ul></li>
<li class="chapter" data-level="25.5" data-path="LRSIM.html"><a href="LRSIM.html#categorical-predictor"><i class="fa fa-check"></i><b>25.5</b> Categorical predictor<span></span></a>
<ul>
<li class="chapter" data-level="25.5.1" data-path="LRSIM.html"><a href="LRSIM.html#lending-club"><i class="fa fa-check"></i><b>25.5.1</b> Lending Club<span></span></a></li>
<li class="chapter" data-level="25.5.2" data-path="LRSIM.html"><a href="LRSIM.html#bootstrap-2"><i class="fa fa-check"></i><b>25.5.2</b> Bootstrap<span></span></a></li>
<li class="chapter" data-level="25.5.3" data-path="LRSIM.html"><a href="LRSIM.html#anova-table"><i class="fa fa-check"></i><b>25.5.3</b> ANOVA Table<span></span></a></li>
<li class="chapter" data-level="25.5.4" data-path="LRSIM.html"><a href="LRSIM.html#pairwise-comparisons"><i class="fa fa-check"></i><b>25.5.4</b> Pairwise Comparisons<span></span></a></li>
</ul></li>
<li class="chapter" data-level="25.6" data-path="LRSIM.html"><a href="LRSIM.html#assumptions-2"><i class="fa fa-check"></i><b>25.6</b> Assumptions<span></span></a></li>
<li class="chapter" data-level="25.7" data-path="LRSIM.html"><a href="LRSIM.html#homework-problems-28"><i class="fa fa-check"></i><b>25.7</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="26" data-path="LRMULTI.html"><a href="LRMULTI.html"><i class="fa fa-check"></i><b>26</b> Multiple Linear Regression<span></span></a>
<ul>
<li class="chapter" data-level="26.1" data-path="LRMULTI.html"><a href="LRMULTI.html#objectives-28"><i class="fa fa-check"></i><b>26.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="26.2" data-path="LRMULTI.html"><a href="LRMULTI.html#introduction-to-multiple-regression"><i class="fa fa-check"></i><b>26.2</b> Introduction to multiple regression<span></span></a></li>
<li class="chapter" data-level="26.3" data-path="LRMULTI.html"><a href="LRMULTI.html#multiple-regression"><i class="fa fa-check"></i><b>26.3</b> Multiple regression<span></span></a>
<ul>
<li class="chapter" data-level="26.3.1" data-path="LRMULTI.html"><a href="LRMULTI.html#a-single-variable-model-for-the-mario-kart-data"><i class="fa fa-check"></i><b>26.3.1</b> A single-variable model for the Mario Kart data<span></span></a></li>
<li class="chapter" data-level="26.3.2" data-path="LRMULTI.html"><a href="LRMULTI.html#including-and-assessing-many-variables-in-a-model"><i class="fa fa-check"></i><b>26.3.2</b> Including and assessing many variables in a model<span></span></a></li>
<li class="chapter" data-level="26.3.3" data-path="LRMULTI.html"><a href="LRMULTI.html#inference-1"><i class="fa fa-check"></i><b>26.3.3</b> Inference<span></span></a></li>
<li class="chapter" data-level="26.3.4" data-path="LRMULTI.html"><a href="LRMULTI.html#adjusted-r2-as-a-better-estimate-of-explained-variance"><i class="fa fa-check"></i><b>26.3.4</b> Adjusted <span class="math inline">\(R^2\)</span> as a better estimate of explained variance<span></span></a></li>
<li class="chapter" data-level="26.3.5" data-path="LRMULTI.html"><a href="LRMULTI.html#reduced-model"><i class="fa fa-check"></i><b>26.3.5</b> Reduced model<span></span></a></li>
<li class="chapter" data-level="26.3.6" data-path="LRMULTI.html"><a href="LRMULTI.html#confidence-and-prediction-intervals"><i class="fa fa-check"></i><b>26.3.6</b> Confidence and prediction intervals<span></span></a></li>
<li class="chapter" data-level="26.3.7" data-path="LRMULTI.html"><a href="LRMULTI.html#diagnostics"><i class="fa fa-check"></i><b>26.3.7</b> Diagnostics<span></span></a></li>
</ul></li>
<li class="chapter" data-level="26.4" data-path="LRMULTI.html"><a href="LRMULTI.html#interaction-and-higher-order-terms"><i class="fa fa-check"></i><b>26.4</b> Interaction and Higher Order Terms<span></span></a>
<ul>
<li class="chapter" data-level="26.4.1" data-path="LRMULTI.html"><a href="LRMULTI.html#summary-3"><i class="fa fa-check"></i><b>26.4.1</b> Summary<span></span></a></li>
</ul></li>
<li class="chapter" data-level="26.5" data-path="LRMULTI.html"><a href="LRMULTI.html#homework-problems-29"><i class="fa fa-check"></i><b>26.5</b> Homework Problems<span></span></a></li>
</ul></li>
<li class="chapter" data-level="27" data-path="LOGREG.html"><a href="LOGREG.html"><i class="fa fa-check"></i><b>27</b> Logistic Regression<span></span></a>
<ul>
<li class="chapter" data-level="27.1" data-path="LOGREG.html"><a href="LOGREG.html#objectives-29"><i class="fa fa-check"></i><b>27.1</b> Objectives<span></span></a></li>
<li class="chapter" data-level="27.2" data-path="LOGREG.html"><a href="LOGREG.html#logistic-regression-introduction"><i class="fa fa-check"></i><b>27.2</b> Logistic regression introduction<span></span></a>
<ul>
<li class="chapter" data-level="27.2.1" data-path="LOGREG.html"><a href="LOGREG.html#mario-kart-data"><i class="fa fa-check"></i><b>27.2.1</b> Mario Kart data<span></span></a></li>
<li class="chapter" data-level="27.2.2" data-path="LOGREG.html"><a href="LOGREG.html#analyzing-contingency-table"><i class="fa fa-check"></i><b>27.2.2</b> Analyzing contingency table<span></span></a></li>
<li class="chapter" data-level="27.2.3" data-path="LOGREG.html"><a href="LOGREG.html#modeling-the-probability-of-an-event"><i class="fa fa-check"></i><b>27.2.3</b> Modeling the probability of an event<span></span></a></li>
<li class="chapter" data-level="27.2.4" data-path="LOGREG.html"><a href="LOGREG.html#first-model---intercept-only"><i class="fa fa-check"></i><b>27.2.4</b> First model - intercept only<span></span></a></li>
<li class="chapter" data-level="27.2.5" data-path="LOGREG.html"><a href="LOGREG.html#second-model---stock_photo"><i class="fa fa-check"></i><b>27.2.5</b> Second model - stock_photo<span></span></a></li>
<li class="chapter" data-level="27.2.6" data-path="LOGREG.html"><a href="LOGREG.html#interpreting-the-coefficients"><i class="fa fa-check"></i><b>27.2.6</b> Interpreting the coefficients<span></span></a></li>
<li class="chapter" data-level="27.2.7" data-path="LOGREG.html"><a href="LOGREG.html#comparing-models"><i class="fa fa-check"></i><b>27.2.7</b> Comparing models<span></span></a></li>
</ul></li>
<li class="chapter" data-level="27.3" data-path="LOGREG.html"><a href="LOGREG.html#multiple-logistic-regression"><i class="fa fa-check"></i><b>27.3</b> Multiple logistic regression<span></span></a>
<ul>
<li class="chapter" data-level="27.3.1" data-path="LOGREG.html"><a href="LOGREG.html#diagnostics-for-logistic-regression"><i class="fa fa-check"></i><b>27.3.1</b> Diagnostics for logistic regression<span></span></a></li>
</ul></li>
<li class="chapter" data-level="27.4" data-path="LOGREG.html"><a href="LOGREG.html#confidence-intervals-2"><i class="fa fa-check"></i><b>27.4</b> Confidence intervals<span></span></a>
<ul>
<li class="chapter" data-level="27.4.1" data-path="LOGREG.html"><a href="LOGREG.html#confidence-intervals-for-a-parameter"><i class="fa fa-check"></i><b>27.4.1</b> Confidence intervals for a parameter<span></span></a></li>
<li class="chapter" data-level="27.4.2" data-path="LOGREG.html"><a href="LOGREG.html#confidence-intervals-for-probability-of-success"><i class="fa fa-check"></i><b>27.4.2</b> Confidence intervals for probability of success<span></span></a></li>
</ul></li>
<li class="chapter" data-level="27.5" data-path="LOGREG.html"><a href="LOGREG.html#summary-4"><i class="fa fa-check"></i><b>27.5</b> Summary<span></span></a></li>
<li class="chapter" data-level="27.6" data-path="LOGREG.html"><a href="LOGREG.html#homework-problems-30"><i class="fa fa-check"></i><b>27.6</b> Homework Problems<span></span></a></li>
</ul></li>
<li><a href="references.html#references">References<span></span></a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Computational Probability and Statistics</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="HYPTESTCLT" class="section level1 hasAnchor" number="18">
<h1><span class="header-section-number">Chapter 18</span> Hypothesis Testing with the Central Limit Theorem<a href="HYPTESTCLT.html#HYPTESTCLT" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="objectives-19" class="section level2 hasAnchor" number="18.1">
<h2><span class="header-section-number">18.1</span> Objectives<a href="HYPTESTCLT.html#objectives-19" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Explain the central limit theorem and when you can use it for inference.<br />
</li>
<li>Conduct hypothesis tests of a single mean and proportion using the CLT and <code>R</code>.<br />
</li>
<li>Explain how the chi-squared and <span class="math inline">\(t\)</span> distributions relate to the normal distribution, where we use them, and describe the impact on the shape of the distribution when the parameters are changed.</li>
</ol>
</div>
<div id="central-limit-theorem" class="section level2 hasAnchor" number="18.2">
<h2><span class="header-section-number">18.2</span> Central limit theorem<a href="HYPTESTCLT.html#central-limit-theorem" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We’ve encountered several research questions and associated hypothesis tests so far in this block of material. While they differ in the settings, in their outcomes, and also in the technique we’ve used to analyze the data, many of them had something in common: for a certain class of test statistics, the general shape of the sampling distribution under the null hypothesis looks like a normal distribution.</p>
<div id="null-distribution" class="section level3 hasAnchor" number="18.2.1">
<h3><span class="header-section-number">18.2.1</span> Null distribution<a href="HYPTESTCLT.html#null-distribution" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>As a reminder, in the tapping and listening problem, we used the proportion of correct answers as our test statistic. Under the null hypothesis we assumed the probability of success was 0.5. The estimate of the sampling distribution of our test statistic is shown in Figure <a href="HYPTESTCLT.html#fig:dens211-fig">18.1</a>.</p>
<div class="figure"><span style="display:block;" id="fig:dens211-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/dens211-fig-1.png" alt="Sampling distribution of the proportion." width="672" />
<p class="caption">
Figure 18.1: Sampling distribution of the proportion.
</p>
</div>
<blockquote>
<p><strong>Exercise</strong>:<br />
Describe the shape of the distribution and note anything that you find interesting.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
</blockquote>
<p>In the Figure <a href="HYPTESTCLT.html#fig:dens212-fig">18.2</a> we have overlayed a normal distribution on the histogram of the estimated sampling distribution. This allows us to visually compare a normal probability density curve with the empirical distribution of the sampling distribution.</p>
<div class="figure"><span style="display:block;" id="fig:dens212-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/dens212-fig-1.png" alt="Sampling distribution of the sample proportion." width="672" />
<p class="caption">
Figure 18.2: Sampling distribution of the sample proportion.
</p>
</div>
<p>This similarity between the empirical and theoretical distributions is not a coincidence, but rather, is guaranteed by mathematical theory. This chapter will be a little more notation and algebra intensive than the previous chapters. However, the goal is to develop a tool that will help us find sampling distributions for test statistics and thus find p-values. This chapter is classical statistics often taught in AP high school classes as well as many introductory undergraduate statistics courses. Remember that before the advances of modern computing, these mathematical solutions were all that was available.</p>
</div>
<div id="theorem---central-limit-theorem" class="section level3 hasAnchor" number="18.2.2">
<h3><span class="header-section-number">18.2.2</span> Theorem - central limit theorem<a href="HYPTESTCLT.html#theorem---central-limit-theorem" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Theorem: Let <span class="math inline">\(X_1,X_2,...,X_n\)</span> be a sequence of iid, independent and identically distributed, random variables from a distribution with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma&lt;\infty\)</span>. Then,
<span class="math display">\[
\bar{X} \overset{approx}{\sim}\textsf{Norm}\left(\mu,{\sigma\over\sqrt{n}}\right)
\]</span></p>
<p>There is a lot going on in this theorem. First notice we are drawing independent samples from the same parent population. The central limit theorem (CLT) does not specify the form of this parent distribution, only that it has a finite variance. Then if we form a new random variable that involves the sum of the individual random variables, in this case the sample mean, the distribution of the new random variable is approximately normal. In the case of the sample mean, the expected value is the same mean as the parent population and the variance is the variance of the parent population divided by the sample size. Let’s summarize these ideas.</p>
<ol style="list-style-type: decimal">
<li>The process of creating a new random variable from the sum of independent identically distributed random variables is approximately normal.</li>
<li>The approximation to a normal distribution improves with sample size <span class="math inline">\(n\)</span>.</li>
<li>The mean and variance of the sampling distribution are a function of the mean and variance of the parent population, the sample size <span class="math inline">\(n\)</span>, and the form of the new random variable.</li>
</ol>
<p>If you go back and review examples, exercises, and homework problems from the previous lessons on hypothesis testing, you will see that we get symmetric normal “looking” distributions when we created test statistics that involved the process of summing. The example of a skewed distribution was the golf ball example where our test statistic was the difference of the max and min. It is hard to overstate the historical importance of this theorem to the field of inferential statistics and science in general.</p>
<p>To get an understanding and some intuition of the central limit theorem, let’s simulate some data and evaluate.</p>
</div>
<div id="simulating-data-for-the-clt" class="section level3 hasAnchor" number="18.2.3">
<h3><span class="header-section-number">18.2.3</span> Simulating data for the CLT<a href="HYPTESTCLT.html#simulating-data-for-the-clt" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For this section, we are going to use an artificial example where we know the population distribution and parameters. We will repeat sampling from this many times and plot the distribution of the summary statistic of interest, the sample mean, to demonstrate the CLT. This is purely an educational thought experiment to give ourselves confidence about the validity of the CLT.</p>
<p>Suppose there is an upcoming election in Colorado and Proposition A is on the ballot. Now suppose that 65% of Colorado voters support Proposition A. We poll a random sample of <span class="math inline">\(n\)</span> Colorado voters. Prior to conducting the sample, we can think about the sample as a sequence of iid random variables from the binomial distribution with one trial in each run and a probability of success (support for the measure) of 0.65. In other words, each random variable will take a value of 1 (support) or 0 (oppose). Figure <a href="HYPTESTCLT.html#fig:dens213-fig">18.3</a> is a plot of the pmf of the parent distribution (<span class="math inline">\(\textsf{Binom}(1,0.65)\)</span>):</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="HYPTESTCLT.html#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_dist</span>(<span class="st">&quot;binom&quot;</span>,<span class="at">size=</span><span class="dv">1</span>,<span class="at">prob=</span>.<span class="dv">65</span>,<span class="at">plot_size=</span><span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb1-2"><a href="HYPTESTCLT.html#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_classic</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb1-3"><a href="HYPTESTCLT.html#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb1-4"><a href="HYPTESTCLT.html#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_labs</span>(<span class="at">y=</span><span class="st">&quot;Probability&quot;</span>,<span class="at">x=</span><span class="st">&quot;X&quot;</span>)</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:dens213-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/dens213-fig-1.png" alt="Binomial pmf with 1 trial and probability of succes of 0.65." width="672" />
<p class="caption">
Figure 18.3: Binomial pmf with 1 trial and probability of succes of 0.65.
</p>
</div>
<p>This is clearly not normal, it is in fact discrete. The mean of <span class="math inline">\(X\)</span> is 0.65 and the standard deviation is <span class="math inline">\(\sqrt{0.65(1-0.65)}=0.477\)</span>.</p>
<p>In our first simulation, we let the sample size be ten, <span class="math inline">\(n=10\)</span>. This is typically too small for the CLT to apply but we will still use it as a starting point. In the code box below, we will obtain a sample of size 10 from this distribution and record the observed mean <span class="math inline">\(\bar{x}\)</span>, which is our method of moments estimate of the probability of success. We will repeat this 10,000 times to get an empirical distribution of <span class="math inline">\(\bar{X}\)</span>. (Note that <span class="math inline">\(\bar{X}\)</span> is a mean of 1s and 0s and can be thought of as a proportion of voters in the sample that support the measure. Often, population proportion is denoted as <span class="math inline">\(\pi\)</span> and the sample proportion is denoted as <span class="math inline">\(\hat{\pi}\)</span>.)</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="HYPTESTCLT.html#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">5501</span>)</span>
<span id="cb2-2"><a href="HYPTESTCLT.html#cb2-2" aria-hidden="true" tabindex="-1"></a>results<span class="ot">&lt;-</span><span class="fu">do</span>(<span class="dv">10000</span>)<span class="sc">*</span><span class="fu">mean</span>(<span class="fu">rbinom</span>(<span class="dv">10</span>,<span class="dv">1</span>,<span class="fl">0.65</span>))</span></code></pre></div>
<p>Since we are summing iid variables, the sampling distribution of the mean should look like a normal distribution. The mean should be close to 0.65, and the standard deviation <span class="math inline">\(\sqrt{\frac{p(1-p)}{n}} = \sqrt{\frac{0.65(1-0.65)}{10}}=0.151\)</span></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="HYPTESTCLT.html#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span>mean,<span class="at">data=</span>results)</span></code></pre></div>
<pre><code>##  min  Q1 median  Q3 max    mean        sd     n missing
##  0.1 0.5    0.7 0.8   1 0.64932 0.1505716 10000       0</code></pre>
<p>Remember from our lessons on probability, these results for the mean and standard deviation do not depend on the CLT, they are results from the properties of expectation on independent samples. The distribution of the sample mean, the shape of the sampling distribution, is approximately normal as a result of the CLT, Figure <a href="HYPTESTCLT.html#fig:dens214-fig">18.4</a>.</p>
<div class="figure"><span style="display:block;" id="fig:dens214-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/dens214-fig-1.png" alt="Sampling distribution of the sample proportion with sample size of 10." width="672" />
<p class="caption">
Figure 18.4: Sampling distribution of the sample proportion with sample size of 10.
</p>
</div>
<p>Note the sampling distribution of the sample mean has a bell-curvish shape, but with some skew to the left for this particular small sample size. That is why we state that the approximation improves with sample size.</p>
<p>As a way to determine the impact of the sample size on the inference to the population, let’s record how often a sample of 10 failed to indicate support for the measure. (How often was the sample proportion less than or equal to 0.5?) Remember, in this artificial example, we know that the population is in favor of the measure, 65% approval. However, if our point estimate is below 0.5, we would be led to believe that the population does not support the measure.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="HYPTESTCLT.html#cb5-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="HYPTESTCLT.html#cb5-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarise</span>(<span class="at">low_result=</span><span class="fu">mean</span>(<span class="sc">~</span>mean<span class="sc">&lt;=</span><span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>##   low_result
## 1     0.2505</code></pre>
<p>Even though we know that 65% of Colorado voters support the measure, a sample of size 10 failed to indicate support 25.05% of the time.</p>
<p>Let’s take a larger sample. In the code below, we will repeat the above but with a sample of size 25. Figure <a href="HYPTESTCLT.html#fig:dens215-fig">18.5</a> plots the sampling distribution.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="HYPTESTCLT.html#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">5501</span>)</span>
<span id="cb7-2"><a href="HYPTESTCLT.html#cb7-2" aria-hidden="true" tabindex="-1"></a>results<span class="ot">&lt;-</span><span class="fu">do</span>(<span class="dv">10000</span>)<span class="sc">*</span><span class="fu">mean</span>(<span class="fu">rbinom</span>(<span class="dv">25</span>,<span class="dv">1</span>,<span class="fl">0.65</span>))</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:dens215-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/dens215-fig-1.png" alt="Sampling distribution of the sample proportion with sample size of 25." width="672" />
<p class="caption">
Figure 18.5: Sampling distribution of the sample proportion with sample size of 25.
</p>
</div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="HYPTESTCLT.html#cb8-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="HYPTESTCLT.html#cb8-2" aria-hidden="true" tabindex="-1"></a> <span class="fu">summarise</span>(<span class="at">low_result=</span><span class="fu">mean</span>(<span class="sc">~</span>mean<span class="sc">&lt;=</span><span class="fl">0.5</span>))</span></code></pre></div>
<pre><code>##   low_result
## 1     0.0623</code></pre>
<p>When increasing the sample size to 25, the standard deviation of our sample proportion decreased. According to the central limit theorem, it should have decreased to <span class="math inline">\(\sigma/\sqrt{25}=\sqrt{\frac{p(1-p)}{25}}=0.095\)</span>. Also, the skew became less severe. Further, the sample of size 25 failed to indicate support only 6.23% of the time. It reasonably follows that an even larger sample would continue these trends. Figure <a href="HYPTESTCLT.html#fig:dens216-fig">18.6</a> demonstrates these trends.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="HYPTESTCLT.html#cb10-1" aria-hidden="true" tabindex="-1"></a>clt <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="HYPTESTCLT.html#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_histogram</span>(<span class="sc">~</span>mean,<span class="at">color=</span><span class="st">&quot;black&quot;</span>,<span class="at">fill=</span><span class="st">&quot;cyan&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="HYPTESTCLT.html#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_facet_grid</span>(<span class="sc">~</span>samp) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="HYPTESTCLT.html#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_bw</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:dens216-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/dens216-fig-1.png" alt="Sampling distribution of the proportion for different trail sizes." width="672" />
<p class="caption">
Figure 18.6: Sampling distribution of the proportion for different trail sizes.
</p>
</div>
</div>
<div id="summary-of-example" class="section level3 hasAnchor" number="18.2.4">
<h3><span class="header-section-number">18.2.4</span> Summary of example<a href="HYPTESTCLT.html#summary-of-example" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In this example, we knew the true proportion of voters who supported the proposition. Based on that knowledge, we simulated the behavior of the sample proportion. We did this by taking a sample of size <span class="math inline">\(n\)</span>, recording the sample proportion and sample mean, and repeating that process thousands of times. In reality, we will not know the true underlying level of support; further, we will not take a sample repeatedly thousands of times from the parent population. Sampling can be expensive and time-consuming. Thus, we would take one random sample of size <span class="math inline">\(n\)</span>, and acknowledge that the resulting sample proportion is but one observation from an underlying normal distribution. We would then determine what values of <span class="math inline">\(\pi\)</span> (the true unknown population proportion) could reasonably have resulted in the observed sample proportion.</p>
</div>
</div>
<div id="other-distribution-for-estimators" class="section level2 hasAnchor" number="18.3">
<h2><span class="header-section-number">18.3</span> Other distribution for estimators<a href="HYPTESTCLT.html#other-distribution-for-estimators" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Prior to using the CLT in hypothesis testing, we want to discuss other sampling distributions that are based on the CLT or normality assumptions. A large part of theoretical statistics has been about mathematically deriving the distribution of sample statistics. In these methods we obtain a sample statistic, determine the distribution of that statistic under certain conditions, and then use that information to make a statement about the population parameter.</p>
<div id="students-t" class="section level3 hasAnchor" number="18.3.1">
<h3><span class="header-section-number">18.3.1</span> Student’s t<a href="HYPTESTCLT.html#students-t" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Let <span class="math inline">\(X_1,X_2,...,X_n\)</span> be an iid sequence of random variables, each with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>. Recall that the central limit theorem tells us that
<span class="math display">\[
\bar{X}\overset{approx}{\sim}\textsf{Norm}(\mu,\sigma/\sqrt{n})
\]</span></p>
<p>Rearranging:
<span class="math display">\[
{\bar{X}-\mu\over\sigma/\sqrt{n}}\overset{approx}{\sim}\textsf{Norm}(0,1)
\]</span></p>
<p>Again, <span class="math inline">\(\sigma\)</span> is unknown. Thus, we have to estimate it. We can estimate it with <span class="math inline">\(S\)</span>, but now we need to know the distribution of <span class="math inline">\({\bar{X}-\mu\over S/\sqrt{n}}\)</span>. This <em>does not</em> follow the normal distribution.</p>
<p>Lemma: Let <span class="math inline">\(X_1,X_2,...,X_n\)</span> be an iid sequence of random variables from a normal population with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>. Then,
<span class="math display">\[
{\bar{X}-\mu\over S/\sqrt{n}} \sim \textsf{t}(n-1)
\]</span></p>
<p>The <span class="math inline">\(\textsf{t}(n-1)\)</span> distribution is read as the “<span class="math inline">\(t\)</span>” distribution. The <span class="math inline">\(t\)</span> distribution has one parameter: degrees of freedom. The expression above <span class="math inline">\(\left({\bar{X}-\mu\over S/\sqrt{n}}\right)\)</span> is referred to as the <span class="math inline">\(t\)</span> statistic.</p>
<p>Similar to the chi-squared distribution, we won’t go over the proof, but it follows from some simple algebra and from the fact that the ratio between a standard normal random variable and the square root of a chi-squared random variable, divided by it’s degrees of freedom follows a <span class="math inline">\(t\)</span> distribution.</p>
<p>The <span class="math inline">\(t\)</span> distribution is very similar to the standard normal distribution, but has longer tails. This seems to make sense in the context of estimating <span class="math inline">\(\mu\)</span> since substituting <span class="math inline">\(S\)</span> for <span class="math inline">\(\sigma\)</span> adds variability to the random variable.
Figure <a href="HYPTESTCLT.html#fig:t211-fig">18.7</a> is a plot of the <span class="math inline">\(t\)</span> distribution, shown as a blue line, and has a bell shape that looks very similar to a normal distribution, red line. However, its tails are thicker, which means observations are more likely to fall beyond two standard deviations from the mean than under the normal distribution. When our sample is small, the value <span class="math inline">\(s\)</span> used to compute the standard error isn’t very reliable. The extra thick tails of the <span class="math inline">\(t\)</span> distribution are exactly the correction we need to resolve this problem. When the degrees of freedom is about 30 or more, the <span class="math inline">\(t\)</span> distribution is nearly indistinguishable from the normal distribution.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="HYPTESTCLT.html#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_dist</span>(<span class="st">&quot;norm&quot;</span>,<span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="HYPTESTCLT.html#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_dist</span>(<span class="st">&quot;t&quot;</span>,<span class="at">df=</span><span class="dv">3</span>,<span class="at">color=</span><span class="st">&quot;blue&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="HYPTESTCLT.html#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_bw</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:t211-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/t211-fig-1.png" alt="The distibtion of t." width="672" />
<p class="caption">
Figure 18.7: The distibtion of t.
</p>
</div>
</div>
</div>
<div id="hypothesis-tests-using-the-clt" class="section level2 hasAnchor" number="18.4">
<h2><span class="header-section-number">18.4</span> Hypothesis tests using the CLT<a href="HYPTESTCLT.html#hypothesis-tests-using-the-clt" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We are now ready to repeat some of our previous problems using the mathematically derived sampling distribution via the CLT.</p>
<div id="body-temperature" class="section level3 hasAnchor" number="18.4.1">
<h3><span class="header-section-number">18.4.1</span> Body temperature<a href="HYPTESTCLT.html#body-temperature" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>We will repeat the body temperature analysis using the CLT. We will use <span class="math inline">\(\alpha = 0.05\)</span></p>
<div id="step-1--state-the-null-and-alternative-hypotheses-5" class="section level4 hasAnchor" number="18.4.1.1">
<h4><span class="header-section-number">18.4.1.1</span> Step 1- State the null and alternative hypotheses<a href="HYPTESTCLT.html#step-1--state-the-null-and-alternative-hypotheses-5" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p><span class="math inline">\(H_0\)</span>: The average body temperature is 98.6; <span class="math inline">\(\mu = 98.6\)</span><br />
<span class="math inline">\(H_A\)</span>: The average body temperature is less than 98.6; <span class="math inline">\(\mu &lt; 98.6\)</span></p>
</div>
<div id="step-2---compute-a-test-statistic.-7" class="section level4 hasAnchor" number="18.4.1.2">
<h4><span class="header-section-number">18.4.1.2</span> Step 2 - Compute a test statistic.<a href="HYPTESTCLT.html#step-2---compute-a-test-statistic.-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We don’t know the population variance, so we will use the <span class="math inline">\(t\)</span> distribution. Remember that</p>
<p><span class="math display">\[
{\bar{X}-\mu\over S/\sqrt{n}} \sim \textsf{t}(n-1)
\]</span>
thus our test statistic is</p>
<p><span class="math display">\[
\frac{\bar{x}-98.6}{s/\sqrt{n}}
\]</span></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="HYPTESTCLT.html#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">favstats</span>(<span class="sc">~</span>temperature,<span class="at">data=</span>temperature)</span></code></pre></div>
<pre><code>##   min   Q1 median   Q3   max     mean        sd   n missing
##  96.3 97.8   98.3 98.7 100.8 98.24923 0.7331832 130       0</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="HYPTESTCLT.html#cb14-1" aria-hidden="true" tabindex="-1"></a>temperature <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="HYPTESTCLT.html#cb14-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(temperature),<span class="at">sd=</span><span class="fu">sd</span>(temperature),<span class="at">test_stat=</span>(mean<span class="fl">-98.6</span>)<span class="sc">/</span>(sd<span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">130</span>)))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##    mean    sd test_stat
##   &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;
## 1  98.2 0.733     -5.45</code></pre>
<p>We are over 5 standard deviation below the null hypothesis mean. We have some assumptions that we will discuss at the end of this problem.</p>
</div>
<div id="step-3---determine-the-p-value.-7" class="section level4 hasAnchor" number="18.4.1.3">
<h4><span class="header-section-number">18.4.1.3</span> Step 3 - Determine the p-value.<a href="HYPTESTCLT.html#step-3---determine-the-p-value.-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We now want to find the p-value from <span class="math inline">\(\Prob(t \leq -5.45)\)</span> on 129 degrees of freedom, given the null hypothesis is true, which is that the probability of success is 0.50. We will use <code>R</code> to get the one-sided p-value.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="HYPTESTCLT.html#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pt</span>(<span class="sc">-</span><span class="fl">5.45</span>,<span class="dv">129</span>)</span></code></pre></div>
<pre><code>## [1] 1.232178e-07</code></pre>
<p>We could also use the <code>R</code> function <code>t_test()</code>.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="HYPTESTCLT.html#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t_test</span>(<span class="sc">~</span>temperature,<span class="at">data=</span>temperature,<span class="at">mu=</span><span class="fl">98.6</span>,<span class="at">alternative=</span><span class="st">&quot;less&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  One Sample t-test
## 
## data:  temperature
## t = -5.4548, df = 129, p-value = 1.205e-07
## alternative hypothesis: true mean is less than 98.6
## 95 percent confidence interval:
##      -Inf 98.35577
## sample estimates:
## mean of x 
##  98.24923</code></pre>
<p>Notice this p-value is much smaller than the p-value from the method used in homework problem 3 in the last chapter. That is because this test statistic has more assumptions and uses the data as continuous and not discrete.</p>
</div>
<div id="step-4---draw-a-conclusion-7" class="section level4 hasAnchor" number="18.4.1.4">
<h4><span class="header-section-number">18.4.1.4</span> Step 4 - Draw a conclusion<a href="HYPTESTCLT.html#step-4---draw-a-conclusion-7" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Based our data, if the true mean body temperature is 98.6, then the probability of observing a mean of 98.25 or less is 0.00000012. This is too unlikely so we reject the hypothesis that the average body temperature is 98.6.</p>
</div>
</div>
</div>
<div id="summary-and-rules-of-thumb" class="section level2 hasAnchor" number="18.5">
<h2><span class="header-section-number">18.5</span> Summary and rules of thumb<a href="HYPTESTCLT.html#summary-and-rules-of-thumb" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>We have covered a great deal in this lesson. At its core, the central limit theorem is a statement about the distribution of a sum of independent identically distributed random variables. This sum is approximately normal. First we summarize rules of thumb for the use of the CLT and <span class="math inline">\(t\)</span> distribution.</p>
<div id="numerical-data-1" class="section level3 hasAnchor" number="18.5.1">
<h3><span class="header-section-number">18.5.1</span> Numerical data<a href="HYPTESTCLT.html#numerical-data-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ol style="list-style-type: decimal">
<li><p>The central limit works regardless of the distribution. However, if the parent population is highly skewed, then more data is needed. The CLT works well once the sample sizes exceed 30 to 40. If the data is fairly symmetric, then less data is needed.</p></li>
<li><p>When estimating the mean and standard error from a sample of numerical data, the <span class="math inline">\(t\)</span> distribution is a little more accurate than the normal model. But there is an assumption that the parent population is normally distributed. This distribution works well even for small samples as long as the data is close to symmetrical and unimodal.</p></li>
<li><p>For medium samples, at least 15 data points, the <span class="math inline">\(t\)</span> distribution still works as long as the data is roughly symmetric and unimodal.</p></li>
<li><p>For large data sets 30-40 or more, the <span class="math inline">\(t\)</span> or even the normal can be used but we suggest you always use the <span class="math inline">\(t\)</span>.</p></li>
</ol>
<p>Now, let’s discuss the assumptions of the <span class="math inline">\(t\)</span> distribution and how to check them.</p>
<ol style="list-style-type: decimal">
<li><p>Independence of observations. This is a difficult assumption to verify. If we collect a simple random sample from less than 10% of the population, or if the data are from an experiment or random process, we feel better about this assumption. If the data comes from an experiment, we can plot the data versus time collected to see if there are any patterns that indicate a relationship. A design of experiment course discusses these ideas.</p></li>
<li><p>Observations come from a nearly normal distribution. This second condition is difficult to verify with small data sets. We often (i) take a look at a plot of the data for obvious departures from the normal model, usually in the form of prominent outliers, and (ii) consider whether any previous experiences alert us that the data may not be nearly normal. However, if the sample size is somewhat large, then we can relax this condition, e.g. moderate skew is acceptable when the sample size is 30 or more, and strong skew is acceptable when the size is about 60 or more.</p>
<p>A typical plot to use to evaluate the normality assumption is called the quantile-quantile plot. We form a scatterplot of the empirical quantiles from the data versus exact quantile values from the theoretical distribution. If the points fall along a line then the data match the distribution. An exact match is not realistic, so we look for major departures from the line.</p></li>
</ol>
<p>Figure <a href="HYPTESTCLT.html#fig:qq211-fig">18.8</a> is our normal-quantile plot for the body temperature data. The largest value may be an outlier, we may want to verify it was entered correctly. The fact that the points are above the line for the larger values and below the line for the smaller values indicates that our data may have longer tails than the normal distribution. There are really only 3 values in the larger quantiles so in fact the data may be slightly skewed to the left, this was also indicated by a comparison of the mean and median. However, since we have 130 data points these results should not impact our findings.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="HYPTESTCLT.html#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gf_qq</span>(<span class="sc">~</span>temperature,<span class="at">data=</span>temperature) <span class="sc">%&gt;%</span></span>
<span id="cb20-2"><a href="HYPTESTCLT.html#cb20-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_qqline</span>(<span class="sc">~</span>temperature,<span class="at">data=</span>temperature) <span class="sc">%&gt;%</span></span>
<span id="cb20-3"><a href="HYPTESTCLT.html#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gf_theme</span>(<span class="fu">theme_bw</span>())</span></code></pre></div>
<div class="figure"><span style="display:block;" id="fig:qq211-fig"></span>
<img src="21-Central-Limit-Theorem_files/figure-html/qq211-fig-1.png" alt="Q-Q plot for body temperature data." width="672" />
<p class="caption">
Figure 18.8: Q-Q plot for body temperature data.
</p>
</div>
<p>Extreme data points, outliers, can be cause for concern. In later chapters, we will look for ways to detect outliers but we have seen them in our boxplots. Outliers are problematic because normal distributions rarely have outliers so the presence of one may indicate a departure from normality. Second, outliers have a big impact on estimation methods for the mean and standard deviation whether it is a method of moments or maximum likelihood estimate.</p>
<p>We can also check the impacts of the assumptions by using other methods for the hypothesis test. If all methods give the same conclusion, we can be confident in the results. Another way to check robustness to assumptions is to simulate data from different distributions and evaluate the performance of the test under the simulated data.</p>
</div>
<div id="binary-data" class="section level3 hasAnchor" number="18.5.2">
<h3><span class="header-section-number">18.5.2</span> Binary data<a href="HYPTESTCLT.html#binary-data" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The distribution of a binomial random variable or simple scalar transformations of it, such as the proportions of success found by dividing by the sample size, are approximately normal by the CLT. Since binomial random variables are bounded by zero and the number of trails, we have to make sure our probability of success is not close to zero or one, that is the number of successes is not close to 0 or <span class="math inline">\(n\)</span>. A general rule of thumb is that the number of success and failures be at least 10.</p>
</div>
<div id="tappers-and-listeners-1" class="section level3 hasAnchor" number="18.5.3">
<h3><span class="header-section-number">18.5.3</span> Tappers and listeners<a href="HYPTESTCLT.html#tappers-and-listeners-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="step-1--state-the-null-and-alternative-hypotheses-6" class="section level4 hasAnchor" number="18.5.3.1">
<h4><span class="header-section-number">18.5.3.1</span> Step 1- State the null and alternative hypotheses<a href="HYPTESTCLT.html#step-1--state-the-null-and-alternative-hypotheses-6" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Here are the two hypotheses:</p>
<p><span class="math inline">\(H_0\)</span>: The tappers are correct, and generally 50% of the time listeners are able to guess the tune. <span class="math inline">\(p = 0.50\)</span><br />
<span class="math inline">\(H_A\)</span>: The tappers are incorrect, and either more than or less than 50% of listeners will be able to guess the tune. <span class="math inline">\(p \neq 0.50\)</span></p>
</div>
<div id="step-2---compute-a-test-statistic.-8" class="section level4 hasAnchor" number="18.5.3.2">
<h4><span class="header-section-number">18.5.3.2</span> Step 2 - Compute a test statistic.<a href="HYPTESTCLT.html#step-2---compute-a-test-statistic.-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>The test statistic that we want to use is the sample mean <span class="math inline">\(\bar{X}\)</span>, this is a method of moments estimate of the probability of success. Since these are independent samples from the same binomial distribution, by the CLT</p>
<p><span class="math display">\[
\bar{X} \overset{approx}{\sim}\textsf{Norm}\left(\pi,\sqrt\frac{\pi(1-\pi)}{n}\right)
\]</span></p>
<p>As we learned, this approximation improves with sample size. As a rule of thumb, most analysts are comfortable with using the CLT for this problem if the number of success and failures are both 10 or greater.</p>
<p>In our study 42 out of 120 listeners (<span class="math inline">\(\bar{x}=\hat{p} = 0.35\)</span>) were able to guess the tune. This is the observed value of test statistic.</p>
</div>
<div id="step-3---determine-the-p-value.-8" class="section level4 hasAnchor" number="18.5.3.3">
<h4><span class="header-section-number">18.5.3.3</span> Step 3 - Determine the p-value.<a href="HYPTESTCLT.html#step-3---determine-the-p-value.-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>We now want to find the p-value from the one-sided probability <span class="math inline">\(\Prob(\bar{X} \leq 0.35)\)</span> given the null hypothesis is true, the probability of success is 0.50. We will use <code>R</code> to get the one-sided value and then double it since the test is two-sided and the sampling distribution is symmetrical.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="HYPTESTCLT.html#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pnorm</span>(<span class="fl">0.35</span>,<span class="at">mean=</span>.<span class="dv">5</span>,<span class="at">sd=</span><span class="fu">sqrt</span>(.<span class="dv">5</span><span class="sc">*</span>.<span class="dv">5</span><span class="sc">/</span><span class="dv">120</span>))</span></code></pre></div>
<pre><code>## [1] 0.001015001</code></pre>
<p>That is a small p-value and consistent with what we would got using both the exact binomial test and the simulation empirical p-values.</p>
<blockquote>
<p><strong>Important note</strong>:
In the calculation of the standard deviation of the sampling distribution, we used the null hypothesized value of the probability of success.</p>
</blockquote>
</div>
<div id="step-4---draw-a-conclusion-8" class="section level4 hasAnchor" number="18.5.3.4">
<h4><span class="header-section-number">18.5.3.4</span> Step 4 - Draw a conclusion<a href="HYPTESTCLT.html#step-4---draw-a-conclusion-8" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Based on our data, if the listeners were guessing correct 50% of the time, there is less than a 1 in 1000 probability that only 42 or less or 78 or more listeners would get it right. This is much less than 0.05, so we reject that the listeners are guessing correctly half of the time.</p>
<p>Note that <code>R</code> has built in functions to perform this test. If you explore these functions, use <code>?prop.test</code> to learn more, you will find options to improve the performance of the test. You are welcome and should read about these methods. Again, before computers, researchers spent time optimizing the performance of the asymptotic methods such as the CLT.</p>
<p>Here is the test of a single proportion using <code>R</code>.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="HYPTESTCLT.html#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prop.test</span>(<span class="dv">42</span>,<span class="dv">120</span>)</span></code></pre></div>
<pre><code>## 
##  1-sample proportions test with continuity correction
## 
## data:  42 out of 120
## X-squared = 10.208, df = 1, p-value = 0.001398
## alternative hypothesis: true p is not equal to 0.5
## 95 percent confidence interval:
##  0.2667083 0.4430441
## sample estimates:
##    p 
## 0.35</code></pre>
<p>The p-value is small, reported as <span class="math inline">\(0.0014\)</span>. We will study the confidence interval soon so don’t worry about that part of the output. The alternative hypothesis is also listed.</p>
<blockquote>
<p><strong>Exercise</strong>:<br />
How do you conduct a one-sided test? What if the null value where 0.45?<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
</blockquote>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="HYPTESTCLT.html#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pval</span>(<span class="fu">prop.test</span>(<span class="dv">42</span>,<span class="dv">120</span>,<span class="at">alternative=</span><span class="st">&quot;less&quot;</span>,<span class="at">p=</span>.<span class="dv">45</span>))</span></code></pre></div>
<pre><code>##   p.value 
## 0.0174214</code></pre>
<p>The exact test uses the function <code>binom.test()</code>.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="HYPTESTCLT.html#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">binom.test</span>(<span class="dv">42</span>,<span class="dv">120</span>)</span></code></pre></div>
<pre><code>## 
## 
## 
## data:  42 out of 120
## number of successes = 42, number of trials = 120, p-value = 0.001299
## alternative hypothesis: true probability of success is not equal to 0.5
## 95 percent confidence interval:
##  0.2652023 0.4423947
## sample estimates:
## probability of success 
##                   0.35</code></pre>
<p>This is the same as</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="HYPTESTCLT.html#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="dv">2</span><span class="sc">*</span><span class="fu">pbinom</span>(<span class="dv">42</span>,<span class="dv">120</span>,.<span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [1] 0.001299333</code></pre>
</div>
</div>
</div>
<div id="homework-problems-20" class="section level2 hasAnchor" number="18.6">
<h2><span class="header-section-number">18.6</span> Homework Problems<a href="HYPTESTCLT.html#homework-problems-20" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li>Suppose we roll a fair six-sided die and let <span class="math inline">\(X\)</span> be the resulting number. The distribution of <span class="math inline">\(X\)</span> is discrete uniform. (Each of the six discrete outcomes is equally likely.)</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Suppose we roll the fair die 5 times and record the value of <span class="math inline">\(\bar{X}\)</span>, the <em>mean</em> of the resulting rolls. Under the central limit theorem, what should be the distribution of <span class="math inline">\(\bar{X}\)</span>?<br />
</p></li>
<li><p>Simulate this process in <code>R</code>. Plot the resulting empirical distribution of <span class="math inline">\(\bar{X}\)</span> and report the mean and standard deviation of <span class="math inline">\(\bar{X}\)</span>. Was it what you expected?</p>
<p>(HINT: You can simulate a die roll using the <code>sample</code> function. Be careful and make sure you use it properly.)</p></li>
<li><p>Repeat parts a) and b) for <span class="math inline">\(n=20\)</span> and <span class="math inline">\(n=50\)</span>. Describe what you notice. Make sure all three plots are plotted on the same <span class="math inline">\(x\)</span>-axis scale. You can use facets if you combine your data into one <code>tibble</code>.</p></li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li><p>The nutrition label on a bag of potato chips says that a one ounce (28 gram) serving of potato chips has 130 calories and contains ten grams of fat, with three grams of saturated fat. A random sample of 35 bags yielded a sample mean of 134 calories with a standard deviation of 17 calories. Is there evidence that the nutrition label does not provide an accurate measure of calories in the bags of potato chips? The conditions necessary for applying the normal model have been checked and are satisfied.</p>
<p>The question has been framed in terms of two possibilities: the nutrition label accurately lists the correct average calories per bag of chips or it does not, which may be framed as a hypothesis test.</p></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Write the null and alternative hypothesis.<br />
</li>
<li>What level of significance are you going to use?<br />
</li>
<li>What is the distribution of the test statistic <span class="math inline">\({\bar{X}-\mu\over S/\sqrt{n}}\)</span>? Calculate the observed value.<br />
</li>
<li>Calculate a p-value.<br />
</li>
<li>Draw a conclusion.</li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li><p>Paired data</p>
<p>Are textbooks actually cheaper online? Here we compare the price of textbooks at the University of California, Los Angeles’ (UCLA’s) bookstore and prices at Amazon.com. Seventy-three UCLA courses were randomly sampled in Spring 2010, representing less than 10% of all UCLA courses. When a class had multiple books, only the most expensive text was considered.</p>
<p>The data is in the file <code>textbooks.csv</code> under the data folder.</p>
<p>Each textbook has two corresponding prices in the data set: one for the UCLA bookstore and one for Amazon. Therefore, each textbook price from the UCLA bookstore has a natural correspondence with a textbook price from Amazon. When two sets of observations have this special correspondence, they are said to be <strong>paired</strong>.</p>
<p>To analyze paired data, it is often useful to look at the difference in outcomes of each pair of observations. In <code>textbooks</code>, we look at the difference in prices, which is represented as the <code>diff</code> variable. It is important that we always subtract using a consistent order; here Amazon prices are always subtracted from UCLA prices.</p></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Is this data tidy? Explain.<br />
</li>
<li>Make a scatterplot of the UCLA price versus the Amazon price. Add a 45 degree line to the plot.<br />
</li>
<li>Make a histogram of the differences in price.</li>
</ol>
<p>The hypotheses are:<br />
<span class="math inline">\(H_0\)</span>: <span class="math inline">\(\mu_{diff}=0\)</span>. There is no difference in the average textbook price.<br />
<span class="math inline">\(H_A\)</span>: <span class="math inline">\(\mu_{diff} \neq 0\)</span>. There is a difference in average prices.</p>
<ol start="4" style="list-style-type: lower-alpha">
<li>To use a <span class="math inline">\(t\)</span> distribution, the variable <code>diff</code> has to independent and normally distributed. Since the 73 books represent less than 10% of the population, the assumption that the random sample is independent is reasonable. Check normality using <code>qqnorsim()</code> from the <strong>openintro</strong> package. It generates 8 qq plots of simulated normal data that you can use to judge the <code>diff</code> variable.<br />
</li>
<li>Run a <span class="math inline">\(t\)</span> test on the <code>diff</code> variable. Report the p-value and conclusion.<br />
</li>
<li>Create a bootstrap distribution and generate a 95% confidence interval on the mean of the differences, the <code>diff</code> column.<br />
</li>
<li>If there is really no differences between book sources, the variable <code>more</code> is a binomial and under the null the probably of success is <span class="math inline">\(\pi = 0.5\)</span>. Run a hypothesis test using the variable <code>more</code>.<br />
</li>
<li>Could you use a permutation test on this example? Explain.</li>
</ol>
<ol start="4" style="list-style-type: decimal">
<li><p>In this lesson, we have used the expression <em>degrees of freedom</em> a lot. What does this expression mean? When we have sample of size <span class="math inline">\(n\)</span>, why are there <span class="math inline">\(n-1\)</span> degrees of freedom for the <span class="math inline">\(t\)</span> distribution? Give a short concise answer (about one paragraph). You will likely have to do a little research on your own.</p></li>
<li><p>Deborah Toohey is running for Congress, and her campaign manager claims she has more than 50% support from the district’s electorate. Ms. Toohey’s opponent claimed that Ms. Toohey has <strong>less</strong> than 50%. Set up a hypothesis test to evaluate who is right.</p></li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Should we run a one-sided or two-sided hypothesis test?<br />
</li>
<li>Write the null and alternative hypothesis.<br />
</li>
<li>What level of significance are you going to use?<br />
</li>
<li>What are the assumptions of this test?<br />
</li>
<li>Calculate the test statistic.<br />
</li>
<li>Calculate a p-value.<br />
</li>
<li>Draw a conclusion.</li>
</ol>
<p>Note: A newspaper collects a simple random sample of 500 likely voters in the district and estimates Toohey’s support to be 52%.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>In general, the distribution is reasonably symmetric. It is unimodal and looks like a normal distribution.<a href="HYPTESTCLT.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>We will only extract the p-value in this exercise<a href="HYPTESTCLT.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="PVALUES.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="CI.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": null,
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/DS-USAFA/Probability-and-Statistics-MASTER/21-Central-Limit-Theorem.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
},
"info": false
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
